import { Head, router, useForm } from '@inertiajs/react';
import { BadgeCheck, Ban, BookOpenCheck, Download, ExternalLink, FileCheck2, FileText, GraduationCap, Landmark, QrCode, ReceiptText, ShieldCheck, Sparkles, UserRound, WalletCards } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { ModalForm } from '@/components/ModalForm';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Student = { id: number; nim: string; user: { name: string; email?: string }; program?: { code: string; name: string; degree?: string } };
type Term = { id: number; code: string; name: string; semester: string };
type Registration = { id: number; academic_term: Term; enrollments_count: number; published_grades_count: number; reviewed_at: string | null };
type Bill = { id: number; invoice_number: string; description: string; amount: string; paid_amount: string; due_on: string | null; status: string; academic_term?: Term };
type Allocation = { id: number; amount: string; billing_item?: { invoice_number: string; description: string } };
type Payment = { id: number; external_reference: string; provider: string; amount: string; paid_at: string | null; status: string; allocations: Allocation[] };
type Document = { id: number; document_number: string; verification_code: string; type: DocType; issued_at: string; revoked_at: string | null; revocation_reason: string | null; issuer?: { name: string }; revoker?: { name: string } };
type DocType = 'krs' | 'khs' | 'transcript' | 'invoice' | 'receipt';
type Props = { mode: 'student' | 'manager'; selectedStudent: Student | null; studentOptions: Student[]; registrations: Registration[]; bills: Bill[]; payments: Payment[]; issuedDocuments: Document[]; access: { academic: boolean; finance: boolean; issue: boolean; revoke: boolean } };

const typeMeta: Record<DocType, { label: string; short: string; tone: string }> = {
  krs: { label: 'Kartu Rencana Studi', short: 'KRS', tone: 'bg-sky-50 text-sky-700' },
  khs: { label: 'Kartu Hasil Studi', short: 'KHS', tone: 'bg-violet-50 text-violet-700' },
  transcript: { label: 'Transkrip Nilai Akademik', short: 'TR', tone: 'bg-emerald-50 text-emerald-700' },
  invoice: { label: 'Tagihan Pendidikan', short: 'INV', tone: 'bg-amber-50 text-amber-700' },
  receipt: { label: 'Kwitansi Pembayaran', short: 'KWT', tone: 'bg-rose-50 text-rose-700' },
};

export default function DocumentsPage(props: Props) {
  const [revokeDocument, setRevokeDocument] = useState<Document | null>(null);
  const revokeForm = useForm({ reason: '' });
  const activeCount = props.issuedDocuments.filter((item) => !item.revoked_at).length;

  function selectStudent(id: string) { router.get('/documents', id ? { student_id: id } : {}, { replace: true }); }
  function issue(type: DocType, sourceId: number) { router.post(`/documents/issue/${type}/${sourceId}`, {}, { preserveScroll: true }); }
  function openRevoke(item: Document) { revokeForm.reset(); revokeForm.clearErrors(); setRevokeDocument(item); }
  function revoke(event: FormEvent) { event.preventDefault(); if (!revokeDocument) return; revokeForm.patch(`/documents/${revokeDocument.id}/revoke`, { preserveScroll: true, onSuccess: () => setRevokeDocument(null) }); }

  return <DashboardLayout><Head title="Dokumen Resmi" />
    <header className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="flex items-center gap-2 text-sm font-semibold text-emerald-600"><Sparkles size={16} /> Digital document trust center</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">Dokumen resmi.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Terbitkan, unduh PDF, dan verifikasi KRS, KHS, transkrip, tagihan, serta kwitansi melalui registri digital yang terlacak.</p></div>{props.mode === 'manager' && <label className="block sm:min-w-80"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Mahasiswa aktif</span><select className="input mt-2 bg-white" value={props.selectedStudent?.id ?? ''} onChange={(e) => selectStudent(e.target.value)}><option value="">Pilih mahasiswa</option>{props.studentOptions.map((student) => <option key={student.id} value={student.id}>{student.nim} · {student.user.name}</option>)}</select></label>}</header>

    <section className="relative mt-7 overflow-hidden rounded-3xl bg-gradient-to-br from-[#051c18] via-[#0a4237] to-[#0b715c] p-6 text-white shadow-xl shadow-emerald-950/15 sm:p-8"><div className="absolute -right-20 -top-24 size-72 rounded-full bg-emerald-300/15 blur-3xl" /><div className="absolute -bottom-24 left-1/3 size-56 rounded-full bg-cyan-300/10 blur-3xl" /><div className="relative grid gap-7 lg:grid-cols-[1fr_auto]"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-emerald-300">Verified academic identity</p><h2 className="mt-3 text-2xl font-semibold">{props.selectedStudent ? props.selectedStudent.user.name : 'Pilih mahasiswa untuk memulai'}</h2>{props.selectedStudent && <p className="mt-2 text-sm text-emerald-100/70">{props.selectedStudent.nim} · {props.selectedStudent.program?.name} ({props.selectedStudent.program?.code})</p>}<div className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white/10 px-3 py-2 text-xs ring-1 ring-white/10"><ShieldCheck size={15} className="text-emerald-300" /> Snapshot terkunci · SHA-256 · QR verification</div></div><div className="grid grid-cols-2 gap-2"><DarkMetric value={String(props.issuedDocuments.length)} label="Total terbit" /><DarkMetric value={String(activeCount)} label="Dokumen aktif" /><DarkMetric value={String(props.registrations.length)} label="Semester" /><DarkMetric value={String(props.payments.length)} label="Pembayaran" /></div></div></section>

    {!props.selectedStudent ? <Empty icon={<UserRound size={28} />} title="Belum ada mahasiswa dipilih" text="Pilih mahasiswa dari daftar untuk melihat dokumen yang tersedia dan riwayat penerbitannya." /> : <>
      <div className="mt-7 grid gap-6 xl:grid-cols-2">
        {props.access.academic && <Panel icon={<GraduationCap size={20} />} eyebrow="Academic records" title="Dokumen akademik" description="KRS tersedia setelah persetujuan; KHS dan transkrip setelah nilai dipublikasikan.">
          <div className="space-y-3">{props.registrations.map((registration) => { const khsReady = registration.enrollments_count > 0 && registration.published_grades_count === registration.enrollments_count; return <article key={registration.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="font-semibold text-slate-900">{registration.academic_term.name}</p><p className="mt-1 text-xs text-slate-400">{registration.academic_term.code} · {registration.enrollments_count} mata kuliah · {registration.published_grades_count} nilai terbit</p></div><div className="flex flex-wrap gap-2"><IssueButton disabled={!props.access.issue} onClick={() => issue('krs', registration.id)} icon={<BookOpenCheck size={14} />} label="Terbitkan KRS" /><IssueButton disabled={!props.access.issue || !khsReady} onClick={() => issue('khs', registration.id)} icon={<BadgeCheck size={14} />} label={khsReady ? 'Terbitkan KHS' : 'Nilai belum lengkap'} /></div></div></article>; })}{!props.registrations.length && <InlineEmpty text="Belum ada KRS yang disetujui." />}</div>
          <div className="mt-4 rounded-2xl bg-gradient-to-r from-emerald-50 to-teal-50 p-4 ring-1 ring-emerald-100"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-white text-emerald-600 shadow-sm"><FileCheck2 size={19} /></div><div><p className="text-sm font-semibold text-slate-900">Transkrip kumulatif</p><p className="mt-1 text-xs text-slate-500">Menggabungkan seluruh nilai published/finalized.</p></div></div><IssueButton disabled={!props.access.issue || !props.registrations.some((item) => item.published_grades_count > 0)} onClick={() => issue('transcript', props.selectedStudent!.id)} icon={<FileText size={14} />} label="Terbitkan transkrip" /></div></div>
        </Panel>}
        {props.access.finance && <Panel icon={<Landmark size={20} />} eyebrow="Financial records" title="Dokumen keuangan" description="Tagihan dan kwitansi memakai snapshot ledger pada saat diterbitkan.">
          <div className="max-h-[430px] space-y-3 overflow-y-auto pr-1">{props.bills.map((bill) => <article key={`b-${bill.id}`} className="flex flex-col justify-between gap-3 rounded-2xl border border-slate-200 p-4 sm:flex-row sm:items-center"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{bill.description}</p><p className="mt-1 text-xs text-slate-400">{bill.invoice_number} · {money(Number(bill.amount))} · {bill.status}</p></div><IssueButton disabled={!props.access.issue} onClick={() => issue('invoice', bill.id)} icon={<ReceiptText size={14} />} label="Tagihan PDF" /></article>)}{props.payments.map((payment) => <article key={`p-${payment.id}`} className="flex flex-col justify-between gap-3 rounded-2xl border border-slate-200 p-4 sm:flex-row sm:items-center"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{money(Number(payment.amount))} · {payment.provider.toUpperCase()}</p><p className="mt-1 truncate text-xs text-slate-400">{payment.external_reference} · {payment.paid_at ? dateTime(payment.paid_at) : 'Waktu belum tercatat'}</p></div><IssueButton disabled={!props.access.issue} onClick={() => issue('receipt', payment.id)} icon={<WalletCards size={14} />} label="Kwitansi PDF" /></article>)}{!props.bills.length && !props.payments.length && <InlineEmpty text="Belum ada tagihan atau pembayaran." />}</div>
        </Panel>}
      </div>

      <section className="mt-7"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-emerald-600">Document registry</p><h2 className="mt-1 text-xl font-semibold text-slate-950">Riwayat penerbitan</h2></div><div className="hidden items-center gap-2 text-xs text-slate-400 sm:flex"><QrCode size={15} /> Verifikasi publik aktif</div></div><div className="mt-4 overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div className="divide-y divide-slate-100">{props.issuedDocuments.map((item) => <article key={item.id} className="flex flex-col justify-between gap-4 p-5 lg:flex-row lg:items-center"><div className="flex min-w-0 gap-3"><div className={`flex size-11 shrink-0 items-center justify-center rounded-xl font-bold ${typeMeta[item.type].tone}`}>{typeMeta[item.type].short}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-semibold text-slate-900">{typeMeta[item.type].label}</p><Status revoked={Boolean(item.revoked_at)} /></div><p className="mt-1 text-[11px] text-slate-400">{item.document_number} · {dateTime(item.issued_at)} · {item.issuer?.name}</p>{item.revocation_reason && <p className="mt-2 text-xs text-rose-600">Dicabut: {item.revocation_reason}</p>}</div></div><div className="flex flex-wrap gap-2"><a href={`/verify/documents/${item.verification_code}`} target="_blank" rel="noreferrer" className="action-secondary"><QrCode size={14} /> Verifikasi</a><a href={`/documents/${item.id}`} target="_blank" rel="noreferrer" className="action-secondary"><ExternalLink size={14} /> Lihat</a><a href={`/documents/${item.id}/pdf`} className="action-secondary"><Download size={14} /> PDF</a>{props.access.revoke && !item.revoked_at && <button onClick={() => openRevoke(item)} className="inline-flex items-center gap-2 rounded-xl bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700 hover:bg-rose-100"><Ban size={14} /> Cabut</button>}</div></article>)}{!props.issuedDocuments.length && <InlineEmpty text="Belum ada dokumen yang diterbitkan untuk mahasiswa ini." />}</div></div></section>
    </>}

    <ModalForm open={Boolean(revokeDocument)} onClose={() => setRevokeDocument(null)} title="Cabut dokumen resmi" description={revokeDocument ? `${revokeDocument.document_number} akan dinyatakan tidak valid pada halaman verifikasi publik.` : ''} icon={<Ban size={20} />} footer={<div className="flex justify-end gap-2"><button type="button" onClick={() => setRevokeDocument(null)} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-500 hover:bg-white">Batal</button><button form="revoke-document-form" type="submit" disabled={revokeForm.processing} className="rounded-xl bg-gradient-to-r from-rose-500 to-pink-600 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-rose-600/15 disabled:opacity-50">{revokeForm.processing ? 'Memproses...' : 'Cabut dokumen'}</button></div>}><form id="revoke-document-form" onSubmit={revoke}><label className="block"><span className="text-xs font-semibold text-slate-700">Alasan pencabutan</span><textarea autoFocus className="input mt-2 min-h-32 resize-y" value={revokeForm.data.reason} onChange={(e) => revokeForm.setData('reason', e.target.value)} placeholder="Jelaskan koreksi data atau alasan administratif secara lengkap..." />{revokeForm.errors.reason && <p className="mt-1.5 text-xs text-rose-600">{revokeForm.errors.reason}</p>}</label><div className="mt-4 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">Riwayat dokumen tetap tersimpan untuk audit. Penerbitan ulang akan menghasilkan dokumen aktif dengan nomor dan snapshot baru.</div></form></ModalForm>
  </DashboardLayout>;
}

function Panel({ icon, eyebrow, title, description, children }: { icon: ReactNode; eyebrow: string; title: string; description: string; children: ReactNode }) { return <section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200 sm:p-6"><div className="mb-5 flex gap-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600">{icon}</div><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-emerald-600">{eyebrow}</p><h2 className="mt-1 font-semibold text-slate-950">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-400">{description}</p></div></div>{children}</section>; }
function IssueButton({ disabled, onClick, icon, label }: { disabled: boolean; onClick: () => void; icon: ReactNode; label: string }) { return <button type="button" disabled={disabled} onClick={onClick} className="inline-flex min-w-max items-center gap-2 rounded-xl bg-slate-950 px-3 py-2 text-[11px] font-semibold text-white shadow-sm hover:bg-emerald-700 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-400 disabled:shadow-none">{icon}{label}</button>; }
function DarkMetric({ value, label }: { value: string; label: string }) { return <div className="min-w-28 rounded-xl bg-white/10 p-3 text-center ring-1 ring-white/10"><p className="text-xl font-bold">{value}</p><p className="mt-1 text-[9px] font-semibold uppercase tracking-wider text-emerald-200/60">{label}</p></div>; }
function Status({ revoked }: { revoked: boolean }) { return <span className={`rounded-lg px-2 py-1 text-[9px] font-bold uppercase ${revoked ? 'bg-rose-50 text-rose-700' : 'bg-emerald-50 text-emerald-700'}`}>{revoked ? 'Dicabut' : 'Valid'}</span>; }
function Empty({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <section className="mt-7 rounded-2xl bg-white p-12 text-center ring-1 ring-slate-200"><div className="mx-auto flex size-14 items-center justify-center rounded-2xl bg-slate-50 text-slate-300">{icon}</div><h2 className="mt-4 font-semibold text-slate-800">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-400">{text}</p></section>; }
function InlineEmpty({ text }: { text: string }) { return <div className="rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-400"><FileText size={21} className="mx-auto mb-2 text-slate-300" />{text}</div>; }
function money(value: number) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value); }
function dateTime(value: string) { return new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
