import { Head, router, useForm } from '@inertiajs/react';
import { AlertTriangle, ArrowLeftRight, BadgeCheck, Banknote, CalendarClock, CheckCircle2, CircleDollarSign, Clock3, CreditCard, FileClock, Landmark, Plus, ReceiptText, Search, ShieldCheck, Sparkles, UsersRound, WalletCards } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { ModalForm } from '@/components/ModalForm';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Term = { id: number; code: string; name: string; semester: string };
type Student = { id: number; nim: string; user: { name: string; email?: string }; program?: { code: string; name?: string } };
type Bill = { id: number; student_id: number; invoice_number: string; description: string; category: string; amount: string; paid_amount: string; due_on: string; status: 'unpaid' | 'partial' | 'paid' | 'waived'; notes: string | null; waiver_reason: string | null; student: Student; academic_term: Term };
type Allocation = { id: number; amount: string; billing_item: { id: number; invoice_number: string; description: string } };
type Payment = { id: number; student_id: number; provider: string; external_reference: string; amount: string; paid_at: string; status: string; notes: string | null; student: Student; allocations: Allocation[] };
type VirtualAccount = { id: number; provider: string; va_number: string; status: string; expires_at: string | null };
type Event = { id: number; provider: string; event_id: string; event_type: string | null; status: string; processed_at: string | null; error_message: string | null; created_at: string };
type Page<T> = { data: T[]; current_page: number; last_page: number; total: number };
type Props = { mode: 'student' | 'manager'; filters: { q: string; status: string; academic_term_id: string; student_id: number | null; tab: Tab }; bills: Page<Bill>; payments: Payment[]; summary: { billed: number; paid: number; outstanding: number; overdue: number }; virtualAccount: VirtualAccount | null; termOptions: Term[]; studentOptions: Student[]; viewerStudentId: number | null; reconciliation: { events: Event[]; summary: Record<string, number> } | null; abilities: { manage: boolean } };
type Tab = 'bills' | 'payments' | 'reconciliation';

export default function FinancePage(props: Props) {
  const [filters, setFilters] = useState(props.filters);
  const [billOpen, setBillOpen] = useState(false);
  const [paymentBill, setPaymentBill] = useState<Bill | null>(null);
  const [waiveBill, setWaiveBill] = useState<Bill | null>(null);
  const billForm = useForm({ student_id: props.filters.student_id ? String(props.filters.student_id) : '', academic_term_id: '', description: '', category: 'UKT', amount: '', due_on: '', notes: '' });
  const paymentForm = useForm({ amount: '', paid_at: localDateTime(new Date().toISOString()), notes: '' });
  const waiveForm = useForm({ reason: '' });
  const tab = props.mode === 'student' && filters.tab === 'reconciliation' ? 'bills' : filters.tab;

  function applyFilter(event: FormEvent) { event.preventDefault(); router.get('/finance', filters, { preserveState: false, replace: true }); }
  function switchTab(next: Tab) { setFilters({ ...filters, tab: next }); router.get('/finance', { ...props.filters, tab: next }, { preserveState: false, replace: true }); }
  function openBill() { billForm.clearErrors(); billForm.setData({ student_id: props.filters.student_id ? String(props.filters.student_id) : '', academic_term_id: '', description: '', category: 'UKT', amount: '', due_on: '', notes: '' }); setBillOpen(true); }
  function saveBill(event: FormEvent) { event.preventDefault(); billForm.post('/finance/bills', { preserveScroll: true, onSuccess: () => setBillOpen(false) }); }
  function openPayment(item: Bill) { paymentForm.clearErrors(); paymentForm.setData({ amount: String(Number(item.amount) - Number(item.paid_amount)), paid_at: localDateTime(new Date().toISOString()), notes: '' }); setPaymentBill(item); }
  function savePayment(event: FormEvent) { event.preventDefault(); if (!paymentBill) return; paymentForm.post(`/finance/bills/${paymentBill.id}/payments`, { preserveScroll: true, onSuccess: () => setPaymentBill(null) }); }
  function saveWaiver(event: FormEvent) { event.preventDefault(); if (!waiveBill) return; waiveForm.post(`/finance/bills/${waiveBill.id}/waive`, { preserveScroll: true, onSuccess: () => setWaiveBill(null) }); }
  const vaStudentId = props.mode === 'student' ? props.viewerStudentId : props.filters.student_id;

  return <DashboardLayout><Head title="Keuangan Mahasiswa" />
    <header className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><div className="flex items-center gap-2 text-sm font-semibold text-amber-600"><Sparkles size={16} /> Financial operations center</div><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">Tagihan & pembayaran.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Ledger mahasiswa yang transparan, alokasi pembayaran otomatis, dan rekonsiliasi bank dalam satu pusat kendali.</p></div><div className="flex gap-2">{vaStudentId && (!props.virtualAccount || props.virtualAccount.status !== 'active') && <button onClick={() => router.post(`/finance/students/${vaStudentId}/virtual-account`, {}, { preserveScroll: true })} className="action-secondary"><Landmark size={15} /> Aktifkan VA</button>}{props.abilities.manage && <button onClick={openBill} className="action-primary"><Plus size={15} /> Terbitkan tagihan</button>}</div></header>

    <section className="relative mt-7 overflow-hidden rounded-3xl bg-gradient-to-br from-[#161006] via-[#3b2608] to-[#74500e] p-6 text-white shadow-xl shadow-amber-950/15 sm:p-8"><div className="absolute -right-20 -top-24 size-72 rounded-full bg-amber-300/15 blur-3xl" /><div className="relative grid gap-7 lg:grid-cols-[1fr_auto]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-300">Ringkasan ledger</p><h2 className="mt-3 text-2xl font-semibold">{props.mode === 'student' ? 'Posisi keuangan Anda' : 'Posisi keuangan terfilter'}</h2><p className="mt-2 text-sm text-amber-100/65">Nilai pembayaran hanya menghitung transaksi yang sudah dialokasikan.</p>{props.virtualAccount && <div className="mt-5 inline-flex items-center gap-3 rounded-xl bg-white/10 px-4 py-3 ring-1 ring-white/10"><CreditCard size={17} className="text-amber-300" /><div><p className="text-[9px] font-bold uppercase tracking-wider text-amber-200/60">Virtual Account {props.virtualAccount.provider.toUpperCase()}</p><p className="mt-1 font-mono text-lg font-bold tracking-wider">{formatVa(props.virtualAccount.va_number)}</p></div><span className="ml-3 rounded-lg bg-emerald-300/15 px-2 py-1 text-[9px] font-bold uppercase text-emerald-200">{props.virtualAccount.status}</span></div>}</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-2"><DarkMetric label="Total tagihan" value={moneyCompact(props.summary.billed)} /><DarkMetric label="Terbayar" value={moneyCompact(props.summary.paid)} /><DarkMetric label="Sisa" value={moneyCompact(props.summary.outstanding)} /><DarkMetric label="Terlambat" value={String(props.summary.overdue)} /></div></div></section>

    <div className="mt-5 flex gap-1 overflow-x-auto rounded-2xl bg-white p-1.5 ring-1 ring-slate-200"><TabButton active={tab === 'bills'} onClick={() => switchTab('bills')} icon={<ReceiptText size={15} />} label="Tagihan" /><TabButton active={tab === 'payments'} onClick={() => switchTab('payments')} icon={<Banknote size={15} />} label="Riwayat pembayaran" />{props.mode === 'manager' && <TabButton active={tab === 'reconciliation'} onClick={() => switchTab('reconciliation')} icon={<ArrowLeftRight size={15} />} label="Rekonsiliasi bank" />}</div>

    {tab !== 'reconciliation' && <form onSubmit={applyFilter} className="mt-5 grid gap-3 rounded-2xl bg-white p-4 ring-1 ring-slate-200 md:grid-cols-[1fr_190px_210px_auto]">{props.mode === 'manager' ? <select className="input" value={filters.student_id ?? ''} onChange={(e) => setFilters({ ...filters, student_id: e.target.value ? Number(e.target.value) : null })}><option value="">Semua mahasiswa</option>{props.studentOptions.map((student) => <option key={student.id} value={student.id}>{student.nim} · {student.user.name}</option>)}</select> : <div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input className="input pl-9" value={filters.q} onChange={(e) => setFilters({ ...filters, q: e.target.value })} placeholder="Cari invoice..." /></div>}<select className="input" value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">Semua status</option><option value="unpaid">Belum lunas</option><option value="partial">Sebagian</option><option value="paid">Lunas</option><option value="waived">Dibebaskan</option></select><select className="input" value={filters.academic_term_id} onChange={(e) => setFilters({ ...filters, academic_term_id: e.target.value })}><option value="">Semua semester</option>{props.termOptions.map((term) => <option key={term.id} value={term.id}>{term.code} · {term.semester}</option>)}</select><button className="rounded-xl bg-slate-950 px-5 text-xs font-semibold text-white">Terapkan</button></form>}

    {tab === 'bills' && <Bills bills={props.bills.data} mode={props.mode} manage={props.abilities.manage} openPayment={openPayment} openWaive={(bill) => { waiveForm.reset(); setWaiveBill(bill); }} />}
    {tab === 'payments' && <Payments payments={props.payments} mode={props.mode} />}
    {tab === 'reconciliation' && props.reconciliation && <Reconciliation data={props.reconciliation} />}

    <ModalForm open={billOpen} onClose={() => setBillOpen(false)} title="Terbitkan tagihan mahasiswa" description="Tagihan baru langsung masuk ke ledger dan menjadi target alokasi pembayaran VA." icon={<ReceiptText size={20} />} size="lg" footer={<FormFooter processing={billForm.processing} onCancel={() => setBillOpen(false)} form="bill-form" label="Terbitkan tagihan" />}><form id="bill-form" onSubmit={saveBill} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Mahasiswa" error={billForm.errors.student_id}><select autoFocus className="input" value={billForm.data.student_id} onChange={(e) => billForm.setData('student_id', e.target.value)}><option value="">Pilih mahasiswa</option>{props.studentOptions.map((student) => <option key={student.id} value={student.id}>{student.nim} · {student.user.name}</option>)}</select></Field><Field label="Semester" error={billForm.errors.academic_term_id}><select className="input" value={billForm.data.academic_term_id} onChange={(e) => billForm.setData('academic_term_id', e.target.value)}><option value="">Pilih semester</option>{props.termOptions.map((term) => <option key={term.id} value={term.id}>{term.code} · {term.semester}</option>)}</select></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Jenis tagihan" error={billForm.errors.description}><input className="input" value={billForm.data.description} onChange={(e) => billForm.setData('description', e.target.value)} placeholder="UKT Semester Ganjil" /></Field><Field label="Kategori" error={billForm.errors.category}><select className="input" value={billForm.data.category} onChange={(e) => billForm.setData('category', e.target.value)}><option>UKT</option><option>Perkuliahan</option><option>Praktikum</option><option>Wisuda</option><option>Lainnya</option></select></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Nominal" error={billForm.errors.amount}><input type="number" min="1" className="input" value={billForm.data.amount} onChange={(e) => billForm.setData('amount', e.target.value)} /></Field><Field label="Jatuh tempo" error={billForm.errors.due_on}><input type="date" className="input" value={billForm.data.due_on} onChange={(e) => billForm.setData('due_on', e.target.value)} /></Field></div><Field label="Catatan internal" error={billForm.errors.notes}><textarea className="input min-h-24 resize-y" value={billForm.data.notes} onChange={(e) => billForm.setData('notes', e.target.value)} /></Field></form></ModalForm>
    <ModalForm open={Boolean(paymentBill)} onClose={() => setPaymentBill(null)} title="Catat pembayaran manual" description={paymentBill ? `${paymentBill.invoice_number} · sisa ${money(Number(paymentBill.amount) - Number(paymentBill.paid_amount))}` : ''} icon={<Banknote size={20} />} footer={<FormFooter processing={paymentForm.processing} onCancel={() => setPaymentBill(null)} form="payment-form" label="Catat & alokasikan" />}><form id="payment-form" onSubmit={savePayment} className="space-y-4"><Field label="Nominal pembayaran" error={paymentForm.errors.amount}><input autoFocus type="number" min="1" className="input" value={paymentForm.data.amount} onChange={(e) => paymentForm.setData('amount', e.target.value)} /></Field><Field label="Waktu pembayaran" error={paymentForm.errors.paid_at}><input type="datetime-local" className="input" value={paymentForm.data.paid_at} onChange={(e) => paymentForm.setData('paid_at', e.target.value)} /></Field><Field label="Referensi/catatan" error={paymentForm.errors.notes}><textarea className="input min-h-24 resize-y" value={paymentForm.data.notes} onChange={(e) => paymentForm.setData('notes', e.target.value)} placeholder="Nomor bukti kas atau referensi bank..." /></Field></form></ModalForm>
    <ModalForm open={Boolean(waiveBill)} onClose={() => setWaiveBill(null)} title="Bebaskan tagihan" description="Tindakan ini tercatat pada audit trail dan tidak menghapus histori tagihan." icon={<ShieldCheck size={20} />} footer={<FormFooter processing={waiveForm.processing} onCancel={() => setWaiveBill(null)} form="waive-form" label="Setujui pembebasan" />}><form id="waive-form" onSubmit={saveWaiver}><Field label="Alasan pembebasan" error={waiveForm.errors.reason}><textarea autoFocus className="input min-h-36 resize-y" value={waiveForm.data.reason} onChange={(e) => waiveForm.setData('reason', e.target.value)} placeholder="Jelaskan dasar kebijakan atau persetujuannya..." /></Field></form></ModalForm>
  </DashboardLayout>;
}

function Bills({ bills, mode, manage, openPayment, openWaive }: { bills: Bill[]; mode: Props['mode']; manage: boolean; openPayment: (bill: Bill) => void; openWaive: (bill: Bill) => void }) {
  return <section className="mt-6">
    <div className="mb-4"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-amber-600">Accounts receivable</p><h2 className="mt-1 text-xl font-semibold text-slate-950">Daftar tagihan</h2></div>
    <div className="space-y-3">{bills.map((bill) => {
      const outstanding = Number(bill.amount) - Number(bill.paid_amount);
      const overdue = outstanding > 0 && new Date(bill.due_on) < new Date();
      return <article key={bill.id} className="rounded-2xl bg-white p-5 ring-1 ring-slate-200">
        <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center">
          <div className="flex min-w-0 gap-4">
            <div className={`flex size-11 shrink-0 items-center justify-center rounded-xl ${bill.status === 'paid' ? 'bg-emerald-50 text-emerald-600' : overdue ? 'bg-rose-50 text-rose-600' : bill.status === 'waived' ? 'bg-sky-50 text-sky-600' : 'bg-amber-50 text-amber-600'}`}>{bill.status === 'paid' ? <CheckCircle2 size={20} /> : overdue ? <AlertTriangle size={20} /> : <ReceiptText size={20} />}</div>
            <div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-950">{bill.description}</h3><Status status={bill.status} /></div><p className="mt-1 text-xs text-slate-400">{bill.invoice_number} · {bill.academic_term.code} · jatuh tempo {formatDate(bill.due_on)}</p>{mode === 'manager' && <p className="mt-2 text-xs font-semibold text-slate-600">{bill.student.nim} · {bill.student.user.name}</p>}</div>
          </div>
          <div className="flex flex-wrap items-center gap-5 lg:justify-end">
            <div className="text-right"><p className="text-lg font-bold text-slate-950">{money(Number(bill.amount))}</p><p className="text-[10px] text-slate-400">Terbayar {money(Number(bill.paid_amount))}</p></div>
            {outstanding > 0 && !['waived', 'paid'].includes(bill.status) && <div className="min-w-28 text-right"><p className="text-xs font-semibold text-rose-600">Sisa {money(outstanding)}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-amber-400 to-emerald-500" style={{ width: `${Math.min(100, Number(bill.paid_amount) / Number(bill.amount) * 100)}%` }} /></div></div>}
            {manage && outstanding > 0 && !['waived', 'paid'].includes(bill.status) && <div className="flex gap-2"><button onClick={() => openPayment(bill)} className="action-secondary"><Banknote size={13} /> Bayar</button><button onClick={() => openWaive(bill)} className="action-secondary"><ShieldCheck size={13} /> Bebaskan</button></div>}
          </div>
        </div>
        {bill.waiver_reason && <p className="mt-4 rounded-xl bg-sky-50 p-3 text-xs leading-5 text-sky-800">Pembebasan: {bill.waiver_reason}</p>}
      </article>;
    })}{!bills.length && <Empty text="Tidak ada tagihan untuk filter ini." />}</div>
  </section>;
}

function Payments({ payments, mode }: { payments: Payment[]; mode: Props['mode'] }) { return <section className="mt-6"><div className="mb-4"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-emerald-600">Cash receipts</p><h2 className="mt-1 text-xl font-semibold text-slate-950">Riwayat pembayaran</h2></div><div className="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div className="divide-y divide-slate-100">{payments.map((payment) => <div key={payment.id} className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="flex gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><CircleDollarSign size={19} /></div><div><p className="text-sm font-semibold text-slate-800">{money(Number(payment.amount))} <span className="ml-2 text-[9px] font-bold uppercase text-emerald-600">{payment.status}</span></p><p className="mt-1 text-[10px] text-slate-400">{formatDateTime(payment.paid_at)} · {payment.provider.toUpperCase()} · {payment.external_reference}</p>{mode === 'manager' && <p className="mt-1 text-xs text-slate-500">{payment.student?.nim} · {payment.student?.user.name}</p>}</div></div><div className="text-right">{payment.allocations.map((allocation) => <p key={allocation.id} className="text-[10px] text-slate-500">{allocation.billing_item.invoice_number} · {money(Number(allocation.amount))}</p>)}</div></div>)}{!payments.length && <Empty text="Belum ada pembayaran yang tercatat." />}</div></div></section>; }

function Reconciliation({ data }: { data: NonNullable<Props['reconciliation']> }) { return <section className="mt-6"><div className="grid gap-4 sm:grid-cols-4"><MiniMetric label="Diterima" value={data.summary.received ?? 0} tone="amber" /><MiniMetric label="Diproses" value={data.summary.processed ?? 0} tone="green" /><MiniMetric label="Gagal" value={data.summary.failed ?? 0} tone="rose" /><MiniMetric label="Total event" value={data.events.length} tone="blue" /></div><div className="mt-6 overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold text-slate-950">Event callback bank terbaru</h2><p className="mt-1 text-xs text-slate-400">Event idempotent; duplikasi tidak membuat pembayaran ganda.</p></div><div className="divide-y divide-slate-100">{data.events.map((event) => <div key={event.id} className="flex flex-col justify-between gap-3 p-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><div className={`flex size-9 items-center justify-center rounded-xl ${event.status === 'processed' ? 'bg-emerald-50 text-emerald-600' : event.status === 'failed' ? 'bg-rose-50 text-rose-600' : 'bg-amber-50 text-amber-600'}`}>{event.status === 'processed' ? <BadgeCheck size={17} /> : event.status === 'failed' ? <AlertTriangle size={17} /> : <FileClock size={17} />}</div><div><p className="font-mono text-xs font-semibold text-slate-700">{event.event_id}</p><p className="mt-1 text-[10px] text-slate-400">{event.provider.toUpperCase()} · {event.event_type ?? 'va.payment.received'} · {formatDateTime(event.created_at)}</p></div></div><div className="sm:text-right"><StatusText status={event.status} />{event.error_message && <p className="mt-1 max-w-md text-xs text-rose-600">{event.error_message}</p>}</div></div>)}{!data.events.length && <Empty text="Belum ada callback bank yang diterima." />}</div></div></section>; }

function DarkMetric({ label, value }: { label: string; value: string }) { return <div className="min-w-28 rounded-xl bg-white/10 px-3 py-3 text-center ring-1 ring-white/10"><p className="text-lg font-bold">{value}</p><p className="mt-1 text-[9px] font-semibold uppercase tracking-wider text-amber-200/60">{label}</p></div>; }
function MiniMetric({ label, value, tone }: { label: string; value: number; tone: 'amber' | 'green' | 'rose' | 'blue' }) { const colors = { amber: 'text-amber-600 bg-amber-50', green: 'text-emerald-600 bg-emerald-50', rose: 'text-rose-600 bg-rose-50', blue: 'text-sky-600 bg-sky-50' }; return <div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><span className={`inline-flex rounded-lg px-2 py-1 text-lg font-bold ${colors[tone]}`}>{value}</span><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p></div>; }
function TabButton({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: ReactNode; label: string }) { return <button onClick={onClick} className={`flex min-w-max flex-1 items-center justify-center gap-2 rounded-xl px-4 py-3 text-xs font-semibold ${active ? 'bg-slate-950 text-white shadow-lg shadow-slate-900/10' : 'text-slate-500 hover:bg-slate-50 hover:text-slate-900'}`}>{icon}{label}</button>; }
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="block"><span className="text-xs font-semibold text-slate-700">{label}</span><div className="mt-2">{children}</div>{error && <p className="mt-1.5 text-xs text-rose-600">{error}</p>}</label>; }
function FormFooter({ processing, onCancel, form, label }: { processing: boolean; onCancel: () => void; form: string; label: string }) { return <div className="flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-500 hover:bg-white">Batal</button><button type="submit" form={form} disabled={processing} className="rounded-xl bg-gradient-to-r from-amber-500 to-orange-600 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-amber-600/15 disabled:opacity-50">{processing ? 'Memproses...' : label}</button></div>; }
function Status({ status }: { status: Bill['status'] }) { const map = { unpaid: ['Belum lunas', 'bg-rose-50 text-rose-700'], partial: ['Sebagian', 'bg-amber-50 text-amber-700'], paid: ['Lunas', 'bg-emerald-50 text-emerald-700'], waived: ['Dibebaskan', 'bg-sky-50 text-sky-700'] }; return <span className={`rounded-lg px-2 py-1 text-[9px] font-bold uppercase ${map[status][1]}`}>{map[status][0]}</span>; }
function StatusText({ status }: { status: string }) { return <span className={`rounded-lg px-2 py-1 text-[9px] font-bold uppercase ${status === 'processed' ? 'bg-emerald-50 text-emerald-700' : status === 'failed' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'}`}>{status}</span>; }
function Empty({ text }: { text: string }) { return <div className="p-10 text-center"><WalletCards size={25} className="mx-auto text-slate-300" /><p className="mt-2 text-sm text-slate-400">{text}</p></div>; }
function money(value: number) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value); }
function moneyCompact(value: number) { return new Intl.NumberFormat('id-ID', { notation: 'compact', maximumFractionDigits: 1 }).format(value); }
function formatDate(value: string) { return new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(value)); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
function localDateTime(value: string) { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
function formatVa(value: string) { return value.replace(/(.{4})/g, '$1 ').trim(); }
