import { Head, router, useForm } from '@inertiajs/react';
import { Award, BadgeCheck, CalendarDays, Download, FileClock, FileUp, GraduationCap, Pencil, Plus, Send, UserRoundCheck } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { ModalForm } from '@/components/ModalForm';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Term = { id: number; code: string; name: string };
type Period = { id: number; academic_term_id: number; code: string; name: string; registration_starts_at: string; registration_ends_at: string; judicium_on: string; ceremony_on: string | null; quota: number | null; is_active: boolean; applications_count: number; approved_count: number; academic_term: Term };
type Requirement = { id: number; document_type: 'identity' | 'photo' | 'clearance'; version: number; original_name: string; is_current: boolean; created_at: string };
type OfficialDocument = { id: number; document_type: 'diploma' | 'final_transcript' | 'skpi'; document_number: string; verification_code: string; issued_at: string };
type Eligibility = { eligible: boolean; passed_credits: number; minimum_credits: number; gpa: number; minimum_gpa: number; outstanding: number; project_complete: boolean; failures: string[] };
type Alumni = { id: number; alumni_number: string; personal_email: string | null; phone: string | null; address: string | null; employment_status: string | null; company_name: string | null; position: string | null; industry: string | null; employment_started_on: string | null; directory_consent: boolean; tracer_responses: Array<{ id: number; survey_year: number; employment_status: string; submitted_at: string }> };
type Application = { id: number; application_number: string; status: string; eligibility_snapshot: Eligibility | null; review_notes: string | null; submitted_at: string | null; reviewed_at: string | null; graduated_at: string | null; period: Pick<Period, 'id' | 'code' | 'name' | 'judicium_on' | 'ceremony_on'>; student: { id: number; nim: string; user: { name: string; email: string }; program: { code: string; name: string; degree: string } }; documents?: Requirement[]; graduate_documents?: OfficialDocument[]; alumni_profile?: Alumni | null; reviewer?: { name: string } | null };
type Paginated<T> = { data: T[]; links: Array<{ url: string | null; label: string; active: boolean }>; total: number };
type Props = { mode: 'student' | 'manager'; applications: Paginated<Application>; selectedApplication: Application | null; periods: Period[]; termOptions: Term[]; alumniProfile: Alumni | null; filters: { status: string; period_id: string; q: string; selected: number | null }; abilities: { managePeriods: boolean; start: boolean; update: boolean; review: boolean; graduate: boolean; updateAlumni: boolean } };
type PeriodForm = { academic_term_id: string; code: string; name: string; registration_starts_at: string; registration_ends_at: string; judicium_on: string; ceremony_on: string; quota: string; is_active: boolean };

const blankPeriod: PeriodForm = { academic_term_id: '', code: '', name: '', registration_starts_at: '', registration_ends_at: '', judicium_on: '', ceremony_on: '', quota: '', is_active: true };
const employmentOptions = [['employed', 'Bekerja'], ['entrepreneur', 'Wirausaha'], ['studying', 'Studi lanjut'], ['seeking', 'Mencari kerja'], ['other', 'Lainnya']];

export default function GraduationIndex(props: Props) {
  const selected = props.selectedApplication;
  const [periodOpen, setPeriodOpen] = useState(false); const [editingPeriod, setEditingPeriod] = useState<Period | null>(null);
  const [documentOpen, setDocumentOpen] = useState(false); const [decisionOpen, setDecisionOpen] = useState(false); const [alumniOpen, setAlumniOpen] = useState(false); const [tracerOpen, setTracerOpen] = useState(false);
  const periodForm = useForm<PeriodForm>(blankPeriod);
  const documentForm = useForm<{ document_type: Requirement['document_type']; document: File | null }>({ document_type: 'identity', document: null });
  const decisionForm = useForm<{ decision: 'approve' | 'reject'; notes: string }>({ decision: 'approve', notes: '' });
  const profile = props.alumniProfile ?? selected?.alumni_profile ?? null;
  const alumniForm = useForm({ personal_email: '', phone: '', address: '', employment_status: '', company_name: '', position: '', industry: '', employment_started_on: '', directory_consent: false });
  const tracerForm = useForm({ survey_year: String(new Date().getFullYear()), employment_status: 'employed', waiting_months: '', company_name: '', position: '', salary_range: '', study_relevance: '', feedback: '' });

  function filter(key: string, value: string) { router.get('/graduation', { ...props.filters, selected: undefined, [key]: value }, { preserveState: true, replace: true }); }
  function openPeriod(period?: Period) {
    setEditingPeriod(period ?? null);
    periodForm.setData(period ? { academic_term_id: String(period.academic_term_id), code: period.code, name: period.name, registration_starts_at: localDateTime(period.registration_starts_at), registration_ends_at: localDateTime(period.registration_ends_at), judicium_on: period.judicium_on.slice(0, 10), ceremony_on: period.ceremony_on?.slice(0, 10) ?? '', quota: period.quota ? String(period.quota) : '', is_active: period.is_active } : blankPeriod);
    periodForm.clearErrors(); setPeriodOpen(true);
  }
  function savePeriod(e: FormEvent) { e.preventDefault(); const done = () => setPeriodOpen(false); editingPeriod ? periodForm.patch(`/graduation/periods/${editingPeriod.id}`, { onSuccess: done }) : periodForm.post('/graduation/periods', { onSuccess: done }); }
  function saveDocument(e: FormEvent) { e.preventDefault(); if (!selected) return; documentForm.post(`/graduation/applications/${selected.id}/documents`, { forceFormData: true, onSuccess: () => { setDocumentOpen(false); documentForm.reset(); } }); }
  function saveDecision(e: FormEvent) { e.preventDefault(); if (!selected) return; decisionForm.post(`/graduation/applications/${selected.id}/decision`, { onSuccess: () => setDecisionOpen(false) }); }
  function openAlumni() { if (!profile) return; alumniForm.setData({ personal_email: profile.personal_email ?? '', phone: profile.phone ?? '', address: profile.address ?? '', employment_status: profile.employment_status ?? '', company_name: profile.company_name ?? '', position: profile.position ?? '', industry: profile.industry ?? '', employment_started_on: profile.employment_started_on?.slice(0, 10) ?? '', directory_consent: profile.directory_consent }); alumniForm.clearErrors(); setAlumniOpen(true); }
  function saveAlumni(e: FormEvent) { e.preventDefault(); if (!profile) return; alumniForm.patch(`/graduation/alumni/${profile.id}`, { onSuccess: () => setAlumniOpen(false) }); }
  function saveTracer(e: FormEvent) { e.preventDefault(); if (!profile) return; tracerForm.post(`/graduation/alumni/${profile.id}/tracer`, { onSuccess: () => { setTracerOpen(false); tracerForm.reset(); } }); }

  return <DashboardLayout><Head title="Yudisium & Alumni" />
    <header className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-emerald-600">Graduation lifecycle</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em] text-slate-950">Yudisium, kelulusan & alumni.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Pemeriksaan kelayakan, penerbitan ijazah/transkrip/SKPI yang dapat diverifikasi, serta pemutakhiran tracer study.</p></div>{props.abilities.managePeriods && <button onClick={() => openPeriod()} className="action-primary"><Plus size={15} /> Periode baru</button>}</header>

    {props.mode === 'student' && props.abilities.start && <section className="mt-7 rounded-2xl bg-gradient-to-br from-emerald-900 to-teal-700 p-5 text-white"><div className="flex items-center gap-3"><CalendarDays size={20} /><div><h2 className="font-bold">Periode pendaftaran aktif</h2><p className="text-xs text-emerald-100">Pilih periode yang sedang dibuka untuk menyiapkan pengajuan.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2">{props.periods.filter((period) => period.is_active).map((period) => <div key={period.id} className="flex items-center justify-between gap-3 rounded-xl bg-white/10 p-4"><div><strong className="text-sm">{period.name}</strong><p className="mt-1 text-[11px] text-emerald-100">Yudisium {date(period.judicium_on)}</p></div><button onClick={() => router.post(`/graduation/periods/${period.id}/start`)} className="rounded-lg bg-white px-3 py-2 text-xs font-bold text-emerald-800">Mulai</button></div>)}{!props.periods.some((period) => period.is_active) && <p className="text-xs text-emerald-100">Belum ada periode aktif.</p>}</div></section>}

    {props.abilities.managePeriods && <section className="mt-7 overflow-x-auto rounded-2xl bg-white ring-1 ring-slate-200"><div className="border-b border-slate-100 p-5"><h2 className="font-bold text-slate-900">Periode yudisium & wisuda</h2></div><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-400"><tr><th className="p-4">Periode</th><th className="p-4">Pendaftaran</th><th className="p-4">Yudisium</th><th className="p-4">Kuota</th><th className="p-4">Status</th><th className="p-4"></th></tr></thead><tbody>{props.periods.map((period) => <tr key={period.id} className="border-t border-slate-100"><td className="p-4"><strong>{period.name}</strong><br /><span className="text-slate-400">{period.code} · {period.academic_term.code}</span></td><td className="p-4">{date(period.registration_starts_at)} – {date(period.registration_ends_at)}</td><td className="p-4">{date(period.judicium_on)}</td><td className="p-4">{period.approved_count}/{period.quota ?? '∞'}</td><td className="p-4"><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${period.is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{period.is_active ? 'AKTIF' : 'NONAKTIF'}</span></td><td className="p-4"><button onClick={() => openPeriod(period)} className="text-slate-500"><Pencil size={14} /></button></td></tr>)}</tbody></table></section>}

    <section className="mt-7 grid gap-3 rounded-2xl bg-white p-4 ring-1 ring-slate-200/80 sm:grid-cols-3"><input defaultValue={props.filters.q} onKeyDown={(e) => { if (e.key === 'Enter') filter('q', e.currentTarget.value); }} placeholder="Cari nomor, nama, atau NIM..." className="input" /><select value={props.filters.period_id} onChange={(e) => filter('period_id', e.target.value)} className="input"><option value="">Semua periode</option>{props.periods.map((period) => <option key={period.id} value={period.id}>{period.code}</option>)}</select><select value={props.filters.status} onChange={(e) => filter('status', e.target.value)} className="input"><option value="">Semua status</option>{['draft', 'submitted', 'approved', 'rejected', 'graduated'].map((status) => <option key={status} value={status}>{statusLabel(status)}</option>)}</select></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[360px_1fr]"><section className="space-y-3">{props.applications.data.map((item) => <button key={item.id} onClick={() => router.get('/graduation', { ...props.filters, selected: item.id }, { preserveState: true })} className={`w-full rounded-2xl bg-white p-4 text-left ring-1 ${selected?.id === item.id ? 'ring-emerald-300 shadow-lg shadow-emerald-900/5' : 'ring-slate-200'}`}><div className="flex justify-between gap-3"><Status value={item.status} /><span className="text-[10px] text-slate-400">{item.period.code}</span></div><h2 className="mt-3 font-bold text-slate-900">{item.student.user.name}</h2><p className="mt-1 text-xs text-slate-500">{item.student.nim} · {item.student.program.code}</p><p className="mt-2 font-mono text-[10px] text-slate-400">{item.application_number}</p></button>)}{!props.applications.data.length && <Empty text="Belum ada pengajuan." />}</section><section>{selected ? <ApplicationDetail application={selected} abilities={props.abilities} openDocument={() => setDocumentOpen(true)} submit={() => confirm('Kirim pengajuan untuk diverifikasi?') && router.post(`/graduation/applications/${selected.id}/submit`)} review={() => { decisionForm.setData({ decision: 'approve', notes: '' }); setDecisionOpen(true); }} graduate={() => confirm('Tetapkan mahasiswa lulus dan terbitkan tiga dokumen resmi?') && router.post(`/graduation/applications/${selected.id}/graduate`)} /> : <Empty text="Pilih pengajuan untuk melihat detail." />}</section></div>

    {profile && <section className="mt-7 rounded-2xl bg-white p-6 ring-1 ring-slate-200"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase text-emerald-600">Portal alumni</p><h2 className="mt-2 text-xl font-bold text-slate-950">{profile.alumni_number}</h2><p className="mt-1 text-xs text-slate-500">{employmentLabel(profile.employment_status)} · {profile.company_name || 'Instansi belum diisi'}</p></div>{props.abilities.updateAlumni && <div className="flex gap-2"><button onClick={openAlumni} className="action-secondary"><Pencil size={14} /> Profil</button><button onClick={() => setTracerOpen(true)} className="action-primary"><BadgeCheck size={14} /> Tracer study</button></div>}</div><div className="mt-5 grid gap-3 sm:grid-cols-3">{profile.tracer_responses.map((row) => <div key={row.id} className="rounded-xl bg-slate-50 p-4"><strong className="text-sm">{row.survey_year}</strong><p className="mt-1 text-xs text-slate-500">{employmentLabel(row.employment_status)}</p></div>)}{!profile.tracer_responses.length && <Empty text="Belum ada respons tracer study." />}</div></section>}

    <ModalForm open={periodOpen} onClose={() => setPeriodOpen(false)} title={editingPeriod ? 'Perbarui periode' : 'Periode yudisium baru'} description="Atur rentang pendaftaran, tanggal penetapan, dan kuota peserta." icon={<CalendarDays size={19} />} size="lg" footer={<FormFooter form="period-form" processing={periodForm.processing} onCancel={() => setPeriodOpen(false)} label="Simpan periode" />}><form id="period-form" onSubmit={savePeriod} className="grid gap-4 sm:grid-cols-2"><Field label="Periode akademik" error={periodForm.errors.academic_term_id}><select required value={periodForm.data.academic_term_id} onChange={(e) => periodForm.setData('academic_term_id', e.target.value)} className="input"><option value="">Pilih periode</option>{props.termOptions.map((term) => <option key={term.id} value={term.id}>{term.code} · {term.name}</option>)}</select></Field><Field label="Kode" error={periodForm.errors.code}><input required value={periodForm.data.code} onChange={(e) => periodForm.setData('code', e.target.value)} className="input" /></Field><Field label="Nama" error={periodForm.errors.name}><input required value={periodForm.data.name} onChange={(e) => periodForm.setData('name', e.target.value)} className="input" /></Field><Field label="Kuota" error={periodForm.errors.quota}><input type="number" min="1" value={periodForm.data.quota} onChange={(e) => periodForm.setData('quota', e.target.value)} className="input" /></Field><Field label="Pendaftaran dibuka" error={periodForm.errors.registration_starts_at}><input required type="datetime-local" value={periodForm.data.registration_starts_at} onChange={(e) => periodForm.setData('registration_starts_at', e.target.value)} className="input" /></Field><Field label="Pendaftaran ditutup" error={periodForm.errors.registration_ends_at}><input required type="datetime-local" value={periodForm.data.registration_ends_at} onChange={(e) => periodForm.setData('registration_ends_at', e.target.value)} className="input" /></Field><Field label="Tanggal yudisium" error={periodForm.errors.judicium_on}><input required type="date" value={periodForm.data.judicium_on} onChange={(e) => periodForm.setData('judicium_on', e.target.value)} className="input" /></Field><Field label="Tanggal wisuda" error={periodForm.errors.ceremony_on}><input type="date" value={periodForm.data.ceremony_on} onChange={(e) => periodForm.setData('ceremony_on', e.target.value)} className="input" /></Field><label className="sm:col-span-2 flex items-center gap-2 text-xs font-semibold text-slate-600"><input type="checkbox" checked={periodForm.data.is_active} onChange={(e) => periodForm.setData('is_active', e.target.checked)} /> Periode aktif dan dapat dipilih mahasiswa</label></form></ModalForm>
    <ModalForm open={documentOpen} onClose={() => setDocumentOpen(false)} title="Unggah dokumen persyaratan" description="Versi sebelumnya tetap tersimpan dan hanya versi terbaru yang digunakan." icon={<FileUp size={19} />} footer={<FormFooter form="document-form" processing={documentForm.processing} onCancel={() => setDocumentOpen(false)} label="Unggah" />}><form id="document-form" onSubmit={saveDocument} className="space-y-4"><Field label="Jenis dokumen" error={documentForm.errors.document_type}><select value={documentForm.data.document_type} onChange={(e) => documentForm.setData('document_type', e.target.value as Requirement['document_type'])} className="input"><option value="identity">Identitas</option><option value="photo">Pas foto</option><option value="clearance">Surat bebas administrasi</option></select></Field><Field label="File PDF/JPG/PNG (maks. 5 MB)" error={documentForm.errors.document}><input required type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(e) => documentForm.setData('document', e.target.files?.[0] ?? null)} className="input" /></Field></form></ModalForm>
    <ModalForm open={decisionOpen} onClose={() => setDecisionOpen(false)} title="Keputusan verifikasi" description="Kelayakan dihitung ulang saat keputusan disimpan." icon={<UserRoundCheck size={19} />} footer={<FormFooter form="decision-form" processing={decisionForm.processing} onCancel={() => setDecisionOpen(false)} label="Simpan keputusan" />}><form id="decision-form" onSubmit={saveDecision} className="space-y-4"><Field label="Keputusan" error={decisionForm.errors.decision}><select value={decisionForm.data.decision} onChange={(e) => decisionForm.setData('decision', e.target.value as 'approve' | 'reject')} className="input"><option value="approve">Setujui</option><option value="reject">Tolak</option></select></Field><Field label="Catatan" error={decisionForm.errors.notes}><textarea value={decisionForm.data.notes} onChange={(e) => decisionForm.setData('notes', e.target.value)} className="input min-h-28" /></Field></form></ModalForm>
    <ModalForm open={alumniOpen} onClose={() => setAlumniOpen(false)} title="Perbarui profil alumni" description="Kontak dan informasi karier membantu kampus menjaga jejaring alumni." icon={<GraduationCap size={19} />} size="lg" footer={<FormFooter form="alumni-form" processing={alumniForm.processing} onCancel={() => setAlumniOpen(false)} label="Simpan profil" />}><form id="alumni-form" onSubmit={saveAlumni} className="grid gap-4 sm:grid-cols-2"><Field label="Email pribadi" error={alumniForm.errors.personal_email}><input type="email" value={alumniForm.data.personal_email} onChange={(e) => alumniForm.setData('personal_email', e.target.value)} className="input" /></Field><Field label="Telepon" error={alumniForm.errors.phone}><input value={alumniForm.data.phone} onChange={(e) => alumniForm.setData('phone', e.target.value)} className="input" /></Field><Field label="Status" error={alumniForm.errors.employment_status}><select value={alumniForm.data.employment_status} onChange={(e) => alumniForm.setData('employment_status', e.target.value)} className="input"><option value="">Belum diisi</option>{employmentOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Instansi / perusahaan" error={alumniForm.errors.company_name}><input value={alumniForm.data.company_name} onChange={(e) => alumniForm.setData('company_name', e.target.value)} className="input" /></Field><Field label="Posisi" error={alumniForm.errors.position}><input value={alumniForm.data.position} onChange={(e) => alumniForm.setData('position', e.target.value)} className="input" /></Field><Field label="Industri" error={alumniForm.errors.industry}><input value={alumniForm.data.industry} onChange={(e) => alumniForm.setData('industry', e.target.value)} className="input" /></Field><Field label="Mulai bekerja" error={alumniForm.errors.employment_started_on}><input type="date" value={alumniForm.data.employment_started_on} onChange={(e) => alumniForm.setData('employment_started_on', e.target.value)} className="input" /></Field><Field label="Alamat" error={alumniForm.errors.address}><textarea value={alumniForm.data.address} onChange={(e) => alumniForm.setData('address', e.target.value)} className="input min-h-20" /></Field><label className="sm:col-span-2 flex items-center gap-2 text-xs font-semibold text-slate-600"><input type="checkbox" checked={alumniForm.data.directory_consent} onChange={(e) => alumniForm.setData('directory_consent', e.target.checked)} /> Izinkan profil ditampilkan pada direktori alumni</label></form></ModalForm>
    <ModalForm open={tracerOpen} onClose={() => setTracerOpen(false)} title="Tracer study" description="Respons pada tahun yang sama akan diperbarui secara idempoten." icon={<BadgeCheck size={19} />} size="lg" footer={<FormFooter form="tracer-form" processing={tracerForm.processing} onCancel={() => setTracerOpen(false)} label="Kirim tracer" />}><form id="tracer-form" onSubmit={saveTracer} className="grid gap-4 sm:grid-cols-2"><Field label="Tahun survei" error={tracerForm.errors.survey_year}><input required type="number" value={tracerForm.data.survey_year} onChange={(e) => tracerForm.setData('survey_year', e.target.value)} className="input" /></Field><Field label="Status" error={tracerForm.errors.employment_status}><select value={tracerForm.data.employment_status} onChange={(e) => tracerForm.setData('employment_status', e.target.value)} className="input">{employmentOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Masa tunggu (bulan)" error={tracerForm.errors.waiting_months}><input type="number" min="0" value={tracerForm.data.waiting_months} onChange={(e) => tracerForm.setData('waiting_months', e.target.value)} className="input" /></Field><Field label="Relevansi studi (1–5)" error={tracerForm.errors.study_relevance}><input type="number" min="1" max="5" value={tracerForm.data.study_relevance} onChange={(e) => tracerForm.setData('study_relevance', e.target.value)} className="input" /></Field><Field label="Instansi / perusahaan" error={tracerForm.errors.company_name}><input value={tracerForm.data.company_name} onChange={(e) => tracerForm.setData('company_name', e.target.value)} className="input" /></Field><Field label="Posisi" error={tracerForm.errors.position}><input value={tracerForm.data.position} onChange={(e) => tracerForm.setData('position', e.target.value)} className="input" /></Field><Field label="Rentang penghasilan" error={tracerForm.errors.salary_range}><input value={tracerForm.data.salary_range} onChange={(e) => tracerForm.setData('salary_range', e.target.value)} className="input" /></Field><Field label="Masukan" error={tracerForm.errors.feedback}><textarea value={tracerForm.data.feedback} onChange={(e) => tracerForm.setData('feedback', e.target.value)} className="input min-h-20" /></Field></form></ModalForm>
  </DashboardLayout>;
}

function ApplicationDetail({ application, abilities, openDocument, submit, review, graduate }: { application: Application; abilities: Props['abilities']; openDocument: () => void; submit: () => void; review: () => void; graduate: () => void }) {
  const documents = (application.documents ?? []).filter((item) => item.is_current);
  return <div className="space-y-5"><section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><div className="flex flex-wrap items-start justify-between gap-4"><div><Status value={application.status} /><h2 className="mt-3 text-xl font-bold text-slate-950">{application.student.user.name}</h2><p className="mt-1 text-sm text-slate-500">{application.student.nim} · {application.student.program.name}</p><p className="mt-2 font-mono text-xs text-slate-400">{application.application_number}</p></div><div className="flex flex-wrap gap-2">{abilities.update && <><button onClick={openDocument} className="action-secondary"><FileUp size={14} /> Dokumen</button><button onClick={submit} className="action-primary"><Send size={14} /> Kirim</button></>}{abilities.review && <button onClick={review} className="action-primary"><UserRoundCheck size={14} /> Verifikasi</button>}{abilities.graduate && <button onClick={graduate} className="action-primary"><Award size={14} /> Tetapkan lulus</button>}</div></div><div className="mt-5 grid gap-3 rounded-xl bg-slate-50 p-4 text-xs text-slate-600 sm:grid-cols-2"><p><strong>Periode</strong><br />{application.period.name}</p><p><strong>Tanggal yudisium</strong><br />{date(application.period.judicium_on)}</p><p><strong>Email</strong><br />{application.student.user.email}</p><p><strong>Program</strong><br />{application.student.program.degree} · {application.student.program.code}</p></div>{application.review_notes && <div className="mt-4 rounded-xl bg-amber-50 p-4 text-xs text-amber-800"><strong>Catatan pemeriksa:</strong> {application.review_notes}</div>}</section>
    {application.eligibility_snapshot && <section className={`rounded-2xl p-5 ring-1 ${application.eligibility_snapshot.eligible ? 'bg-emerald-50 ring-emerald-200' : 'bg-rose-50 ring-rose-200'}`}><h3 className="font-bold">{application.eligibility_snapshot.eligible ? 'Syarat kelulusan terpenuhi' : 'Syarat belum terpenuhi'}</h3><div className="mt-3 grid gap-3 text-xs sm:grid-cols-4"><p><strong>SKS</strong><br />{application.eligibility_snapshot.passed_credits}/{application.eligibility_snapshot.minimum_credits}</p><p><strong>IPK</strong><br />{application.eligibility_snapshot.gpa}/{application.eligibility_snapshot.minimum_gpa}</p><p><strong>Tunggakan</strong><br />Rp {Number(application.eligibility_snapshot.outstanding).toLocaleString('id-ID')}</p><p><strong>Tugas akhir</strong><br />{application.eligibility_snapshot.project_complete ? 'Selesai' : 'Belum selesai'}</p></div>{application.eligibility_snapshot.failures.length > 0 && <p className="mt-3 text-xs">{application.eligibility_snapshot.failures.join(' · ')}</p>}</section>}
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h3 className="font-bold text-slate-900">Dokumen persyaratan</h3><div className="mt-4 space-y-2">{documents.map((document) => <a key={document.id} href={`/graduation/applications/${application.id}/documents/${document.id}`} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><span><strong className="block text-slate-800">{requirementLabel(document.document_type)} · v{document.version}</strong>{document.original_name}</span><Download size={15} /></a>)}{!documents.length && <Empty text="Belum ada dokumen persyaratan." />}</div></div><div className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><h3 className="font-bold text-slate-900">Dokumen kelulusan resmi</h3><div className="mt-4 space-y-2">{(application.graduate_documents ?? []).map((document) => <a key={document.id} href={`/graduation/applications/${application.id}/documents-final/${document.id}.pdf`} className="flex items-center justify-between rounded-xl bg-emerald-50 p-3 text-xs text-emerald-800"><span><strong className="block">{officialLabel(document.document_type)}</strong>{document.document_number}</span><Download size={15} /></a>)}{!application.graduate_documents?.length && <Empty text="Diterbitkan setelah penetapan lulus." />}</div></div></section>
  </div>;
}

function Status({ value }: { value: string }) { const tone = ({ draft: 'bg-slate-100 text-slate-600', submitted: 'bg-sky-50 text-sky-700', approved: 'bg-teal-50 text-teal-700', rejected: 'bg-rose-50 text-rose-700', graduated: 'bg-emerald-100 text-emerald-800' } as Record<string, string>)[value] ?? 'bg-slate-100 text-slate-600'; return <span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase ${tone}`}>{statusLabel(value)}</span>; }
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-semibold text-slate-600">{label}</span>{children}{error && <span className="mt-1 block text-xs text-rose-600">{error}</span>}</label>; }
function FormFooter({ processing, onCancel, form, label }: { processing: boolean; onCancel: () => void; form: string; label: string }) { return <div className="flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-500">Batal</button><button type="submit" form={form} disabled={processing} className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{processing ? 'Memproses...' : label}</button></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-slate-200 p-6 text-center text-xs text-slate-400"><FileClock size={19} className="mx-auto mb-2" />{text}</div>; }
function statusLabel(value: string) { return ({ draft: 'Draf', submitted: 'Menunggu verifikasi', approved: 'Disetujui', rejected: 'Ditolak', graduated: 'Lulus' } as Record<string, string>)[value] ?? value; }
function requirementLabel(value: string) { return ({ identity: 'Identitas', photo: 'Pas foto', clearance: 'Bebas administrasi' } as Record<string, string>)[value] ?? value; }
function officialLabel(value: string) { return ({ diploma: 'Ijazah', final_transcript: 'Transkrip final', skpi: 'SKPI' } as Record<string, string>)[value] ?? value; }
function employmentLabel(value: string | null) { return value ? Object.fromEntries(employmentOptions)[value] ?? value : 'Status karier belum diisi'; }
function date(value: string) { return new Date(value).toLocaleDateString('id-ID'); }
function localDateTime(value: string) { const date = new Date(value); const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
