import { Head, router } from '@inertiajs/react';
import { Banknote, BarChart3, BadgeCheck, CircleDollarSign, GraduationCap, Landmark, Sparkles, Star, TrendingUp, UserCheck, UsersRound, WalletCards } from 'lucide-react';
import type { ReactNode } from 'react';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Term = { id: number; code: string; name: string; semester: string; is_active?: boolean };
type Props = { filters: { academic_term_id: string }; termOptions: Term[]; academic: { active_students: number; registrations: number; approved_registrations: number; enrollments: number; average_score: number }; finance: { billed: number; paid: number; outstanding: number; collection_rate: number; payment_trend: { month: string; amount: number }[] }; pmb: { applications: number; submitted: number; verified: number; converted: number }; quality: { responses: number; average: number; classes: number } };

export default function ReportPage(props: Props) {
  const maxTrend = Math.max(1, ...props.finance.payment_trend.map((item) => item.amount));
  return <DashboardLayout><Head title="Laporan Eksekutif" />
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 text-sm font-semibold text-emerald-600"><Sparkles size={16} /> Executive intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">Laporan institusi.</h1><p className="mt-2 text-sm text-slate-500">Ringkasan akademik, keuangan, penerimaan, dan kualitas pembelajaran.</p></div><select value={props.filters.academic_term_id} onChange={(e) => router.get('/reports', { academic_term_id: e.target.value }, { replace: true })} className="input bg-white sm:w-64"><option value="">Semua semester</option>{props.termOptions.map((term) => <option key={term.id} value={term.id}>{term.code} · {term.semester}</option>)}</select></header>
    <section className="relative mt-7 overflow-hidden rounded-3xl bg-gradient-to-br from-[#071b16] via-[#0a3b31] to-[#0c6a57] p-6 text-white shadow-xl shadow-emerald-950/15 sm:p-8"><div className="absolute -right-16 -top-24 size-72 rounded-full bg-emerald-300/15 blur-3xl" /><div className="relative grid gap-6 md:grid-cols-2 xl:grid-cols-4"><HeroMetric icon={<UsersRound size={18} />} label="Mahasiswa aktif" value={number(props.academic.active_students)} /><HeroMetric icon={<UserCheck size={18} />} label="Registrasi disetujui" value={number(props.academic.approved_registrations)} /><HeroMetric icon={<CircleDollarSign size={18} />} label="Collection rate" value={`${props.finance.collection_rate}%`} /><HeroMetric icon={<Star size={18} />} label="Skor EDOM" value={props.quality.average.toFixed(2)} /></div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel eyebrow="Academic performance" title="Operasional akademik" icon={<GraduationCap size={20} className="text-sky-600" />}><div className="grid grid-cols-2 gap-3"><DataCard label="Registrasi KRS" value={number(props.academic.registrations)} /><DataCard label="Peserta kelas" value={number(props.academic.enrollments)} /><DataCard label="Rerata nilai" value={props.academic.average_score.toFixed(2)} /><DataCard label="Approval rate" value={`${props.academic.registrations ? Math.round(props.academic.approved_registrations / props.academic.registrations * 100) : 0}%`} /></div></Panel><Panel eyebrow="Financial health" title="Kesehatan keuangan" icon={<WalletCards size={20} className="text-amber-600" />}><div className="space-y-3"><MoneyRow label="Total tagihan" value={props.finance.billed} color="slate" /><MoneyRow label="Realisasi pembayaran" value={props.finance.paid} color="green" /><MoneyRow label="Piutang berjalan" value={props.finance.outstanding} color="rose" /><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-amber-400 to-emerald-500" style={{ width: `${Math.min(100, props.finance.collection_rate)}%` }} /></div></div></Panel></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Panel eyebrow="Cashflow trend" title="Penerimaan 6 bulan terakhir" icon={<TrendingUp size={20} className="text-emerald-600" />}><div className="flex h-52 items-end gap-3">{props.finance.payment_trend.map((item) => <div key={item.month} className="flex h-full flex-1 flex-col justify-end"><p className="mb-2 truncate text-center text-[9px] font-semibold text-slate-500">{moneyCompact(item.amount)}</p><div className="mx-auto w-full max-w-12 rounded-t-xl bg-gradient-to-t from-emerald-700 to-teal-300" style={{ height: `${Math.max(5, item.amount / maxTrend * 80)}%` }} /><p className="mt-2 text-center text-[9px] text-slate-400">{month(item.month)}</p></div>)}{!props.finance.payment_trend.length && <div className="m-auto text-sm text-slate-400">Belum ada penerimaan pada periode grafik.</div>}</div></Panel><Panel eyebrow="Admission funnel" title="Konversi PMB" icon={<BadgeCheck size={20} className="text-violet-600" />}><Funnel label="Total aplikasi" value={props.pmb.applications} max={props.pmb.applications} tone="bg-violet-300" /><Funnel label="Dikirim" value={props.pmb.submitted} max={props.pmb.applications} tone="bg-violet-400" /><Funnel label="Terverifikasi" value={props.pmb.verified} max={props.pmb.applications} tone="bg-violet-500" /><Funnel label="Menjadi mahasiswa" value={props.pmb.converted} max={props.pmb.applications} tone="bg-violet-700" /></Panel></div>
    <section className="mt-6 rounded-2xl bg-white p-6 ring-1 ring-slate-200"><div className="flex items-center gap-3"><div className="flex size-11 items-center justify-center rounded-xl bg-fuchsia-50 text-fuchsia-600"><BarChart3 size={20} /></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-fuchsia-600">Quality assurance</p><h2 className="font-semibold text-slate-950">Partisipasi EDOM</h2></div></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><DataCard label="Respons anonim" value={number(props.quality.responses)} /><DataCard label="Kelas terukur" value={number(props.quality.classes)} /><DataCard label="Rerata kepuasan" value={`${props.quality.average.toFixed(2)} / 5`} /></div></section>
  </DashboardLayout>;
}
function Panel({ eyebrow, title, icon, children }: { eyebrow: string; title: string; icon: ReactNode; children: ReactNode }) { return <section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200"><div className="mb-5 flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-400">{eyebrow}</p><h2 className="mt-1 font-semibold text-slate-950">{title}</h2></div>{icon}</div>{children}</section>; }
function HeroMetric({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="rounded-2xl bg-white/10 p-4 ring-1 ring-white/10"><div className="flex items-center gap-2 text-emerald-200">{icon}<span className="text-[9px] font-bold uppercase tracking-wider">{label}</span></div><p className="mt-3 text-3xl font-bold">{value}</p></div>; }
function DataCard({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xl font-bold text-slate-950">{value}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-wider text-slate-400">{label}</p></div>; }
function MoneyRow({ label, value, color }: { label: string; value: number; color: 'slate' | 'green' | 'rose' }) { const colors = { slate: 'text-slate-900', green: 'text-emerald-700', rose: 'text-rose-700' }; return <div className="flex items-center justify-between"><span className="text-xs text-slate-500">{label}</span><span className={`text-sm font-bold ${colors[color]}`}>{money(value)}</span></div>; }
function Funnel({ label, value, max, tone }: { label: string; value: number; max: number; tone: string }) { return <div className="mb-4"><div className="flex items-center justify-between text-xs"><span className="text-slate-500">{label}</span><span className="font-bold text-slate-800">{number(value)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${tone}`} style={{ width: `${max ? Math.max(2, value / max * 100) : 0}%` }} /></div></div>; }
function number(value: number) { return new Intl.NumberFormat('id-ID').format(value); }
function money(value: number) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value); }
function moneyCompact(value: number) { return new Intl.NumberFormat('id-ID', { notation: 'compact', maximumFractionDigits: 1 }).format(value); }
function month(value: string) { return new Intl.DateTimeFormat('id-ID', { month: 'short' }).format(new Date(`${value}-01`)); }
