<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\AcademicScheduleController;
use App\Http\Controllers\AcademicRegistrationController;
use App\Http\Controllers\AcademicGradeController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CurriculumController;
use App\Http\Controllers\FacilityController;
use App\Http\Controllers\FacilityTransferController;
use App\Http\Controllers\MenuBuilderController;
use App\Http\Controllers\MasterDataController;
use App\Http\Controllers\MasterDataTransferController;
use App\Http\Controllers\LecturerTransferController;
use App\Http\Controllers\LmsController;
use App\Http\Controllers\EdomController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\AuditController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\OfficialDocumentController;
use App\Http\Controllers\StudentServiceController;
use App\Http\Controllers\AcademicGuidanceController;
use App\Http\Controllers\AcademicCalendarController;
use App\Http\Controllers\AcademicProjectController;
use App\Http\Controllers\GraduationController;
use App\Http\Controllers\Pmb\PmbRegistrationController;
use App\Http\Controllers\Pmb\PmbApplicationController;
use App\Http\Controllers\Pmb\PmbFeeController;
use App\Http\Controllers\Pmb\PmbSelectionController;
use App\Http\Controllers\Pmb\PmbVerificationController;
use App\Http\Controllers\Pmb\SimulatePmbPaymentController;
use App\Http\Controllers\RoleSwitchController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentTransferController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserTransferController;

Route::get('/', fn () => \Inertia\Inertia::render('Landing'))->name('home');
Route::get('/verify/documents/{verificationCode}', [OfficialDocumentController::class, 'verify'])->middleware('throttle:60,1')->name('documents.verify');
Route::get('/verify/services/{verificationCode}', [StudentServiceController::class, 'verifyDocument'])->middleware('throttle:60,1')->name('services.documents.verify');
Route::get('/verify/exams/{verificationCode}', [AcademicCalendarController::class, 'verify'])->middleware('throttle:60,1')->name('exams.verify');
Route::get('/verify/projects/defenses/{verificationCode}', [AcademicProjectController::class, 'verifyDefense'])->middleware('throttle:60,1')->name('academic.projects.defenses.verify');
Route::get('/repository/projects/{verificationCode}', [AcademicProjectController::class, 'repository'])->middleware('throttle:60,1')->name('academic.projects.repository.public');
Route::get('/repository/projects/{verificationCode}/download', [AcademicProjectController::class, 'repositoryDownload'])->middleware('throttle:30,1')->name('academic.projects.repository.download');
Route::get('/verify/graduation/{verificationCode}', [GraduationController::class, 'verifyDocument'])->middleware('throttle:60,1')->name('graduation.documents.verify');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->middleware('throttle:5,1');
    Route::get('/forgot-password', [ForgotPasswordController::class, 'create'])->name('password.request');
    Route::post('/forgot-password', [ForgotPasswordController::class, 'store'])->middleware('throttle:3,1')->name('password.email');
    Route::get('/reset-password/{token}', [ResetPasswordController::class, 'create'])->name('password.reset');
    Route::post('/reset-password', [ResetPasswordController::class, 'store'])->middleware('throttle:5,1')->name('password.update');
    Route::get('/pmb/register', [PmbRegistrationController::class, 'create'])->name('pmb.register');
    Route::post('/pmb/register', [PmbRegistrationController::class, 'store'])->middleware('throttle:5,1');
});
Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->middleware('auth')->name('logout');
Route::middleware('auth')->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/academic/registration', [AcademicRegistrationController::class, 'index'])->name('academic.registration');
    Route::post('/academic/registration/periods', [AcademicRegistrationController::class, 'storePeriod'])->name('academic.registration.periods.store');
    Route::patch('/academic/registration/periods/{period}', [AcademicRegistrationController::class, 'updatePeriod'])->name('academic.registration.periods.update');
    Route::post('/academic/registration/start', [AcademicRegistrationController::class, 'start'])->name('academic.registration.start');
    Route::post('/academic/registration/{registration}/courses', [AcademicRegistrationController::class, 'addCourse'])->name('academic.registration.courses.store');
    Route::delete('/academic/registration/{registration}/courses/{enrollment}', [AcademicRegistrationController::class, 'removeCourse'])->name('academic.registration.courses.destroy');
    Route::post('/academic/registration/{registration}/submit', [AcademicRegistrationController::class, 'submit'])->name('academic.registration.submit');
    Route::post('/academic/registration/{registration}/dispensation', [AcademicRegistrationController::class, 'requestDispensation'])->name('academic.registration.dispensation.store');
    Route::post('/academic/registration/{registration}/dispensation/decision', [AcademicRegistrationController::class, 'decideDispensation'])->name('academic.registration.dispensation.decision');
    Route::post('/academic/registration/{registration}/review', [AcademicRegistrationController::class, 'review'])->name('academic.registration.review');
    Route::post('/academic/registration/{registration}/changes', [AcademicRegistrationController::class, 'requestChange'])->name('academic.registration.changes.store');
    Route::delete('/academic/registration/{registration}/changes/{change}', [AcademicRegistrationController::class, 'cancelChange'])->name('academic.registration.changes.cancel');
    Route::post('/academic/registration/{registration}/changes/{change}/review', [AcademicRegistrationController::class, 'reviewChange'])->name('academic.registration.changes.review');
    Route::get('/academic/grades', [AcademicGradeController::class, 'index'])->name('academic.grades');
    Route::post('/academic/grades/classes/{classGroup}/components', [AcademicGradeController::class, 'storeComponent'])->name('academic.grades.components.store');
    Route::patch('/academic/grades/classes/{classGroup}/components/{component}', [AcademicGradeController::class, 'updateComponent'])->name('academic.grades.components.update');
    Route::delete('/academic/grades/classes/{classGroup}/components/{component}', [AcademicGradeController::class, 'destroyComponent'])->name('academic.grades.components.destroy');
    Route::put('/academic/grades/classes/{classGroup}/enrollments/{enrollment}/scores', [AcademicGradeController::class, 'storeScores'])->name('academic.grades.scores.update');
    Route::post('/academic/grades/classes/{classGroup}/publish', [AcademicGradeController::class, 'publish'])->name('academic.grades.publish');
    Route::post('/academic/grades/classes/{classGroup}/finalize', [AcademicGradeController::class, 'finalize'])->name('academic.grades.finalize');
    Route::post('/academic/grades/classes/{classGroup}/reopen', [AcademicGradeController::class, 'reopen'])->name('academic.grades.reopen');
    Route::get('/academic/lms', [LmsController::class, 'index'])->name('academic.lms');
    Route::post('/academic/lms/classes/{classGroup}/materials', [LmsController::class, 'storeMaterial'])->name('academic.lms.materials.store');
    Route::post('/academic/lms/classes/{classGroup}/materials/{material}', [LmsController::class, 'updateMaterial'])->name('academic.lms.materials.update');
    Route::delete('/academic/lms/classes/{classGroup}/materials/{material}', [LmsController::class, 'destroyMaterial'])->name('academic.lms.materials.destroy');
    Route::get('/academic/lms/classes/{classGroup}/materials/{material}/attachment', [LmsController::class, 'materialAttachment'])->name('academic.lms.materials.attachment');
    Route::post('/academic/lms/classes/{classGroup}/assignments', [LmsController::class, 'storeAssignment'])->name('academic.lms.assignments.store');
    Route::post('/academic/lms/classes/{classGroup}/assignments/{assignment}', [LmsController::class, 'updateAssignment'])->name('academic.lms.assignments.update');
    Route::delete('/academic/lms/classes/{classGroup}/assignments/{assignment}', [LmsController::class, 'destroyAssignment'])->name('academic.lms.assignments.destroy');
    Route::get('/academic/lms/classes/{classGroup}/assignments/{assignment}/attachment', [LmsController::class, 'assignmentAttachment'])->name('academic.lms.assignments.attachment');
    Route::post('/academic/lms/classes/{classGroup}/assignments/{assignment}/submit', [LmsController::class, 'submit'])->name('academic.lms.assignments.submit');
    Route::post('/academic/lms/classes/{classGroup}/assignments/{assignment}/submissions/{submission}/grade', [LmsController::class, 'grade'])->name('academic.lms.submissions.grade');
    Route::get('/academic/lms/classes/{classGroup}/assignments/{assignment}/submissions/{submission}/attachment', [LmsController::class, 'submissionAttachment'])->name('academic.lms.submissions.attachment');
    Route::post('/academic/lms/classes/{classGroup}/topics', [LmsController::class, 'storeTopic'])->name('academic.lms.topics.store');
    Route::patch('/academic/lms/classes/{classGroup}/topics/{topic}', [LmsController::class, 'moderateTopic'])->name('academic.lms.topics.moderate');
    Route::delete('/academic/lms/classes/{classGroup}/topics/{topic}', [LmsController::class, 'destroyTopic'])->name('academic.lms.topics.destroy');
    Route::post('/academic/lms/classes/{classGroup}/topics/{topic}/comments', [LmsController::class, 'storeComment'])->name('academic.lms.comments.store');
    Route::delete('/academic/lms/classes/{classGroup}/topics/{topic}/comments/{comment}', [LmsController::class, 'destroyComment'])->name('academic.lms.comments.destroy');
    Route::get('/academic/edom', [EdomController::class, 'index'])->name('academic.edom');
    Route::post('/academic/edom/questionnaires', [EdomController::class, 'storeQuestionnaire'])->name('academic.edom.questionnaires.store');
    Route::patch('/academic/edom/questionnaires/{questionnaire}', [EdomController::class, 'updateQuestionnaire'])->name('academic.edom.questionnaires.update');
    Route::delete('/academic/edom/questionnaires/{questionnaire}', [EdomController::class, 'destroyQuestionnaire'])->name('academic.edom.questionnaires.destroy');
    Route::post('/academic/edom/questionnaires/{questionnaire}/questions', [EdomController::class, 'storeQuestion'])->name('academic.edom.questions.store');
    Route::patch('/academic/edom/questionnaires/{questionnaire}/questions/{question}', [EdomController::class, 'updateQuestion'])->name('academic.edom.questions.update');
    Route::delete('/academic/edom/questionnaires/{questionnaire}/questions/{question}', [EdomController::class, 'destroyQuestion'])->name('academic.edom.questions.destroy');
    Route::post('/academic/edom/questionnaires/{questionnaire}/classes/{classGroup}', [EdomController::class, 'submit'])->name('academic.edom.submit');
    Route::get('/finance', [FinanceController::class, 'index'])->name('finance.index');
    Route::post('/finance/bills', [FinanceController::class, 'storeBill'])->name('finance.bills.store');
    Route::post('/finance/bills/{bill}/payments', [FinanceController::class, 'recordPayment'])->name('finance.payments.store');
    Route::post('/finance/bills/{bill}/waive', [FinanceController::class, 'waive'])->name('finance.bills.waive');
    Route::post('/finance/students/{student}/virtual-account', [FinanceController::class, 'issueVa'])->name('finance.virtual-account.issue');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::post('/notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.read-all');
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'read'])->name('notifications.read');
    Route::get('/admin/audit-logs', [AuditController::class, 'index'])->name('admin.audit-logs');
    Route::get('/admin/audit-logs/export', [AuditController::class, 'export'])->name('admin.audit-logs.export');
    Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('/academic/attendance', [AttendanceController::class, 'index'])->name('academic.attendance');
    Route::post('/academic/attendance/classes/{classGroup}/sessions', [AttendanceController::class, 'store'])->name('academic.attendance.sessions.store');
    Route::patch('/academic/attendance/classes/{classGroup}/sessions/{session}', [AttendanceController::class, 'update'])->name('academic.attendance.sessions.update');
    Route::delete('/academic/attendance/classes/{classGroup}/sessions/{session}', [AttendanceController::class, 'destroy'])->name('academic.attendance.sessions.destroy');
    Route::post('/academic/attendance/classes/{classGroup}/sessions/{session}/transition', [AttendanceController::class, 'transition'])->name('academic.attendance.sessions.transition');
    Route::put('/academic/attendance/classes/{classGroup}/sessions/{session}/records', [AttendanceController::class, 'saveRecords'])->name('academic.attendance.records.update');
    Route::post('/academic/attendance/classes/{classGroup}/sessions/{session}/check-in', [AttendanceController::class, 'checkIn'])->name('academic.attendance.check-in');
    Route::get('/documents', [OfficialDocumentController::class, 'index'])->name('documents.index');
    Route::post('/documents/issue/{type}/{sourceId}', [OfficialDocumentController::class, 'issue'])->name('documents.issue');
    Route::get('/documents/{document}', [OfficialDocumentController::class, 'show'])->name('documents.show');
    Route::get('/documents/{document}/pdf', [OfficialDocumentController::class, 'pdf'])->name('documents.pdf');
    Route::patch('/documents/{document}/revoke', [OfficialDocumentController::class, 'revoke'])->name('documents.revoke');
    Route::get('/services', [StudentServiceController::class, 'index'])->name('services.index');
    Route::post('/services', [StudentServiceController::class, 'store'])->name('services.store');
    Route::post('/services/{serviceRequest}/resubmit', [StudentServiceController::class, 'resubmit'])->name('services.resubmit');
    Route::post('/services/{serviceRequest}/cancel', [StudentServiceController::class, 'cancel'])->name('services.cancel');
    Route::post('/services/{serviceRequest}/decision', [StudentServiceController::class, 'decide'])->name('services.decision');
    Route::get('/services/{serviceRequest}/attachment', [StudentServiceController::class, 'attachment'])->name('services.attachment');
    Route::get('/academic/guidance', [AcademicGuidanceController::class, 'index'])->name('academic.guidance');
    Route::get('/academic/calendar', [AcademicCalendarController::class, 'index'])->name('academic.calendar');
    Route::post('/academic/calendar/events', [AcademicCalendarController::class, 'storeEvent'])->name('academic.calendar.events.store');
    Route::patch('/academic/calendar/events/{event}', [AcademicCalendarController::class, 'updateEvent'])->name('academic.calendar.events.update');
    Route::delete('/academic/calendar/events/{event}', [AcademicCalendarController::class, 'destroyEvent'])->name('academic.calendar.events.destroy');
    Route::post('/academic/calendar/exams', [AcademicCalendarController::class, 'storeExam'])->name('academic.calendar.exams.store');
    Route::patch('/academic/calendar/exams/{exam}', [AcademicCalendarController::class, 'updateExam'])->name('academic.calendar.exams.update');
    Route::delete('/academic/calendar/exams/{exam}', [AcademicCalendarController::class, 'destroyExam'])->name('academic.calendar.exams.destroy');
    Route::get('/academic/calendar/exams/{exam}/card', [AcademicCalendarController::class, 'card'])->name('academic.exams.card');
    Route::put('/academic/calendar/exams/{exam}/invigilators', [AcademicCalendarController::class, 'syncInvigilators'])->name('academic.exams.invigilators.update');
    Route::post('/academic/calendar/exams/{exam}/participants/prepare', [AcademicCalendarController::class, 'prepareRoster'])->name('academic.exams.participants.prepare');
    Route::put('/academic/calendar/exams/{exam}/attendance', [AcademicCalendarController::class, 'recordAttendance'])->name('academic.exams.attendance.update');
    Route::put('/academic/calendar/exams/{exam}/report', [AcademicCalendarController::class, 'saveReport'])->name('academic.exams.report.update');
    Route::get('/academic/calendar/exams/{exam}/attendance.pdf', [AcademicCalendarController::class, 'attendancePdf'])->name('academic.exams.attendance.pdf');
    Route::get('/academic/calendar/exams/{exam}/report.pdf', [AcademicCalendarController::class, 'reportPdf'])->name('academic.exams.report.pdf');
    Route::get('/academic/projects', [AcademicProjectController::class, 'index'])->name('academic.projects');
    Route::post('/academic/projects', [AcademicProjectController::class, 'store'])->name('academic.projects.store');
    Route::patch('/academic/projects/{project}', [AcademicProjectController::class, 'update'])->name('academic.projects.update');
    Route::post('/academic/projects/{project}/documents', [AcademicProjectController::class, 'uploadDocument'])->name('academic.projects.documents.store');
    Route::get('/academic/projects/{project}/documents/{document}', [AcademicProjectController::class, 'downloadDocument'])->name('academic.projects.documents.show');
    Route::post('/academic/projects/{project}/submit', [AcademicProjectController::class, 'submit'])->name('academic.projects.submit');
    Route::post('/academic/projects/{project}/decision', [AcademicProjectController::class, 'decide'])->name('academic.projects.decision');
    Route::put('/academic/projects/{project}/assignments', [AcademicProjectController::class, 'syncAssignments'])->name('academic.projects.assignments.update');
    Route::post('/academic/projects/{project}/logbooks', [AcademicProjectController::class, 'storeLogbook'])->name('academic.projects.logbooks.store');
    Route::post('/academic/projects/{project}/logbooks/{logbook}/review', [AcademicProjectController::class, 'reviewLogbook'])->name('academic.projects.logbooks.review');
    Route::post('/academic/projects/{project}/guidance', [AcademicProjectController::class, 'storeGuidance'])->name('academic.projects.guidance.store');
    Route::post('/academic/projects/{project}/defenses', [AcademicProjectController::class, 'scheduleDefense'])->name('academic.projects.defenses.store');
    Route::put('/academic/projects/{project}/defenses/{defense}/rubric', [AcademicProjectController::class, 'saveRubric'])->name('academic.projects.defenses.rubric.update');
    Route::put('/academic/projects/{project}/defenses/{defense}/scores', [AcademicProjectController::class, 'saveScores'])->name('academic.projects.defenses.scores.update');
    Route::post('/academic/projects/{project}/defenses/{defense}/complete', [AcademicProjectController::class, 'completeDefense'])->name('academic.projects.defenses.complete');
    Route::get('/academic/projects/{project}/defenses/{defense}/minutes.pdf', [AcademicProjectController::class, 'minutesPdf'])->name('academic.projects.defenses.minutes');
    Route::post('/academic/projects/{project}/repository', [AcademicProjectController::class, 'publishRepository'])->name('academic.projects.repository.publish');
    Route::get('/graduation', [GraduationController::class, 'index'])->name('graduation.index');
    Route::post('/graduation/periods', [GraduationController::class, 'storePeriod'])->name('graduation.periods.store');
    Route::patch('/graduation/periods/{period}', [GraduationController::class, 'updatePeriod'])->name('graduation.periods.update');
    Route::post('/graduation/periods/{period}/start', [GraduationController::class, 'start'])->name('graduation.start');
    Route::post('/graduation/applications/{application}/documents', [GraduationController::class, 'uploadDocument'])->name('graduation.documents.store');
    Route::get('/graduation/applications/{application}/documents/{document}', [GraduationController::class, 'downloadDocument'])->name('graduation.documents.show');
    Route::post('/graduation/applications/{application}/submit', [GraduationController::class, 'submit'])->name('graduation.submit');
    Route::post('/graduation/applications/{application}/decision', [GraduationController::class, 'decide'])->name('graduation.decision');
    Route::post('/graduation/applications/{application}/graduate', [GraduationController::class, 'graduate'])->name('graduation.graduate');
    Route::get('/graduation/applications/{application}/documents-final/{document}.pdf', [GraduationController::class, 'documentPdf'])->name('graduation.documents.pdf');
    Route::patch('/graduation/alumni/{profile}', [GraduationController::class, 'updateAlumni'])->name('graduation.alumni.update');
    Route::post('/graduation/alumni/{profile}/tracer', [GraduationController::class, 'submitTracer'])->name('graduation.tracer.store');
    Route::post('/academic/guidance/appointments', [AcademicGuidanceController::class, 'storeAppointment'])->name('academic.guidance.appointments.store');
    Route::patch('/academic/guidance/appointments/{appointment}', [AcademicGuidanceController::class, 'decideAppointment'])->name('academic.guidance.appointments.update');
    Route::post('/academic/guidance/notes', [AcademicGuidanceController::class, 'storeNote'])->name('academic.guidance.notes.store');
    Route::patch('/academic/guidance/warnings/{warning}', [AcademicGuidanceController::class, 'decideWarning'])->name('academic.guidance.warnings.update');
    Route::post('/academic/guidance/availability', [AcademicGuidanceController::class, 'storeAvailability'])->name('academic.guidance.availability.store');
    Route::post('/academic/guidance/interventions', [AcademicGuidanceController::class, 'storeIntervention'])->name('academic.guidance.interventions.store');
    Route::patch('/academic/guidance/interventions/{plan}', [AcademicGuidanceController::class, 'updateIntervention'])->name('academic.guidance.interventions.update');
    Route::post('/services/types', [StudentServiceController::class, 'storeType'])->name('services.types.store');
    Route::patch('/services/types/{type}', [StudentServiceController::class, 'updateType'])->name('services.types.update');
    Route::delete('/services/types/{type}', [StudentServiceController::class, 'destroyType'])->name('services.types.destroy');
    Route::get('/services/documents/{document}', [StudentServiceController::class, 'showDocument'])->name('services.documents.show');
    Route::get('/services/documents/{document}/pdf', [StudentServiceController::class, 'pdfDocument'])->name('services.documents.pdf');
    Route::patch('/services/documents/{document}/revoke', [StudentServiceController::class, 'revokeDocument'])->name('services.documents.revoke');
    Route::get('/pmb/application', PmbApplicationController::class)->name('pmb.application');
    Route::patch('/pmb/application/profile', [PmbApplicationController::class, 'updateProfile'])->name('pmb.application.profile');
    Route::post('/pmb/application/documents', [PmbApplicationController::class, 'storeDocument'])->name('pmb.application.documents.store');
    Route::delete('/pmb/application/documents/{document}', [PmbApplicationController::class, 'destroyDocument'])->name('pmb.application.documents.destroy');
    Route::post('/pmb/application/submit', [PmbApplicationController::class, 'submit'])->name('pmb.application.submit');
    Route::get('/admin/pmb', [PmbFeeController::class, 'index'])->name('admin.pmb');
    Route::post('/admin/pmb/fees', [PmbFeeController::class, 'store'])->name('admin.pmb.fees.store');
    Route::patch('/admin/pmb/fees/{fee}', [PmbFeeController::class, 'update'])->name('admin.pmb.fees.update');
    Route::delete('/admin/pmb/fees/{fee}', [PmbFeeController::class, 'destroy'])->name('admin.pmb.fees.destroy');
    Route::patch('/admin/pmb/fees/{fee}/restore', [PmbFeeController::class, 'restore'])->name('admin.pmb.fees.restore');
    Route::get('/admin/pmb/applications/{application}', [PmbVerificationController::class, 'show'])->name('admin.pmb.applications.show');
    Route::get('/admin/pmb/applications/{application}/documents/{document}', [PmbVerificationController::class, 'download'])->name('admin.pmb.documents.download');
    Route::patch('/admin/pmb/applications/{application}/documents/{document}', [PmbVerificationController::class, 'decide'])->name('admin.pmb.documents.decide');
    Route::post('/admin/pmb/applications/{application}/return', [PmbVerificationController::class, 'returnForCorrection'])->name('admin.pmb.applications.return');
    Route::post('/admin/pmb/applications/{application}/verify', [PmbVerificationController::class, 'verify'])->name('admin.pmb.applications.verify');
    Route::post('/admin/pmb/applications/{application}/simulate-payment', SimulatePmbPaymentController::class)->name('admin.pmb.applications.simulate-payment');
    Route::get('/admin/pmb/selection', [PmbSelectionController::class, 'index'])->name('admin.pmb.selection');
    Route::post('/admin/pmb/selection', [PmbSelectionController::class, 'store'])->name('admin.pmb.selection.store');
    Route::patch('/admin/pmb/selection/{selection}', [PmbSelectionController::class, 'update'])->name('admin.pmb.selection.update');
    Route::delete('/admin/pmb/selection/{selection}', [PmbSelectionController::class, 'destroy'])->name('admin.pmb.selection.destroy');
    Route::post('/admin/pmb/selection/{selection}/components', [PmbSelectionController::class, 'storeComponent'])->name('admin.pmb.selection.components.store');
    Route::delete('/admin/pmb/selection/{selection}/components/{component}', [PmbSelectionController::class, 'destroyComponent'])->name('admin.pmb.selection.components.destroy');
    Route::post('/admin/pmb/selection/{selection}/candidates', [PmbSelectionController::class, 'assignCandidate'])->name('admin.pmb.selection.candidates.store');
    Route::delete('/admin/pmb/selection/{selection}/candidates/{result}', [PmbSelectionController::class, 'removeCandidate'])->name('admin.pmb.selection.candidates.destroy');
    Route::put('/admin/pmb/selection/{selection}/candidates/{result}/scores', [PmbSelectionController::class, 'storeScores'])->name('admin.pmb.selection.scores.update');
    Route::post('/admin/pmb/selection/{selection}/finalize', [PmbSelectionController::class, 'finalize'])->name('admin.pmb.selection.finalize');
    Route::post('/admin/pmb/selection/{selection}/candidates/{result}/convert', [PmbSelectionController::class, 'convert'])->name('admin.pmb.selection.convert');
    Route::post('/role/switch', RoleSwitchController::class)->name('role.switch');
    Route::get('/admin/menu-builder', [MenuBuilderController::class, 'index'])->name('admin.menu-builder');
    Route::post('/admin/menu-builder', [MenuBuilderController::class, 'store']);
    Route::patch('/admin/menu-builder/{menu}', [MenuBuilderController::class, 'update']);
    Route::delete('/admin/menu-builder/{menu}', [MenuBuilderController::class, 'destroy']);
    Route::get('/admin/master-data', [MasterDataController::class, 'index'])->name('admin.master-data');
    Route::post('/admin/master-data/{resource}', [MasterDataController::class, 'store'])->name('admin.master-data.store');
    Route::patch('/admin/master-data/{resource}/{id}', [MasterDataController::class, 'update'])->name('admin.master-data.update');
    Route::delete('/admin/master-data/imports/{token}', [MasterDataTransferController::class, 'cancel'])->name('admin.master-data.import.cancel');
    Route::delete('/admin/master-data/{resource}/{id}', [MasterDataController::class, 'destroy'])->name('admin.master-data.destroy');
    Route::post('/admin/master-data/{resource}/import/preview', [MasterDataTransferController::class, 'preview'])->name('admin.master-data.import.preview');
    Route::post('/admin/master-data/imports/{token}/confirm', [MasterDataTransferController::class, 'confirm'])->name('admin.master-data.import.confirm');
    Route::get('/admin/master-data/{resource}/template', [MasterDataTransferController::class, 'template'])->name('admin.master-data.template');
    Route::get('/admin/master-data/{resource}/export', [MasterDataTransferController::class, 'export'])->name('admin.master-data.export');
    Route::get('/admin/facilities', [FacilityController::class, 'index'])->name('admin.facilities');
    Route::post('/admin/facilities/{resource}', [FacilityController::class, 'store'])->name('admin.facilities.store');
    Route::patch('/admin/facilities/{resource}/{id}', [FacilityController::class, 'update'])->name('admin.facilities.update');
    Route::delete('/admin/facilities/imports/{token}', [FacilityTransferController::class, 'cancel'])->name('admin.facilities.import.cancel');
    Route::delete('/admin/facilities/{resource}/{id}', [FacilityController::class, 'destroy'])->name('admin.facilities.destroy');
    Route::patch('/admin/facilities/{resource}/{id}/restore', [FacilityController::class, 'restore'])->name('admin.facilities.restore');
    Route::post('/admin/facilities/{resource}/bulk', [FacilityController::class, 'bulk'])->name('admin.facilities.bulk');
    Route::post('/admin/facilities/{resource}/import/preview', [FacilityTransferController::class, 'preview'])->name('admin.facilities.import.preview');
    Route::post('/admin/facilities/imports/{token}/confirm', [FacilityTransferController::class, 'confirm'])->name('admin.facilities.import.confirm');
    Route::get('/admin/facilities/{resource}/template', [FacilityTransferController::class, 'template'])->name('admin.facilities.template');
    Route::get('/admin/facilities/{resource}/export', [FacilityTransferController::class, 'export'])->name('admin.facilities.export');
    Route::get('/admin/curricula', [CurriculumController::class, 'index'])->name('admin.curricula');
    Route::post('/admin/curricula', [CurriculumController::class, 'store'])->name('admin.curricula.store');
    Route::patch('/admin/curricula/{curriculum}', [CurriculumController::class, 'update'])->name('admin.curricula.update');
    Route::delete('/admin/curricula/{curriculum}', [CurriculumController::class, 'destroy'])->name('admin.curricula.destroy');
    Route::patch('/admin/curricula/{curriculum}/restore', [CurriculumController::class, 'restore'])->name('admin.curricula.restore');
    Route::post('/admin/curricula/{curriculum}/courses', [CurriculumController::class, 'storeCourse'])->name('admin.curricula.courses.store');
    Route::patch('/admin/curricula/{curriculum}/courses/{item}', [CurriculumController::class, 'updateCourse'])->name('admin.curricula.courses.update');
    Route::delete('/admin/curricula/{curriculum}/courses/{item}', [CurriculumController::class, 'destroyCourse'])->name('admin.curricula.courses.destroy');
    Route::post('/admin/course-prerequisites', [CurriculumController::class, 'storePrerequisite'])->name('admin.course-prerequisites.store');
    Route::delete('/admin/course-prerequisites/{prerequisite}', [CurriculumController::class, 'destroyPrerequisite'])->name('admin.course-prerequisites.destroy');
    Route::get('/admin/academic-schedules', [AcademicScheduleController::class, 'index'])->name('admin.academic-schedules');
    Route::post('/admin/lecturers', [AcademicScheduleController::class, 'storeLecturer'])->name('admin.lecturers.store');
    Route::patch('/admin/lecturers/{lecturer}', [AcademicScheduleController::class, 'updateLecturer'])->name('admin.lecturers.update');
    Route::delete('/admin/lecturers/{lecturer}', [AcademicScheduleController::class, 'destroyLecturer'])->name('admin.lecturers.destroy');
    Route::patch('/admin/lecturers/{lecturer}/restore', [AcademicScheduleController::class, 'restoreLecturer'])->name('admin.lecturers.restore');
    Route::post('/admin/lecturers/bulk', [AcademicScheduleController::class, 'bulkLecturers'])->name('admin.lecturers.bulk');
    Route::post('/admin/lecturers/import/preview', [LecturerTransferController::class, 'preview'])->name('admin.lecturers.import.preview');
    Route::post('/admin/lecturers/imports/{token}/confirm', [LecturerTransferController::class, 'confirm'])->name('admin.lecturers.import.confirm');
    Route::delete('/admin/lecturers/imports/{token}', [LecturerTransferController::class, 'cancel'])->name('admin.lecturers.import.cancel');
    Route::get('/admin/lecturers/template', [LecturerTransferController::class, 'template'])->name('admin.lecturers.template');
    Route::get('/admin/lecturers/export', [LecturerTransferController::class, 'export'])->name('admin.lecturers.export');
    Route::post('/admin/schedules', [AcademicScheduleController::class, 'storeSchedule'])->name('admin.schedules.store');
    Route::patch('/admin/schedules/{schedule}', [AcademicScheduleController::class, 'updateSchedule'])->name('admin.schedules.update');
    Route::delete('/admin/schedules/{schedule}', [AcademicScheduleController::class, 'destroySchedule'])->name('admin.schedules.destroy');
    Route::patch('/admin/schedules/{schedule}/restore', [AcademicScheduleController::class, 'restoreSchedule'])->name('admin.schedules.restore');
    Route::get('/admin/students', [StudentController::class, 'index'])->name('admin.students');
    Route::post('/admin/students', [StudentController::class, 'store'])->name('admin.students.store');
    Route::patch('/admin/students/{student}', [StudentController::class, 'update'])->name('admin.students.update');
    Route::post('/admin/students/{student}/status', [StudentController::class, 'transition'])->name('admin.students.status');
    Route::delete('/admin/students/{student}', [StudentController::class, 'destroy'])->name('admin.students.destroy');
    Route::patch('/admin/students/{student}/restore', [StudentController::class, 'restore'])->name('admin.students.restore');
    Route::post('/admin/students/bulk', [StudentController::class, 'bulk'])->name('admin.students.bulk');
    Route::post('/admin/students/import/preview', [StudentTransferController::class, 'preview'])->name('admin.students.import.preview');
    Route::post('/admin/students/imports/{token}/confirm', [StudentTransferController::class, 'confirm'])->name('admin.students.import.confirm');
    Route::delete('/admin/students/imports/{token}', [StudentTransferController::class, 'cancel'])->name('admin.students.import.cancel');
    Route::get('/admin/students/template', [StudentTransferController::class, 'template'])->name('admin.students.template');
    Route::get('/admin/students/export', [StudentTransferController::class, 'export'])->name('admin.students.export');
    Route::get('/admin/users', [UserController::class, 'index'])->name('admin.users');
    Route::post('/admin/users', [UserController::class, 'store'])->name('admin.users.store');
    Route::post('/admin/users/bulk', [UserController::class, 'bulk'])->name('admin.users.bulk');
    Route::post('/admin/users/import/preview', [UserTransferController::class, 'preview'])->name('admin.users.import.preview');
    Route::post('/admin/users/imports/{token}/confirm', [UserTransferController::class, 'confirm'])->name('admin.users.import.confirm');
    Route::delete('/admin/users/imports/{token}', [UserTransferController::class, 'cancel'])->name('admin.users.import.cancel');
    Route::get('/admin/users/template', [UserTransferController::class, 'template'])->name('admin.users.template');
    Route::get('/admin/users/export', [UserTransferController::class, 'export'])->name('admin.users.export');
    Route::patch('/admin/users/{user}', [UserController::class, 'update'])->name('admin.users.update');
    Route::delete('/admin/users/{user}', [UserController::class, 'destroy'])->name('admin.users.destroy');
    Route::patch('/admin/users/{user}/restore', [UserController::class, 'restore'])->name('admin.users.restore');
});
