import { Head, router } from '@inertiajs/react';
import { BadgeCheck, Bell, BookOpenCheck, CheckCheck, CircleDollarSign, Clock3, GraduationCap, Info, ShieldCheck } from 'lucide-react';
import type { ReactNode } from 'react';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Item = { id: number; type: string; title: string; message: string; link: string | null; read_at: string | null; created_at: string };
type Props = { notifications: { data: Item[]; total: number; current_page: number; last_page: number }; filters: { status: string; type: string }; types: string[] };

export default function NotificationPage({ notifications, filters, types }: Props) {
  function apply(status: string, type = filters.type) { router.get('/notifications', { status, type }, { preserveState: false, replace: true }); }
  return <DashboardLayout><Head title="Notifikasi" />
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-cyan-600">Communication center</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">Notifikasi.</h1><p className="mt-2 text-sm text-slate-500">Pembaruan penting dari aktivitas akademik dan keuangan Anda.</p></div><button onClick={() => router.post('/notifications/read-all', {}, { preserveScroll: true })} className="action-secondary"><CheckCheck size={15} /> Tandai semua dibaca</button></header>
    <div className="mt-7 flex flex-wrap gap-2"><Filter active={!filters.status} onClick={() => apply('')} label="Semua" /><Filter active={filters.status === 'unread'} onClick={() => apply('unread')} label="Belum dibaca" /><Filter active={filters.status === 'read'} onClick={() => apply('read')} label="Sudah dibaca" />{types.map((type) => <Filter key={type} active={filters.type === type} onClick={() => apply(filters.status, filters.type === type ? '' : type)} label={labelType(type)} />)}</div>
    <section className="mt-5 overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div className="divide-y divide-slate-100">{notifications.data.map((item) => <button key={item.id} onClick={() => router.post(`/notifications/${item.id}/read`)} className={`flex w-full gap-4 p-5 text-left transition hover:bg-slate-50 ${item.read_at ? 'opacity-65' : 'bg-cyan-50/20'}`}><NotificationIcon type={item.type} /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><h2 className="text-sm font-semibold text-slate-900">{item.title}</h2>{!item.read_at && <span className="mt-1 size-2 shrink-0 rounded-full bg-cyan-500 shadow-[0_0_8px_rgba(6,182,212,.45)]" />}</div><p className="mt-1 text-sm leading-6 text-slate-500">{item.message}</p><p className="mt-2 flex items-center gap-1 text-[10px] text-slate-400"><Clock3 size={11} /> {formatDate(item.created_at)}</p></div></button>)}{!notifications.data.length && <div className="p-14 text-center"><Bell size={30} className="mx-auto text-slate-300" /><h2 className="mt-3 font-semibold text-slate-700">Kotak masuk bersih</h2><p className="mt-1 text-sm text-slate-400">Tidak ada notifikasi untuk filter ini.</p></div>}</div></section>
  </DashboardLayout>;
}

function Filter({ active, onClick, label }: { active: boolean; onClick: () => void; label: string }) { return <button onClick={onClick} className={`rounded-xl px-3 py-2 text-xs font-semibold ring-1 ${active ? 'bg-slate-950 text-white ring-slate-950' : 'bg-white text-slate-500 ring-slate-200 hover:text-cyan-600'}`}>{label}</button>; }
function NotificationIcon({ type }: { type: string }) { const map: Record<string, { icon: ReactNode; classes: string }> = { finance: { icon: <CircleDollarSign size={19} />, classes: 'bg-amber-50 text-amber-600' }, grades: { icon: <GraduationCap size={19} />, classes: 'bg-emerald-50 text-emerald-600' }, lms: { icon: <BookOpenCheck size={19} />, classes: 'bg-rose-50 text-rose-600' }, registration: { icon: <BadgeCheck size={19} />, classes: 'bg-sky-50 text-sky-600' }, security: { icon: <ShieldCheck size={19} />, classes: 'bg-violet-50 text-violet-600' } }; const selected = map[type] ?? { icon: <Info size={19} />, classes: 'bg-slate-100 text-slate-600' }; return <div className={`flex size-11 shrink-0 items-center justify-center rounded-xl ${selected.classes}`}>{selected.icon}</div>; }
function labelType(type: string) { return ({ finance: 'Keuangan', grades: 'Nilai', lms: 'LMS', registration: 'Registrasi', security: 'Keamanan' } as Record<string, string>)[type] ?? type; }
function formatDate(value: string) { return new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
