import { Head, router, useForm } from '@inertiajs/react';
import { Award, BadgeCheck, BarChart3, BookOpenCheck, CheckCircle2, ClipboardEdit, FileCheck2, GraduationCap, LockKeyhole, Pencil, Plus, RefreshCcw, Search, Send, Sparkles, Trash2, TrendingUp, UsersRound } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { ModalForm } from '@/components/ModalForm';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Term = { id: number; name: string; code: string; semester: string; is_active?: boolean };
type Course = { id: number; code: string; name: string; credits: number; program?: { id: number; code: string; name: string } };
type Score = { id: number; grade_component_id: number; score: string };
type Component = { id: number; name: string; weight: string; max_score: string; sort_order: number; scores?: Score[] };
type Sheet = { id: number; status: 'draft' | 'published' | 'finalized'; notes: string | null; published_at: string | null; finalized_at: string | null; components: Component[]; published_by?: { name: string } | null; finalized_by?: { name: string } | null };
type Enrollment = { id: number; credits: number; final_score: string | null; letter_grade: string | null; grade_status: string; grade_scores: Score[]; registration: { student: { id: number; nim: string; user: { id: number; name: string; email: string }; program: { code: string; name: string } } } };
type ClassGroup = { id: number; name: string; enrollments_count: number; day: string; starts_at: string; ends_at: string; course: Course; academic_term: Term; lecturer: { id: number; name: string; nidn: string } | null; grade_sheet: Sheet | null; enrollments?: Enrollment[] };
type GradeRow = { id: number; credits: number; final_score: string; letter_grade: string; grade_status: string; grade_points: number; course: Course; academic_term: Term; class_name: string; lecturer: { name: string } | null };
type Page<T> = { data: T[]; current_page: number; last_page: number; total: number };
type Props = { mode: 'student' | 'manager'; filters: { academic_term_id: string; q: string; selected: number | null }; termOptions: Term[]; student: { nim: string; user: { name: string }; program: { code: string; name: string }; academic_advisor: { name: string } | null } | null; khs: GradeRow[]; transcript: GradeRow[]; semesterSummaries: { academic_term: Term; credits: number; courses: number; gpa: number }[]; metrics: { credits: number; courses: number; gpa: number } | null; gradeScale: { letter: string; minimum: number; points: number }[]; classGroups: Page<ClassGroup> | null; selectedClass: ClassGroup | null; summary?: { classes: number; draft: number; published: number; finalized: number }; abilities: { manage: boolean; finalize: boolean } };

export default function GradesPage(props: Props) {
  return <DashboardLayout><Head title="Nilai & Transkrip" />{props.mode === 'student' ? <StudentWorkspace {...props} /> : <ManagerWorkspace {...props} />}</DashboardLayout>;
}

function StudentWorkspace({ filters, termOptions, student, khs, transcript, semesterSummaries, metrics, gradeScale }: Props) {
  return <>
    <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold text-teal-600">Rekam akademik pribadi</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">KHS & transkrip.</h1><p className="mt-2 text-sm text-slate-500">Pantau hasil studi yang sudah dipublikasikan secara aman dan transparan.</p></div><select value={filters.academic_term_id} onChange={(event) => router.get('/academic/grades', { academic_term_id: event.target.value }, { preserveState: false, replace: true })} className="input w-full bg-white lg:w-64"><option value="">Pilih semester</option>{termOptions.map((term) => <option key={term.id} value={term.id}>{term.code} · {term.semester}</option>)}</select></div>
    <section className="relative mt-8 overflow-hidden rounded-[1.75rem] bg-gradient-to-br from-[#061725] via-[#0a3140] to-[#0c5554] p-6 text-white shadow-xl shadow-slate-900/10 sm:p-8"><div className="absolute -right-16 -top-24 size-64 rounded-full bg-teal-300/15 blur-3xl" /><div className="relative grid gap-7 lg:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2 text-xs font-semibold text-teal-200"><Sparkles size={15} /> Ringkasan prestasi akademik</div><h2 className="mt-4 text-2xl font-semibold">{student?.user.name}</h2><p className="mt-1 text-sm text-slate-300">{student?.nim} · {student?.program.code} · {student?.program.name}</p><p className="mt-5 text-xs text-slate-400">Dosen PA: {student?.academic_advisor?.name ?? 'Belum ditentukan'}</p></div><div className="grid grid-cols-3 gap-3"><DarkMetric label="IPK" value={(metrics?.gpa ?? 0).toFixed(2)} /><DarkMetric label="SKS" value={String(metrics?.credits ?? 0)} /><DarkMetric label="MK" value={String(metrics?.courses ?? 0)} /></div></div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><section className="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200/80"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-semibold text-slate-950">Kartu Hasil Studi</h2><p className="mt-1 text-xs text-slate-400">Nilai pada semester terpilih.</p></div><Award size={20} className="text-teal-600" /></div><GradeTable rows={khs} /></section><section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200/80"><h2 className="font-semibold text-slate-950">Performa per semester</h2><div className="mt-4 space-y-3">{semesterSummaries.map((item) => <div key={item.academic_term.id} className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-slate-700">{item.academic_term.code}</p><p className="mt-1 text-[11px] text-slate-400">{item.courses} mata kuliah · {item.credits} SKS</p></div><span className="text-xl font-semibold text-teal-700">{item.gpa.toFixed(2)}</span></div></div>)}{!semesterSummaries.length && <Empty text="Belum ada nilai yang dipublikasikan." />}</div><div className="mt-5 border-t border-slate-100 pt-5"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Skala nilai aktif</p><div className="mt-3 flex flex-wrap gap-2">{gradeScale.map((scale) => <span key={scale.letter} className="rounded-lg bg-teal-50 px-2.5 py-1.5 text-[10px] font-semibold text-teal-700">{scale.letter} ≥ {scale.minimum}</span>)}</div></div></section></div>
    <section className="mt-6 overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200/80"><div className="flex items-center gap-3 border-b border-slate-100 p-5"><div className="flex size-10 items-center justify-center rounded-xl bg-violet-50 text-violet-600"><GraduationCap size={19} /></div><div><h2 className="font-semibold text-slate-950">Transkrip sementara</h2><p className="text-xs text-slate-400">Akumulasi seluruh nilai published dan finalized.</p></div></div><GradeTable rows={transcript} showTerm /></section>
  </>;
}

function ManagerWorkspace({ filters, termOptions, classGroups, selectedClass, summary, abilities, gradeScale }: Props) {
  const [filterData, setFilterData] = useState(filters);
  const [componentModal, setComponentModal] = useState<{ open: boolean; item: Component | null }>({ open: false, item: null });
  const [publishModal, setPublishModal] = useState(false);
  const componentForm = useForm({ name: '', weight: '0', max_score: '100', sort_order: 0 });
  const publishForm = useForm({ notes: '' });
  const sheet = selectedClass?.grade_sheet ?? null;
  const components = sheet?.components ?? [];
  const totalWeight = components.reduce((sum, item) => sum + Number(item.weight), 0);

  function filter(event: FormEvent) { event.preventDefault(); router.get('/academic/grades', { q: filterData.q, academic_term_id: filterData.academic_term_id }, { preserveState: false, replace: true }); }
  function openComponent(item: Component | null = null) { componentForm.clearErrors(); componentForm.setData(item ? { name: item.name, weight: item.weight, max_score: item.max_score, sort_order: item.sort_order } : { name: '', weight: '0', max_score: '100', sort_order: components.length + 1 }); setComponentModal({ open: true, item }); }
  function closeComponent() { if (!componentForm.processing) setComponentModal({ open: false, item: null }); }
  function submitComponent(event: FormEvent) { event.preventDefault(); if (!selectedClass) return; const options = { preserveScroll: true, onSuccess: closeComponent }; if (componentModal.item) componentForm.patch(`/academic/grades/classes/${selectedClass.id}/components/${componentModal.item.id}`, options); else componentForm.post(`/academic/grades/classes/${selectedClass.id}/components`, options); }
  function publish(event: FormEvent) { event.preventDefault(); if (!selectedClass) return; publishForm.post(`/academic/grades/classes/${selectedClass.id}/publish`, { preserveScroll: true, onSuccess: () => setPublishModal(false) }); }
  function destroyComponent(item: Component) { if (selectedClass && window.confirm(`Hapus komponen ${item.name} beserta skor terkait?`)) router.delete(`/academic/grades/classes/${selectedClass.id}/components/${item.id}`, { preserveScroll: true }); }

  return <>
    <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold text-teal-600">Evaluasi akademik</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">Nilai, KHS & transkrip.</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Kelola komponen, skor mahasiswa, publikasi, dan finalisasi nilai dengan jejak audit.</p></div><div className="flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-xs font-semibold text-slate-600 ring-1 ring-slate-200"><LockKeyhole size={16} className="text-teal-600" /> Finalisasi hanya oleh Prodi/Admin</div></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={<BookOpenCheck size={18} />} label="Kelas bernilai" value={summary?.classes ?? 0} tone="teal" /><Summary icon={<ClipboardEdit size={18} />} label="Lembar draf" value={summary?.draft ?? 0} tone="amber" /><Summary icon={<Send size={18} />} label="Published" value={summary?.published ?? 0} tone="blue" /><Summary icon={<BadgeCheck size={18} />} label="Finalized" value={summary?.finalized ?? 0} tone="emerald" /></div>
    <section className="mt-6 grid gap-6 xl:grid-cols-[.65fr_1.35fr]"><div><form onSubmit={filter} className="grid gap-3 rounded-2xl bg-white p-4 ring-1 ring-slate-200/80"><label className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={filterData.q} onChange={(event) => setFilterData({ ...filterData, q: event.target.value })} className="input pl-9" placeholder="Cari mata kuliah atau kelas" /></label><div className="flex gap-2"><select value={filterData.academic_term_id} onChange={(event) => setFilterData({ ...filterData, academic_term_id: event.target.value })} className="input"><option value="">Semua semester</option>{termOptions.map((term) => <option key={term.id} value={term.id}>{term.code}</option>)}</select><button className="rounded-xl bg-slate-900 px-4 text-white"><Search size={16} /></button></div></form><div className="mt-4 space-y-3">{classGroups?.data.map((item) => <button key={item.id} onClick={() => router.get('/academic/grades', { ...filterData, selected: item.id }, { preserveState: false })} className={`w-full rounded-2xl bg-white p-4 text-left transition ${selectedClass?.id === item.id ? 'ring-2 ring-teal-500 shadow-lg shadow-teal-900/5' : 'ring-1 ring-slate-200 hover:ring-teal-300'}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-900">{item.course.code} · {item.course.name}</p><p className="mt-1 text-xs text-slate-400">Kelas {item.name} · {item.academic_term.code}</p></div><Status value={item.grade_sheet?.status ?? 'unconfigured'} /></div><p className="mt-3 flex items-center gap-2 text-[11px] text-slate-500"><UsersRound size={13} /> {item.enrollments_count} mahasiswa · {item.lecturer?.name ?? 'Tanpa dosen'}</p></button>)}{!classGroups?.data.length && <Empty text="Tidak ada kelas dengan mahasiswa aktif." />}</div>{classGroups && <div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>{classGroups.total} kelas</span><div className="flex gap-2"><PageButton disabled={classGroups.current_page <= 1} onClick={() => router.get('/academic/grades', { ...filterData, page: classGroups.current_page - 1 })}>Sebelumnya</PageButton><PageButton disabled={classGroups.current_page >= classGroups.last_page} onClick={() => router.get('/academic/grades', { ...filterData, page: classGroups.current_page + 1 })}>Berikutnya</PageButton></div></div>}</div>
      <div>{selectedClass ? <div className="space-y-6"><section className="relative overflow-hidden rounded-[1.6rem] bg-gradient-to-br from-[#071827] to-[#134955] p-6 text-white shadow-lg shadow-slate-900/10"><div className="absolute -right-14 -top-20 size-48 rounded-full bg-teal-300/15 blur-3xl" /><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><Status value={sheet?.status ?? 'unconfigured'} dark /><span className="text-xs text-slate-400">{selectedClass.academic_term.code}</span></div><h2 className="mt-4 text-xl font-semibold">{selectedClass.course.code} · {selectedClass.course.name}</h2><p className="mt-2 text-sm text-slate-300">Kelas {selectedClass.name} · {selectedClass.course.credits} SKS · {selectedClass.lecturer?.name ?? 'Tanpa dosen'}</p></div><div className="rounded-2xl bg-white/10 px-5 py-4 text-right"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Bobot komponen</p><p className={`mt-2 text-3xl font-semibold ${Math.abs(totalWeight - 100) < .001 ? 'text-teal-200' : 'text-amber-200'}`}>{totalWeight.toFixed(2)}%</p></div></div><div className="relative mt-5 flex flex-wrap gap-2">{sheet?.status === 'draft' && abilities.manage && <button disabled={Math.abs(totalWeight - 100) > .001 || !(selectedClass.enrollments?.length)} onClick={() => setPublishModal(true)} className="rounded-xl bg-teal-300 px-4 py-2.5 text-xs font-semibold text-slate-950 disabled:opacity-40"><Send className="mr-2 inline" size={14} />Publikasikan nilai</button>}{sheet?.status === 'published' && abilities.finalize && <><button onClick={() => window.confirm('Finalisasi akan mengunci nilai secara permanen. Lanjutkan?') && router.post(`/academic/grades/classes/${selectedClass.id}/finalize`, {}, { preserveScroll: true })} className="rounded-xl bg-emerald-500 px-4 py-2.5 text-xs font-semibold text-white"><CheckCircle2 className="mr-2 inline" size={14} />Finalisasi</button><button onClick={() => window.confirm('Buka kembali nilai menjadi draf? Nilai sementara disembunyikan dari mahasiswa.') && router.post(`/academic/grades/classes/${selectedClass.id}/reopen`, {}, { preserveScroll: true })} className="rounded-xl bg-white/10 px-4 py-2.5 text-xs font-semibold text-white"><RefreshCcw className="mr-2 inline" size={14} />Buka kembali</button></>}</div></section>
        <section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200/80"><div className="flex items-center justify-between gap-4"><div><h3 className="font-semibold text-slate-950">Komponen penilaian</h3><p className="mt-1 text-xs text-slate-400">Bobot total wajib 100% sebelum publikasi.</p></div>{abilities.manage && (!sheet || sheet.status === 'draft') && <button onClick={() => openComponent()} className="flex items-center gap-2 rounded-xl bg-teal-600 px-4 py-2.5 text-xs font-semibold text-white"><Plus size={15} /> Tambah</button>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2">{components.map((item) => <div key={item.id} className="group rounded-xl bg-slate-50 p-4 ring-1 ring-slate-100"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-800">{item.name}</p><p className="mt-1 text-xs text-slate-400">Maks. {Number(item.max_score)} · Bobot {Number(item.weight)}%</p></div>{abilities.manage && sheet?.status === 'draft' && <div className="flex gap-1"><button onClick={() => openComponent(item)} className="rounded-lg p-2 text-slate-400 hover:bg-white hover:text-teal-600"><Pencil size={14} /></button><button onClick={() => destroyComponent(item)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={14} /></button></div>}</div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-gradient-to-r from-teal-500 to-cyan-400" style={{ width: `${Math.min(Number(item.weight), 100)}%` }} /></div></div>)}{!components.length && <div className="sm:col-span-2"><Empty text="Belum ada komponen nilai. Tambahkan komponen pertama melalui modal." /></div>}</div></section>
        <section className="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200/80"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h3 className="font-semibold text-slate-950">Nilai mahasiswa</h3><p className="mt-1 text-xs text-slate-400">Simpan per mahasiswa; publikasi hanya aktif setelah seluruh nilai lengkap.</p></div><FileCheck2 size={20} className="text-teal-600" /></div><div className="divide-y divide-slate-100">{selectedClass.enrollments?.map((enrollment) => <ScoreRow key={`${enrollment.id}-${components.map((component) => component.id).join('-')}`} classId={selectedClass.id} enrollment={enrollment} components={components} editable={Boolean(abilities.manage && sheet?.status === 'draft')} />)}{!selectedClass.enrollments?.length && <Empty text="Belum ada mahasiswa enrolled pada kelas ini." />}</div></section>
      </div> : <div className="rounded-2xl bg-white p-12 ring-1 ring-slate-200/80"><Empty text="Pilih kelas untuk mengelola lembar nilai." /></div>}</div></section>

    <ModalForm open={componentModal.open} onClose={closeComponent} closeDisabled={componentForm.processing} title={componentModal.item ? 'Edit komponen nilai' : 'Tambah komponen nilai'} description="Atur nama, nilai maksimum, dan kontribusi komponen terhadap nilai akhir." icon={componentModal.item ? <Pencil size={18} /> : <Plus size={18} />} footer={<div className="flex justify-end gap-2"><button type="button" onClick={closeComponent} disabled={componentForm.processing} className="rounded-xl px-4 py-2.5 text-xs font-semibold text-slate-500 ring-1 ring-slate-200">Batal</button><button form="grade-component-form" disabled={componentForm.processing} className="rounded-xl bg-gradient-to-r from-teal-600 to-cyan-600 px-5 py-2.5 text-xs font-semibold text-white shadow-lg shadow-teal-700/15 disabled:opacity-40">{componentForm.processing ? 'Menyimpan...' : 'Simpan komponen'}</button></div>}>
      <form id="grade-component-form" onSubmit={submitComponent} className="grid gap-4 sm:grid-cols-2"><Field label="Nama komponen" className="sm:col-span-2"><input autoFocus required value={componentForm.data.name} onChange={(event) => componentForm.setData('name', event.target.value)} className="input" placeholder="UTS, UAS, Tugas, Kehadiran" /></Field><Field label="Bobot (%)"><input required type="number" min="0.01" max="100" step="0.01" value={componentForm.data.weight} onChange={(event) => componentForm.setData('weight', event.target.value)} className="input" /></Field><Field label="Nilai maksimum"><input required type="number" min="0.01" max="1000" step="0.01" value={componentForm.data.max_score} onChange={(event) => componentForm.setData('max_score', event.target.value)} className="input" /></Field><Field label="Urutan"><input type="number" min="0" value={componentForm.data.sort_order} onChange={(event) => componentForm.setData('sort_order', Number(event.target.value))} className="input" /></Field><div className="flex items-end"><div className="w-full rounded-xl bg-teal-50 p-3 text-xs text-teal-700"><BarChart3 size={14} className="mr-2 inline" />Sisa bobot: {(100 - totalWeight + Number(componentModal.item?.weight ?? 0)).toFixed(2)}%</div></div><div className="sm:col-span-2"><Errors errors={componentForm.errors} /></div></form>
    </ModalForm>

    <ModalForm open={publishModal} onClose={() => !publishForm.processing && setPublishModal(false)} closeDisabled={publishForm.processing} title="Publikasikan nilai" description="Sistem menghitung nilai akhir dan huruf mutu, lalu menampilkannya pada KHS mahasiswa." icon={<Send size={18} />} size="sm" footer={<div className="flex justify-end gap-2"><button type="button" onClick={() => setPublishModal(false)} className="rounded-xl px-4 py-2.5 text-xs font-semibold text-slate-500 ring-1 ring-slate-200">Batal</button><button form="publish-grade-form" disabled={publishForm.processing} className="rounded-xl bg-teal-600 px-5 py-2.5 text-xs font-semibold text-white disabled:opacity-40">Publikasikan</button></div>}><form id="publish-grade-form" onSubmit={publish}><div className="rounded-xl bg-amber-50 p-4 text-xs leading-5 text-amber-700">Pastikan seluruh skor benar. Nilai published masih dapat dibuka kembali oleh Prodi/Admin sebelum finalisasi.</div><div className="mt-4 flex flex-wrap gap-2">{gradeScale.map((scale) => <span key={scale.letter} className="rounded-lg bg-teal-50 px-2.5 py-1.5 text-[10px] font-semibold text-teal-700">{scale.letter} ≥ {scale.minimum}</span>)}</div><Field label="Catatan untuk mahasiswa" className="mt-4"><textarea value={publishForm.data.notes} onChange={(event) => publishForm.setData('notes', event.target.value)} className="input min-h-28" placeholder="Opsional" /></Field><Errors errors={publishForm.errors} /></form></ModalForm>
  </>;
}

function ScoreRow({ classId, enrollment, components, editable }: { classId: number; enrollment: Enrollment; components: Component[]; editable: boolean }) {
  const initial = Object.fromEntries(components.map((component) => [String(component.id), enrollment.grade_scores.find((score) => score.grade_component_id === component.id)?.score ?? '']));
  const form = useForm<{ scores: Record<string, string> }>({ scores: initial });
  function setScore(id: number, value: string) { form.setData('scores', { ...form.data.scores, [String(id)]: value }); }
  function submit(event: FormEvent) { event.preventDefault(); form.put(`/academic/grades/classes/${classId}/enrollments/${enrollment.id}/scores`, { preserveScroll: true }); }
  const student = enrollment.registration.student;
  return <div className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="text-sm font-semibold text-slate-900">{student.user.name}</p><p className="mt-1 text-xs text-slate-400">{student.nim} · {student.program.code}</p></div>{enrollment.final_score !== null && <div className="flex items-center gap-2"><span className="rounded-xl bg-slate-50 px-3 py-2 text-xs text-slate-500 ring-1 ring-slate-200">Nilai akhir <strong className="ml-1 text-slate-800">{Number(enrollment.final_score).toFixed(2)}</strong></span><span className="flex size-10 items-center justify-center rounded-xl bg-teal-50 text-sm font-bold text-teal-700">{enrollment.letter_grade}</span></div>}</div>{editable && components.length > 0 ? <form onSubmit={submit} className="mt-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{components.map((component) => <Field key={component.id} label={`${component.name} / ${Number(component.max_score)}`}><input required type="number" min="0" max={component.max_score} step="0.01" value={form.data.scores[String(component.id)] ?? ''} onChange={(event) => setScore(component.id, event.target.value)} className="input" /></Field>)}</div><Errors errors={form.errors} /><button disabled={form.processing} className="mt-3 rounded-xl bg-slate-900 px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-40">{form.processing ? 'Menyimpan...' : 'Simpan nilai'}</button></form> : components.length > 0 ? <div className="mt-4 flex flex-wrap gap-2">{components.map((component) => <span key={component.id} className="rounded-lg bg-slate-50 px-3 py-2 text-[11px] text-slate-600 ring-1 ring-slate-200">{component.name}: <strong>{enrollment.grade_scores.find((score) => score.grade_component_id === component.id)?.score ?? '—'}</strong></span>)}</div> : null}</div>;
}

function GradeTable({ rows, showTerm = false }: { rows: GradeRow[]; showTerm?: boolean }) { return <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-slate-50 text-[10px] font-bold uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Mata kuliah</th>{showTerm && <th className="px-5 py-3">Semester</th>}<th className="px-5 py-3">SKS</th><th className="px-5 py-3">Angka</th><th className="px-5 py-3">Huruf</th><th className="px-5 py-3">Mutu</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id}><td className="px-5 py-4"><p className="font-semibold text-slate-800">{row.course.code} · {row.course.name}</p><p className="mt-1 text-[11px] text-slate-400">Kelas {row.class_name} · {row.lecturer?.name ?? '—'}</p></td>{showTerm && <td className="px-5 py-4 text-slate-500">{row.academic_term.code}</td>}<td className="px-5 py-4 text-slate-600">{row.credits}</td><td className="px-5 py-4 font-semibold text-slate-700">{Number(row.final_score).toFixed(2)}</td><td className="px-5 py-4"><span className="flex size-9 items-center justify-center rounded-xl bg-teal-50 font-bold text-teal-700">{row.letter_grade}</span></td><td className="px-5 py-4 text-slate-600">{(row.grade_points * row.credits).toFixed(2)}</td></tr>)}{!rows.length && <tr><td colSpan={showTerm ? 6 : 5}><Empty text="Belum ada nilai pada bagian ini." /></td></tr>}</tbody></table></div>; }
function DarkMetric({ label, value }: { label: string; value: string }) { return <div className="min-w-20 rounded-2xl bg-white/10 p-4 text-center ring-1 ring-white/10"><p className="text-2xl font-semibold text-teal-200">{value}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p></div>; }
function Summary({ icon, label, value, tone }: { icon: ReactNode; label: string; value: number; tone: 'teal' | 'amber' | 'blue' | 'emerald' }) { const color = { teal: 'bg-teal-50 text-teal-600', amber: 'bg-amber-50 text-amber-600', blue: 'bg-blue-50 text-blue-600', emerald: 'bg-emerald-50 text-emerald-600' }[tone]; return <div className="rounded-2xl bg-white p-5 ring-1 ring-slate-200/80"><div className="flex items-center justify-between"><span className={`flex size-10 items-center justify-center rounded-xl ${color}`}>{icon}</span><span className="text-2xl font-semibold text-slate-950">{value.toLocaleString('id-ID')}</span></div><p className="mt-3 text-xs font-medium text-slate-500">{label}</p></div>; }
function Status({ value, dark = false }: { value: string; dark?: boolean }) { const tones: Record<string, string> = dark ? { draft: 'bg-amber-300/15 text-amber-200', published: 'bg-blue-300/15 text-blue-200', finalized: 'bg-emerald-300/15 text-emerald-200', unconfigured: 'bg-white/10 text-slate-300' } : { draft: 'bg-amber-50 text-amber-700', published: 'bg-blue-50 text-blue-700', finalized: 'bg-emerald-50 text-emerald-700', unconfigured: 'bg-slate-100 text-slate-500' }; const labels: Record<string, string> = { draft: 'Draf', published: 'Published', finalized: 'Final', unconfigured: 'Belum disiapkan' }; return <span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${tones[value] ?? tones.unconfigured}`}>{labels[value] ?? value}</span>; }
function Field({ label, children, className = '' }: { label: string; children: ReactNode; className?: string }) { return <label className={`block ${className}`}><span className="mb-2 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
function Errors({ errors }: { errors: Record<string, string> }) { const values = Object.values(errors); return values.length ? <ul className="mt-3 space-y-1 rounded-xl bg-rose-50 p-3 text-xs text-rose-600">{values.map((error, index) => <li key={`${error}-${index}`}>{error}</li>)}</ul> : null; }
function Empty({ text }: { text: string }) { return <div className="flex flex-col items-center justify-center py-9 text-center"><TrendingUp size={21} className="text-slate-300" /><p className="mt-2 text-xs text-slate-400">{text}</p></div>; }
function PageButton({ children, disabled, onClick }: { children: ReactNode; disabled: boolean; onClick: () => void }) { return <button disabled={disabled} onClick={onClick} className="rounded-lg px-3 py-2 ring-1 ring-slate-200 disabled:opacity-30">{children}</button>; }
