import { Head, router, useForm } from '@inertiajs/react';
import { AlertTriangle, CalendarClock, CheckCircle2, HeartPulse, MessageSquareText, Plus, ShieldAlert, UserRound } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { ModalForm } from '@/components/ModalForm';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Student = { id: number; nim: string; status: string; user?: { name: string }; program?: { code: string; name: string }; academic_advisor?: { name: string } };
type Appointment = { id: number; student: Student; lecturer?: { name: string }; starts_at: string; ends_at: string; mode: string; location?: string; agenda: string; status: string; student_notes?: string; lecturer_notes?: string };
type Note = { id: number; student: Student; lecturer?: { name: string }; title: string; content: string; follow_up_due?: string; follow_up_status: string; created_at: string };
type Warning = { id: number; student: Student; assigned_lecturer?: { name: string }; warning_type: string; severity: string; score?: number; evidence?: Record<string, number | string | null>; status: string; resolution_notes?: string };
type Availability = { id: number; weekday: number; starts_at: string; ends_at: string; mode: string };
type Intervention = { id: number; student: Student; title: string; action_plan: string; due_on?: string; status: string; outcome?: string };
type Props = { mode: 'student' | 'manager'; students: Student[]; appointments: Appointment[]; notes: Note[]; warnings: Warning[]; availability?: Availability[]; interventions?: Intervention[]; stats: { students: number; appointments: number; openWarnings: number; followUps: number }; abilities: { createAppointment: boolean; manage: boolean; canWriteNote: boolean } };

const warningLabels: Record<string, string> = { low_gpa: 'IPS/IPK rendah', low_attendance: 'Presensi rendah', outstanding_bill: 'Tunggakan tagihan', inactive_status: 'Status mahasiswa tidak aktif' };
const statusLabels: Record<string, string> = { pending: 'Menunggu', confirmed: 'Dikonfirmasi', completed: 'Selesai', cancelled: 'Dibatalkan', no_show: 'Tidak hadir' };

export default function GuidancePage({ mode, students, appointments, notes, warnings, availability = [], interventions = [], stats, abilities }: Props) {
  const [appointmentOpen, setAppointmentOpen] = useState(false); const [noteOpen, setNoteOpen] = useState(false); const [availabilityOpen, setAvailabilityOpen] = useState(false); const [interventionOpen, setInterventionOpen] = useState(false); const [activeStudent, setActiveStudent] = useState<Student | null>(students[0] ?? null);
  const appointmentForm = useForm({ student_id: activeStudent?.id ? String(activeStudent.id) : '', starts_at: '', ends_at: '', mode: 'online', location: '', agenda: '', student_notes: '' });
  const noteForm = useForm({ student_id: activeStudent?.id ?? 0, title: '', content: '', follow_up_due: '', follow_up_status: 'none' });
  const availabilityForm = useForm({ weekday: 1, starts_at: '09:00', ends_at: '10:00', mode: 'online' });
  const interventionForm = useForm({ student_id: activeStudent?.id ?? 0, warning_id: '', title: '', action_plan: '', due_on: '', assigned_lecturer_id: '' });
  function openAppointment() { appointmentForm.setData((data) => ({ ...data, student_id: String(activeStudent?.id ?? students[0]?.id ?? '') })); appointmentForm.clearErrors(); setAppointmentOpen(true); }
  function submitAppointment(e: FormEvent) { e.preventDefault(); appointmentForm.post('/academic/guidance/appointments', { preserveScroll: true, onSuccess: () => setAppointmentOpen(false) }); }
  function openNote(student?: Student) { const target = student ?? activeStudent ?? students[0]; if (!target) return; setActiveStudent(target); noteForm.setData({ student_id: target.id, title: '', content: '', follow_up_due: '', follow_up_status: 'none' }); noteForm.clearErrors(); setNoteOpen(true); }
  function submitNote(e: FormEvent) { e.preventDefault(); noteForm.post('/academic/guidance/notes', { preserveScroll: true, onSuccess: () => setNoteOpen(false) }); }
  function updateAppointment(item: Appointment, status: string) { router.patch(`/academic/guidance/appointments/${item.id}`, { status }, { preserveScroll: true }); }
  function updateWarning(item: Warning, status: string) { router.patch(`/academic/guidance/warnings/${item.id}`, { status }, { preserveScroll: true }); }
  function submitAvailability(e: FormEvent) { e.preventDefault(); availabilityForm.post('/academic/guidance/availability', { preserveScroll: true, onSuccess: () => setAvailabilityOpen(false) }); }
  function openIntervention(item?: Warning) { const student = item?.student ?? activeStudent ?? students[0]; if (!student) return; setActiveStudent(student); interventionForm.setData({ student_id: student.id, warning_id: item?.id ? String(item.id) : '', title: item ? `Tindak lanjut: ${warningLabels[item.warning_type] ?? item.warning_type}` : '', action_plan: '', due_on: '', assigned_lecturer_id: '' }); interventionForm.clearErrors(); setInterventionOpen(true); }
  function submitIntervention(e: FormEvent) { e.preventDefault(); interventionForm.post('/academic/guidance/interventions', { preserveScroll: true, onSuccess: () => setInterventionOpen(false) }); }
  function updateIntervention(item: Intervention, status: string) { router.patch(`/academic/guidance/interventions/${item.id}`, { status }, { preserveScroll: true }); }
  const weekdayLabels = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'];
  const statCards = [{ label: 'Mahasiswa dipantau', value: stats.students, Icon: UserRound, gradient: 'from-cyan-500 to-blue-600' }, { label: 'Jadwal aktif', value: stats.appointments, Icon: CalendarClock, gradient: 'from-violet-500 to-fuchsia-600' }, { label: 'Early warning terbuka', value: stats.openWarnings, Icon: ShieldAlert, gradient: 'from-amber-500 to-orange-600' }, { label: 'Tindak lanjut', value: stats.followUps, Icon: MessageSquareText, gradient: 'from-emerald-500 to-teal-600' }];
  return <DashboardLayout><Head title="Bimbingan Akademik" /><div className="space-y-6">
    <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-950 via-indigo-800 to-cyan-700 p-6 text-white shadow-xl"><div className="relative z-10 flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-200">Student success center</p><h1 className="mt-2 text-3xl font-black tracking-tight">Bimbingan & early warning</h1><p className="mt-2 max-w-2xl text-sm text-indigo-100">Jadwal konsultasi, catatan privat, dan sinyal risiko akademik dalam satu ruang kerja terarah.</p></div>{mode === 'student' && abilities.createAppointment && <button onClick={openAppointment} className="inline-flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm font-bold text-indigo-800 shadow-lg"><Plus size={17} /> Ajukan bimbingan</button>}</div><HeartPulse className="absolute -bottom-10 -right-5 h-44 w-44 text-white/10" /></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{statCards.map(({ label, value, Icon, gradient }) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className={`mb-3 flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br ${gradient} text-white`}><Icon size={19} /></div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-slate-900">{value}</p></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.08fr_.92fr]">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Jadwal konsultasi</h2><p className="text-xs text-slate-500">Atur percakapan yang fokus dan terdokumentasi.</p></div>{mode === 'manager' && abilities.canWriteNote && <button onClick={() => openNote()} className="inline-flex items-center gap-1 rounded-xl bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700"><MessageSquareText size={15} /> Catatan</button>}</div><div className="space-y-3">{appointments.length ? appointments.map((item) => <div key={item.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold text-slate-900">{item.agenda}</p><p className="mt-1 text-xs text-slate-500">{item.student.user?.name} · {item.student.nim} · {new Date(item.starts_at).toLocaleString('id-ID', { dateStyle: 'medium', timeStyle: 'short' })}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-[11px] font-bold text-slate-600">{statusLabels[item.status] ?? item.status}</span></div><p className="mt-2 text-xs text-slate-500">{item.mode === 'online' ? 'Daring' : item.mode === 'phone' ? 'Telepon' : `Luring · ${item.location ?? 'lokasi belum diisi'}`}</p>{abilities.manage && ['pending', 'confirmed'].includes(item.status) && <div className="mt-3 flex gap-2">{item.status === 'pending' && <button onClick={() => updateAppointment(item, 'confirmed')} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-bold text-white">Konfirmasi</button>}{item.status === 'confirmed' && <button onClick={() => updateAppointment(item, 'completed')} className="rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-bold text-white">Tandai selesai</button>}<button onClick={() => updateAppointment(item, 'cancelled')} className="rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-bold text-slate-600">Batalkan</button></div>}</div>) : <Empty text="Belum ada jadwal bimbingan." />}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Early warning</h2><p className="text-xs text-slate-500">Sinyal risiko dihitung dari data akademik terbaru.</p></div><AlertTriangle className="text-amber-500" size={20} /></div><div className="space-y-3">{warnings.length ? warnings.map((item) => <div key={item.id} className="rounded-2xl border border-amber-100 bg-amber-50/60 p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-bold text-slate-900">{warningLabels[item.warning_type] ?? item.warning_type}</p><p className="mt-1 text-xs text-slate-600">{item.student.user?.name} · {item.student.nim}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${item.severity === 'high' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700'}`}>{item.severity}</span></div><p className="mt-2 text-xs text-slate-600">Nilai indikator: <strong>{item.score ?? '—'}</strong></p>{abilities.manage && item.status !== 'resolved' && <div className="mt-3 flex gap-2"><button onClick={() => updateWarning(item, 'acknowledged')} className="rounded-lg bg-white px-3 py-1.5 text-xs font-bold text-amber-700 ring-1 ring-amber-200">Tindak lanjuti</button><button onClick={() => updateWarning(item, 'resolved')} className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-bold text-white">Selesaikan</button></div>}</div>) : <Empty text="Tidak ada early warning aktif." />}</div></section>
    </div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Catatan bimbingan privat</h2><p className="text-xs text-slate-500">Hanya mahasiswa terkait dan pengelola yang berwenang dapat melihatnya.</p></div>{mode === 'manager' && abilities.canWriteNote && <button onClick={() => openNote()} className="rounded-xl bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Tambah catatan</button>}</div><div className="grid gap-3 md:grid-cols-2">{notes.length ? notes.map((item) => <article key={item.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex items-center justify-between gap-2"><h3 className="font-bold text-slate-900">{item.title}</h3><span className="text-[10px] font-bold uppercase text-slate-400">{item.follow_up_status}</span></div><p className="mt-2 line-clamp-3 whitespace-pre-wrap text-sm text-slate-600">{item.content}</p><p className="mt-3 text-xs text-slate-400">{item.student.user?.name} · {new Date(item.created_at).toLocaleDateString('id-ID')}</p></article>) : <Empty text="Belum ada catatan bimbingan." />}</div></section>
    <ModalForm open={appointmentOpen} onClose={() => setAppointmentOpen(false)} title="Ajukan jadwal bimbingan" description="Pilih waktu yang realistis agar dosen wali dapat mempersiapkan konsultasi." icon={<CalendarClock size={18} />} footer={<><button onClick={() => setAppointmentOpen(false)} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600">Batal</button><button onClick={submitAppointment} disabled={appointmentForm.processing} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">Kirim pengajuan</button></>}><div className="space-y-4"><Field label="Mulai"><input type="datetime-local" value={appointmentForm.data.starts_at} onChange={(e) => appointmentForm.setData('starts_at', e.target.value)} className="input" /></Field><Field label="Selesai"><input type="datetime-local" value={appointmentForm.data.ends_at} onChange={(e) => appointmentForm.setData('ends_at', e.target.value)} className="input" /></Field><Field label="Mode"><select value={appointmentForm.data.mode} onChange={(e) => appointmentForm.setData('mode', e.target.value)} className="input"><option value="online">Daring</option><option value="onsite">Luring</option><option value="phone">Telepon</option></select></Field><Field label="Lokasi / tautan"><input value={appointmentForm.data.location} onChange={(e) => appointmentForm.setData('location', e.target.value)} className="input" /></Field><Field label="Agenda"><input value={appointmentForm.data.agenda} onChange={(e) => appointmentForm.setData('agenda', e.target.value)} className="input" /></Field><Field label="Catatan awal"><textarea value={appointmentForm.data.student_notes} onChange={(e) => appointmentForm.setData('student_notes', e.target.value)} className="input min-h-24" /></Field></div></ModalForm>
    <ModalForm open={noteOpen} onClose={() => setNoteOpen(false)} title="Catatan bimbingan privat" description="Catatan ini menjadi dasar tindak lanjut akademik mahasiswa." icon={<MessageSquareText size={18} />} footer={<><button onClick={() => setNoteOpen(false)} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600">Batal</button><button onClick={submitNote} disabled={noteForm.processing} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">Simpan catatan</button></>}><div className="space-y-4"><Field label="Mahasiswa"><select value={noteForm.data.student_id} onChange={(e) => noteForm.setData('student_id', Number(e.target.value))} className="input">{students.map((item) => <option key={item.id} value={item.id}>{item.user?.name} · {item.nim}</option>)}</select></Field><Field label="Judul"><input value={noteForm.data.title} onChange={(e) => noteForm.setData('title', e.target.value)} className="input" /></Field><Field label="Isi catatan"><textarea value={noteForm.data.content} onChange={(e) => noteForm.setData('content', e.target.value)} className="input min-h-36" /></Field><Field label="Tindak lanjut"><select value={noteForm.data.follow_up_status} onChange={(e) => noteForm.setData('follow_up_status', e.target.value)} className="input"><option value="none">Tidak ada</option><option value="pending">Perlu ditindaklanjuti</option><option value="completed">Selesai</option></select></Field></div></ModalForm>
    <div className="grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Ketersediaan dosen</h2><p className="text-xs text-slate-500">Slot konsultasi yang bisa dipilih mahasiswa.</p></div>{mode === 'manager' && abilities.manage && <button onClick={() => setAvailabilityOpen(true)} className="rounded-xl bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700"><Plus size={14} /></button>}</div><div className="space-y-2">{availability.length ? availability.map((slot) => <div key={slot.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-xs"><span className="font-bold text-slate-700">{weekdayLabels[slot.weekday - 1]}</span><span className="text-slate-500">{slot.starts_at.slice(0, 5)}–{slot.ends_at.slice(0, 5)} · {slot.mode === 'online' ? 'Daring' : 'Luring'}</span></div>) : <Empty text="Belum ada slot ketersediaan." />}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Rencana intervensi</h2><p className="text-xs text-slate-500">Ubah sinyal risiko menjadi langkah tindak lanjut yang jelas.</p></div>{abilities.manage && <button onClick={() => openIntervention()} className="rounded-xl bg-indigo-600 px-3 py-2 text-xs font-bold text-white"><Plus size={14} /></button>}</div><div className="grid gap-3 md:grid-cols-2">{interventions.length ? interventions.map((item) => <article key={item.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-start justify-between gap-2"><div><h3 className="text-sm font-bold text-slate-900">{item.title}</h3><p className="mt-1 text-xs text-slate-500">{item.student.user?.name} · {item.student.nim}</p></div><span className="rounded-full bg-indigo-50 px-2 py-1 text-[10px] font-bold text-indigo-700">{item.status}</span></div><p className="mt-2 line-clamp-2 text-xs text-slate-600">{item.action_plan}</p>{item.due_on && <p className="mt-2 text-[11px] font-semibold text-amber-600">Target: {new Date(item.due_on).toLocaleDateString('id-ID')}</p>}{abilities.manage && item.status !== 'completed' && <button onClick={() => updateIntervention(item, 'completed')} className="mt-3 rounded-lg bg-emerald-600 px-2.5 py-1.5 text-[11px] font-bold text-white">Tandai selesai</button>}</article>) : <Empty text="Belum ada rencana intervensi." />}</div></section></div>
    <ModalForm open={availabilityOpen} onClose={() => setAvailabilityOpen(false)} title="Tambah ketersediaan dosen" description="Slot ini akan ditampilkan sebagai waktu konsultasi." icon={<CalendarClock size={18} />} footer={<><button onClick={() => setAvailabilityOpen(false)} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600">Batal</button><button onClick={submitAvailability} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">Simpan</button></>}><div className="space-y-4"><Field label="Hari"><select value={availabilityForm.data.weekday} onChange={(e) => availabilityForm.setData('weekday', Number(e.target.value))} className="input">{weekdayLabels.map((day, index) => <option key={day} value={index + 1}>{day}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Mulai"><input type="time" value={availabilityForm.data.starts_at} onChange={(e) => availabilityForm.setData('starts_at', e.target.value)} className="input" /></Field><Field label="Selesai"><input type="time" value={availabilityForm.data.ends_at} onChange={(e) => availabilityForm.setData('ends_at', e.target.value)} className="input" /></Field></div><Field label="Mode"><select value={availabilityForm.data.mode} onChange={(e) => availabilityForm.setData('mode', e.target.value)} className="input"><option value="online">Daring</option><option value="onsite">Luring</option><option value="phone">Telepon</option></select></Field></div></ModalForm>
    <ModalForm open={interventionOpen} onClose={() => setInterventionOpen(false)} title="Buat rencana intervensi" description="Tentukan aksi dan tenggat tindak lanjut." icon={<ShieldAlert size={18} />} footer={<><button onClick={() => setInterventionOpen(false)} className="rounded-xl border px-4 py-2 text-sm font-bold text-slate-600">Batal</button><button onClick={submitIntervention} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white">Simpan rencana</button></>}><div className="space-y-4"><Field label="Mahasiswa"><select value={interventionForm.data.student_id} onChange={(e) => interventionForm.setData('student_id', Number(e.target.value))} className="input">{students.map((item) => <option key={item.id} value={item.id}>{item.user?.name} · {item.nim}</option>)}</select></Field><Field label="Judul"><input value={interventionForm.data.title} onChange={(e) => interventionForm.setData('title', e.target.value)} className="input" /></Field><Field label="Rencana aksi"><textarea value={interventionForm.data.action_plan} onChange={(e) => interventionForm.setData('action_plan', e.target.value)} className="input min-h-32" /></Field><Field label="Target tanggal"><input type="date" value={interventionForm.data.due_on} onChange={(e) => interventionForm.setData('due_on', e.target.value)} className="input" /></Field></div></ModalForm>
  </div></DashboardLayout>;
}
function Empty({ text }: { text: string }) { return <div className="col-span-full flex items-center gap-2 rounded-xl border border-dashed border-slate-200 p-5 text-sm text-slate-400"><CheckCircle2 size={17} /> {text}</div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm font-semibold text-slate-700">{label}<div className="mt-1">{children}</div></label>; }
