import { Head, router, useForm } from '@inertiajs/react';
import { AlertTriangle, Archive, CalendarClock, Check, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, FileSpreadsheet, Pencil, Plus, RotateCcw, Search, Trash2, Upload, UserRoundCheck, UsersRound, X } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Page<T> = { data: T[]; current_page: number; last_page: number; total: number };
type Program = { id: number; name: string; code: string };
type Term = { id: number; name: string; code: string; is_active: boolean };
type UserOption = { id: number; name: string; email: string };
type Course = { id: number; program_id: number; name: string; code: string; credits: number; program: Program };
type Room = { id: number; name: string; code: string; capacity: number; building: { id: number; name: string } };
type Lecturer = { id: number; user_id: number | null; program_id: number; name: string; nidn: string; employee_number: string | null; academic_title: string | null; employment_status: string; expertise: string | null; is_active: boolean; deleted_at: string | null; program: Program; user: UserOption | null; class_groups_count: number };
type Schedule = { id: number; academic_term_id: number; course_id: number; lecturer_id: number; room_id: number; name: string; capacity: number; enrolled_count: number; day: string; starts_at: string; ends_at: string; is_active: boolean; deleted_at: string | null; academic_term: Term; course: Course; lecturer: Pick<Lecturer, 'id' | 'name' | 'nidn'>; assigned_room: Room };
type Resource = 'lecturers' | 'schedules';
type Filters = { q: string; program_id: string; academic_term_id: string; status: 'available' | 'archived' };
type ImportRow = { line: number; values: Record<string, string>; action: 'create' | 'update'; errors: Record<string, string[]> };
type ImportPreview = { token: string; file_name: string; total_rows: number; valid_rows: number; error_rows: number; rows: ImportRow[] };
type Props = { filters: Filters; lecturers: Page<Lecturer>; schedules: Page<Schedule>; programOptions: Program[]; termOptions: Term[]; courseOptions: Course[]; lecturerOptions: Pick<Lecturer, 'id' | 'name' | 'nidn'>[]; roomOptions: Room[]; userOptions: UserOption[]; summary: { lecturers: number; schedules: number; active_term_schedules: number; weekly_capacity: number; archived: number }; abilities: Record<Resource, { create: boolean; update: boolean; delete: boolean }>; lecturerTransferAbility: { import: boolean; export: boolean }; importPreview: ImportPreview | null };
type LecturerForm = { user_id: string; program_id: string; name: string; nidn: string; employee_number: string; academic_title: string; employment_status: string; expertise: string; is_active: boolean };
type ScheduleForm = { academic_term_id: string; course_id: string; lecturer_id: string; room_id: string; name: string; capacity: number; day: string; starts_at: string; ends_at: string; is_active: boolean };

const initialLecturer: LecturerForm = { user_id: '', program_id: '', name: '', nidn: '', employee_number: '', academic_title: '', employment_status: 'Tetap', expertise: '', is_active: true };
const initialSchedule: ScheduleForm = { academic_term_id: '', course_id: '', lecturer_id: '', room_id: '', name: 'A', capacity: 30, day: 'Senin', starts_at: '08:00', ends_at: '09:40', is_active: true };
const days = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu'];

export default function AcademicSchedules({ filters, lecturers, schedules, programOptions, termOptions, courseOptions, lecturerOptions, roomOptions, userOptions, summary, abilities, lecturerTransferAbility, importPreview }: Props) {
  const [resource, setResource] = useState<Resource>('schedules');
  const [editing, setEditing] = useState<{ resource: Resource; id: number } | null>(null);
  const [filterData, setFilterData] = useState(filters);
  const lecturerForm = useForm<LecturerForm>(initialLecturer);
  const scheduleForm = useForm<ScheduleForm>(initialSchedule);
  const importForm = useForm<{ file: File | null }>({ file: null });
  const confirmForm = useForm({});
  const [selectedLecturers, setSelectedLecturers] = useState<number[]>([]);

  function resetForms() { setEditing(null); lecturerForm.reset(); scheduleForm.reset(); lecturerForm.clearErrors(); scheduleForm.clearErrors(); }
  function selectResource(next: Resource) { setResource(next); resetForms(); }

  function submitLecturer(event: FormEvent) {
    event.preventDefault();
    const options = { preserveScroll: true, onSuccess: resetForms };
    if (editing?.resource === 'lecturers') { lecturerForm.patch(`/admin/lecturers/${editing.id}`, options); return; }
    lecturerForm.post('/admin/lecturers', options);
  }

  function submitSchedule(event: FormEvent) {
    event.preventDefault();
    const options = { preserveScroll: true, onSuccess: resetForms };
    if (editing?.resource === 'schedules') { scheduleForm.patch(`/admin/schedules/${editing.id}`, options); return; }
    scheduleForm.post('/admin/schedules', options);
  }

  function editLecturer(item: Lecturer) {
    setResource('lecturers'); setEditing({ resource: 'lecturers', id: item.id });
    lecturerForm.setData({ user_id: item.user_id ? String(item.user_id) : '', program_id: String(item.program_id), name: item.name, nidn: item.nidn, employee_number: item.employee_number ?? '', academic_title: item.academic_title ?? '', employment_status: item.employment_status, expertise: item.expertise ?? '', is_active: item.is_active });
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  function editSchedule(item: Schedule) {
    setResource('schedules'); setEditing({ resource: 'schedules', id: item.id });
    scheduleForm.setData({ academic_term_id: String(item.academic_term_id), course_id: String(item.course_id), lecturer_id: String(item.lecturer_id), room_id: String(item.room_id), name: item.name, capacity: item.capacity, day: item.day, starts_at: item.starts_at.slice(0, 5), ends_at: item.ends_at.slice(0, 5), is_active: item.is_active });
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  function applyFilters(event: FormEvent) { event.preventDefault(); setSelectedLecturers([]); router.get('/admin/academic-schedules', filterData, { preserveState: true, replace: true }); }
  function paginate(target: Resource, page: number) { if (target === 'lecturers') setSelectedLecturers([]); router.get('/admin/academic-schedules', { ...filterData, [target === 'lecturers' ? 'lecturers_page' : 'schedules_page']: page }, { preserveState: true, replace: true }); }
  function previewImport(event: FormEvent) { event.preventDefault(); importForm.post('/admin/lecturers/import/preview', { forceFormData: true, preserveScroll: true }); }
  function confirmImport() { if (importPreview) confirmForm.post(`/admin/lecturers/imports/${importPreview.token}/confirm`, { preserveScroll: true }); }
  function cancelImport() { if (importPreview) router.delete(`/admin/lecturers/imports/${importPreview.token}`, { preserveScroll: true }); }
  function toggleLecturer(id: number) { setSelectedLecturers((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  function bulkLecturers() { const action = filterData.status === 'archived' ? 'restore' : 'archive'; if (!selectedLecturers.length || !window.confirm(`${action === 'restore' ? 'Pulihkan' : 'Arsipkan'} ${selectedLecturers.length} dosen?`)) return; router.post('/admin/lecturers/bulk', { action, ids: selectedLecturers }, { preserveScroll: true, onSuccess: () => setSelectedLecturers([]) }); }
  function archive(target: Resource, id: number, label: string) { if (window.confirm(`Arsipkan ${label}?`)) router.delete(`/admin/${target}/${id}`, { preserveScroll: true }); }
  function restore(target: Resource, id: number) { router.patch(`/admin/${target}/${id}/restore`, {}, { preserveScroll: true }); }
  const canForm = abilities[resource].create || editing !== null;

  return <DashboardLayout>
    <Head title="Dosen & Jadwal" />
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-medium text-teal-600">Operasional akademik</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">Dosen & Jadwal.</h1><p className="mt-2 text-sm text-slate-500">Kelola pengampu, kelas, ruangan, kapasitas, dan waktu kuliah tanpa bentrok.</p></div><div className="flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-slate-600 ring-1 ring-slate-200"><Archive size={16} className="text-teal-600" /> {summary.archived} data dalam arsip</div></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={<UserRoundCheck size={18} />} label="Dosen tersedia" value={summary.lecturers} /><Summary icon={<CalendarClock size={18} />} label="Jadwal tersedia" value={summary.schedules} /><Summary icon={<Clock3 size={18} />} label="Jadwal periode aktif" value={summary.active_term_schedules} /><Summary icon={<UsersRound size={18} />} label="Kapasitas mingguan" value={summary.weekly_capacity} /></div>

    <section className="mt-6 rounded-2xl bg-white p-5 ring-1 ring-slate-200/80"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-teal-50 text-teal-600"><FileSpreadsheet size={18} /></div><div><h2 className="text-sm font-semibold text-slate-900">Transfer CSV dosen</h2><p className="mt-1 text-xs text-slate-400">Prodi memakai kode, akun opsional memakai email aktif, dan NIDN menjadi identitas upsert.</p></div></div><div className="flex gap-2">{lecturerTransferAbility.export && <a href="/admin/lecturers/template" className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-semibold text-slate-600 ring-1 ring-slate-200"><FileSpreadsheet size={15} /> Template</a>}{lecturerTransferAbility.export && <a href="/admin/lecturers/export" className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-semibold text-slate-600 ring-1 ring-slate-200"><Download size={15} /> Export</a>}</div></div><form onSubmit={previewImport} className="mt-5 flex min-w-0 gap-2"><input required type="file" accept=".csv,text/csv" onChange={(event) => importForm.setData('file', event.target.files?.[0] ?? null)} className="min-w-0 flex-1 rounded-xl bg-slate-50 px-3 py-2 text-xs text-slate-500 ring-1 ring-slate-200 file:mr-3 file:rounded-lg file:border-0 file:bg-slate-900 file:px-3 file:py-1.5 file:text-xs file:font-semibold file:text-white" /><button disabled={!lecturerTransferAbility.import || importForm.processing} className="flex items-center gap-2 rounded-xl bg-teal-600 px-4 text-xs font-semibold text-white disabled:opacity-40"><Upload size={15} /> Preview</button></form>{importForm.errors.file && <p className="mt-3 text-xs text-rose-600">{importForm.errors.file}</p>}</section>

    {importPreview && <section className="mt-6 overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200/80"><div className="flex flex-col gap-4 border-b border-slate-100 p-5 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2">{importPreview.error_rows ? <AlertTriangle size={18} className="text-amber-500" /> : <CheckCircle2 size={18} className="text-emerald-500" />}<h2 className="font-semibold text-slate-900">Preview dosen</h2></div><p className="mt-1 text-xs text-slate-400">{importPreview.file_name} · {importPreview.valid_rows} valid · {importPreview.error_rows} bermasalah</p></div><div className="flex gap-2"><button onClick={cancelImport} className="rounded-xl px-4 py-2.5 text-xs font-semibold text-slate-500 ring-1 ring-slate-200">Batalkan</button><button onClick={confirmImport} disabled={importPreview.error_rows > 0 || confirmForm.processing} className="rounded-xl bg-[#071827] px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-40">Konfirmasi impor</button></div></div>{(confirmForm.errors as Record<string, string>).import && <p className="bg-rose-50 px-5 py-3 text-xs text-rose-600">{(confirmForm.errors as Record<string, string>).import}</p>}<div className="max-h-[380px] overflow-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">Baris</th><th className="px-4 py-3">NIDN</th><th className="px-4 py-3">Nama</th><th className="px-4 py-3">Aksi</th><th className="px-4 py-3">Validasi</th></tr></thead><tbody className="divide-y divide-slate-100">{importPreview.rows.map((row) => { const errors = Object.values(row.errors).flat(); return <tr key={row.line} className={errors.length ? 'bg-rose-50/40' : ''}><td className="px-4 py-3">{row.line}</td><td className="px-4 py-3 font-semibold text-teal-700">{row.values.nidn || '—'}</td><td className="px-4 py-3">{row.values.name || '—'}</td><td className="px-4 py-3">{row.action === 'create' ? 'Buat' : 'Perbarui'}</td><td className="px-4 py-3">{errors.length ? <ul className="space-y-1 text-rose-600">{errors.map((error, index) => <li key={`${error}-${index}`}>{error}</li>)}</ul> : <span className="text-emerald-600">Siap diimpor</span>}</td></tr>; })}</tbody></table></div></section>}

    <div className="mt-6 grid gap-6 xl:grid-cols-[.72fr_1.28fr]">
      <section className="h-fit rounded-2xl bg-white p-6 ring-1 ring-slate-200/80">
        <div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-teal-50 text-teal-600">{editing ? <Pencil size={18} /> : <Plus size={18} />}</div><div className="min-w-0 flex-1"><h2 className="font-semibold text-slate-950">{editing ? 'Edit data' : 'Tambah data'}</h2><p className="text-xs text-slate-400">Semua perubahan dicatat pada audit log.</p></div>{editing && <button onClick={resetForms} className="rounded-lg p-2 text-slate-400"><X size={16} /></button>}</div>
        {!editing && <div className="mt-6 flex gap-2">{(['schedules', 'lecturers'] as Resource[]).map((item) => <button key={item} onClick={() => selectResource(item)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${resource === item ? 'border-teal-300 bg-teal-50 text-teal-700' : 'border-slate-200 text-slate-400'}`}>{item === 'schedules' ? 'Jadwal' : 'Dosen'}</button>)}</div>}
        {!canForm ? <p className="mt-6 rounded-xl bg-amber-50 p-4 text-xs text-amber-700">Anda memiliki akses lihat tanpa izin membuat data.</p> : resource === 'lecturers' ? <form onSubmit={submitLecturer} className="mt-6 space-y-4">
          <Field label="Program studi"><select required value={lecturerForm.data.program_id} onChange={(e) => lecturerForm.setData('program_id', e.target.value)} className="input"><option value="">Pilih prodi</option>{programOptions.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></Field>
          <Field label="Nama dosen"><input required value={lecturerForm.data.name} onChange={(e) => lecturerForm.setData('name', e.target.value)} className="input" placeholder="Nama lengkap dosen" /></Field>
          <div className="grid gap-4 sm:grid-cols-2"><Field label="NIDN"><input required value={lecturerForm.data.nidn} onChange={(e) => lecturerForm.setData('nidn', e.target.value.toUpperCase())} className="input" /></Field><Field label="Nomor pegawai"><input value={lecturerForm.data.employee_number} onChange={(e) => lecturerForm.setData('employee_number', e.target.value.toUpperCase())} className="input" /></Field></div>
          <div className="grid gap-4 sm:grid-cols-2"><Field label="Jabatan akademik"><input value={lecturerForm.data.academic_title} onChange={(e) => lecturerForm.setData('academic_title', e.target.value)} className="input" placeholder="Lektor" /></Field><Field label="Status"><select value={lecturerForm.data.employment_status} onChange={(e) => lecturerForm.setData('employment_status', e.target.value)} className="input"><option>Tetap</option><option>Tidak Tetap</option></select></Field></div>
          <Field label="Bidang keahlian"><input value={lecturerForm.data.expertise} onChange={(e) => lecturerForm.setData('expertise', e.target.value)} className="input" /></Field>
          <Field label="Tautkan akun"><select value={lecturerForm.data.user_id} onChange={(e) => lecturerForm.setData('user_id', e.target.value)} className="input"><option value="">Tanpa akun</option>{userOptions.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.email}</option>)}</select></Field>
          <Active checked={lecturerForm.data.is_active} onChange={(value) => lecturerForm.setData('is_active', value)} /><Errors errors={lecturerForm.errors} /><Submit processing={lecturerForm.processing} editing={Boolean(editing)} />
        </form> : <form onSubmit={submitSchedule} className="mt-6 space-y-4">
          <Field label="Periode akademik"><select required value={scheduleForm.data.academic_term_id} onChange={(e) => scheduleForm.setData('academic_term_id', e.target.value)} className="input"><option value="">Pilih periode</option>{termOptions.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}{item.is_active ? ' (aktif)' : ''}</option>)}</select></Field>
          <Field label="Mata kuliah"><select required value={scheduleForm.data.course_id} onChange={(e) => scheduleForm.setData('course_id', e.target.value)} className="input"><option value="">Pilih mata kuliah</option>{courseOptions.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name} · {item.program.code}</option>)}</select></Field>
          <div className="grid gap-4 sm:grid-cols-2"><Field label="Kelas"><input required value={scheduleForm.data.name} onChange={(e) => scheduleForm.setData('name', e.target.value.toUpperCase())} className="input" placeholder="A" /></Field><Field label="Kapasitas"><input required type="number" min="1" value={scheduleForm.data.capacity} onChange={(e) => scheduleForm.setData('capacity', Number(e.target.value))} className="input" /></Field></div>
          <Field label="Dosen pengampu"><select required value={scheduleForm.data.lecturer_id} onChange={(e) => scheduleForm.setData('lecturer_id', e.target.value)} className="input"><option value="">Pilih dosen</option>{lecturerOptions.map((item) => <option key={item.id} value={item.id}>{item.nidn} · {item.name}</option>)}</select></Field>
          <Field label="Ruangan"><select required value={scheduleForm.data.room_id} onChange={(e) => { const room = roomOptions.find((item) => item.id === Number(e.target.value)); scheduleForm.setData((data) => ({ ...data, room_id: e.target.value, capacity: room ? Math.min(data.capacity, room.capacity) : data.capacity })); }} className="input"><option value="">Pilih ruangan</option>{roomOptions.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name} · {item.building.name} ({item.capacity})</option>)}</select></Field>
          <div className="grid gap-4 sm:grid-cols-3"><Field label="Hari"><select value={scheduleForm.data.day} onChange={(e) => scheduleForm.setData('day', e.target.value)} className="input">{days.map((day) => <option key={day}>{day}</option>)}</select></Field><Field label="Mulai"><input required type="time" value={scheduleForm.data.starts_at} onChange={(e) => scheduleForm.setData('starts_at', e.target.value)} className="input" /></Field><Field label="Selesai"><input required type="time" value={scheduleForm.data.ends_at} onChange={(e) => scheduleForm.setData('ends_at', e.target.value)} className="input" /></Field></div>
          <Active checked={scheduleForm.data.is_active} onChange={(value) => scheduleForm.setData('is_active', value)} /><Errors errors={scheduleForm.errors} /><Submit processing={scheduleForm.processing} editing={Boolean(editing)} />
        </form>}
      </section>

      <section className="min-w-0">
        <form onSubmit={applyFilters} className="mb-4 grid gap-3 rounded-2xl bg-white p-4 ring-1 ring-slate-200/80 md:grid-cols-2 xl:grid-cols-4"><label className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={filterData.q} onChange={(e) => setFilterData({ ...filterData, q: e.target.value })} className="input pl-9" placeholder="Cari data" /></label><select value={filterData.program_id} onChange={(e) => setFilterData({ ...filterData, program_id: e.target.value })} className="input"><option value="">Semua prodi</option>{programOptions.map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</select><select value={filterData.academic_term_id} onChange={(e) => setFilterData({ ...filterData, academic_term_id: e.target.value })} className="input"><option value="">Semua periode</option>{termOptions.map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</select><div className="flex gap-2"><select value={filterData.status} onChange={(e) => setFilterData({ ...filterData, status: e.target.value as Filters['status'] })} className="input"><option value="available">Tersedia</option><option value="archived">Arsip</option></select><button className="rounded-xl bg-teal-600 px-4 text-white"><Search size={16} /></button></div></form>
        <BulkSelector items={lecturers.data} selected={selectedLecturers} enabled={filterData.status === 'archived' ? abilities.lecturers.update : abilities.lecturers.delete} action={filterData.status === 'archived' ? 'Pulihkan' : 'Arsipkan'} onToggle={toggleLecturer} onSubmit={bulkLecturers} />
        <div className="grid gap-4 md:grid-cols-2">
          <DataSection title="Dosen" page={lecturers} abilities={abilities.lecturers} onPage={(page) => paginate('lecturers', page)} onEdit={editLecturer} onArchive={(item) => archive('lecturers', item.id, item.name)} onRestore={(item) => restore('lecturers', item.id)} titleOf={(item) => item.name} codeOf={(item) => item.nidn} details={(item) => <><Row label="Prodi" value={item.program.name} /><Row label="Status" value={`${item.employment_status} · ${item.class_groups_count} jadwal`} />{item.expertise && <Row label="Keahlian" value={item.expertise} />}</>} />
          <DataSection title="Jadwal kuliah" page={schedules} abilities={abilities.schedules} onPage={(page) => paginate('schedules', page)} onEdit={editSchedule} onArchive={(item) => archive('schedules', item.id, `${item.course.code} ${item.name}`)} onRestore={(item) => restore('schedules', item.id)} titleOf={(item) => `${item.course.code} · Kelas ${item.name}`} codeOf={(item) => item.academic_term.code} details={(item) => <><Row label="Waktu" value={`${item.day}, ${item.starts_at.slice(0, 5)}–${item.ends_at.slice(0, 5)}`} /><Row label="Dosen" value={item.lecturer.name} /><Row label="Ruang" value={`${item.assigned_room.code} · ${item.assigned_room.building.name}`} /><Row label="Kapasitas" value={`${item.enrolled_count}/${item.capacity}`} /></>} />
        </div>
      </section>
    </div>
  </DashboardLayout>;
}

function Summary({ icon, label, value }: { icon: ReactNode; label: string; value: number }) { return <div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200/80"><div className="flex items-center justify-between"><span className="text-teal-600">{icon}</span><span className="text-2xl font-semibold text-slate-950">{value.toLocaleString('id-ID')}</span></div><p className="mt-3 text-xs font-medium text-slate-500">{label}</p></div>; }
function BulkSelector({ items, selected, enabled, action, onToggle, onSubmit }: { items: Lecturer[]; selected: number[]; enabled: boolean; action: string; onToggle: (id: number) => void; onSubmit: () => void }) { if (!enabled || items.length === 0) return null; return <div className="mb-4 rounded-2xl bg-white p-4 ring-1 ring-slate-200/80"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-slate-700">Bulk dosen pada halaman ini</p><button disabled={selected.length === 0} onClick={onSubmit} className="rounded-lg bg-slate-900 px-3 py-1.5 text-[10px] font-semibold text-white disabled:opacity-30">{action} {selected.length || ''}</button></div><div className="mt-3 flex max-h-24 flex-wrap gap-2 overflow-auto">{items.map((item) => <label key={item.id} className={`flex cursor-pointer items-center gap-2 rounded-lg px-2.5 py-1.5 text-[10px] ring-1 ${selected.includes(item.id) ? 'bg-teal-50 text-teal-700 ring-teal-200' : 'text-slate-500 ring-slate-200'}`}><input type="checkbox" checked={selected.includes(item.id)} onChange={() => onToggle(item.id)} />{item.nidn} · {item.name}</label>)}</div></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
function Active({ checked, onChange }: { checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-2 text-xs font-semibold text-slate-600"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /> Data aktif</label>; }
function Errors({ errors }: { errors: Partial<Record<string, string>> }) { return <>{Object.values(errors).map((error, index) => <p key={`${error}-${index}`} className="text-xs text-rose-600">{error}</p>)}</>; }
function Submit({ processing, editing }: { processing: boolean; editing: boolean }) { return <button disabled={processing} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#071827] py-3 font-semibold text-white disabled:opacity-60">{processing ? 'Menyimpan...' : editing ? 'Perbarui data' : 'Simpan data'} <Check size={16} /></button>; }
function Row({ label, value }: { label: string; value: string }) { return <p><span className="text-slate-400">{label}:</span> {value}</p>; }

function DataSection<T extends { id: number; deleted_at: string | null }>({ title, page, abilities, titleOf, codeOf, details, onPage, onEdit, onArchive, onRestore }: { title: string; page: Page<T>; abilities: { update: boolean; delete: boolean }; titleOf: (item: T) => string; codeOf: (item: T) => string; details: (item: T) => ReactNode; onPage: (page: number) => void; onEdit: (item: T) => void; onArchive: (item: T) => void; onRestore: (item: T) => void }) {
  return <div className="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200/80"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h3 className="text-sm font-semibold text-slate-800">{title}</h3><span className="text-xs text-slate-400">{page.total} data</span></div><div className="divide-y divide-slate-100">{page.data.map((item) => <div key={item.id} className="group px-5 py-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-800">{titleOf(item)}</p><p className="mt-0.5 text-[11px] font-semibold uppercase tracking-wide text-teal-600">{codeOf(item)}</p><div className="mt-2 space-y-1 text-xs text-slate-400">{details(item)}</div></div><div className="flex gap-1">{item.deleted_at ? abilities.update && <button onClick={() => onRestore(item)} className="rounded-lg p-2 text-slate-300 hover:text-teal-600"><RotateCcw size={14} /></button> : <>{abilities.update && <button onClick={() => onEdit(item)} className="rounded-lg p-2 text-slate-300 hover:text-teal-600"><Pencil size={14} /></button>}{abilities.delete && <button onClick={() => onArchive(item)} className="rounded-lg p-2 text-slate-300 hover:text-rose-600"><Trash2 size={14} /></button>}</>}</div></div></div>)}{page.data.length === 0 && <p className="p-8 text-center text-xs text-slate-400">Tidak ada data ditemukan.</p>}</div><div className="flex items-center justify-between border-t border-slate-100 px-5 py-3 text-xs text-slate-400"><span>Halaman {page.current_page} / {page.last_page}</span><div className="flex gap-1"><button onClick={() => onPage(page.current_page - 1)} disabled={page.current_page <= 1} className="rounded-lg p-1.5 disabled:opacity-30"><ChevronLeft size={14} /></button><button onClick={() => onPage(page.current_page + 1)} disabled={page.current_page >= page.last_page} className="rounded-lg p-1.5 disabled:opacity-30"><ChevronRight size={14} /></button></div></div></div>;
}
