import { Head, router } from '@inertiajs/react';
import { Activity, CalendarDays, ChevronRight, Database, Download, Eye, FileClock, Search, ShieldCheck, UserRound } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { ModalForm } from '@/components/ModalForm';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Log = { id: number; module: string; action: string; record_type: string | null; record_id: string | null; old_data: Record<string, unknown> | null; new_data: Record<string, unknown> | null; ip_address: string | null; created_at: string; user: { name: string; email: string } | null };
type Props = { logs: { data: Log[]; total: number; current_page: number; last_page: number }; filters: { q: string; module: string; action: string; date_from: string; date_to: string }; modules: string[]; summary: { today: number; week: number; users: number; modules: number } };

export default function AuditLogs({ logs, filters: initial, modules, summary }: Props) {
  const [filters, setFilters] = useState(initial); const [selected, setSelected] = useState<Log | null>(null);
  function filter(event: FormEvent) { event.preventDefault(); router.get('/admin/audit-logs', filters, { replace: true, preserveState: false }); }
  const exportUrl = `/admin/audit-logs/export?${new URLSearchParams(filters).toString()}`;
  return <DashboardLayout><Head title="Audit Trail" />
    <header className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="flex items-center gap-2 text-sm font-semibold text-violet-600"><ShieldCheck size={16} /> Security & accountability</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">Audit trail sistem.</h1><p className="mt-2 text-sm text-slate-500">Telusuri perubahan penting dengan identitas pelaku, waktu, modul, dan konteks data.</p></div><a href={exportUrl} className="action-secondary"><Download size={15} /> Ekspor CSV</a></header>
    <div className="mt-7 grid gap-4 sm:grid-cols-4"><Metric icon={<Activity size={18} />} label="Hari ini" value={summary.today} tone="violet" /><Metric icon={<CalendarDays size={18} />} label="7 hari" value={summary.week} tone="blue" /><Metric icon={<UserRound size={18} />} label="Pelaku" value={summary.users} tone="green" /><Metric icon={<Database size={18} />} label="Modul" value={summary.modules} tone="amber" /></div>
    <form onSubmit={filter} className="mt-6 grid gap-3 rounded-2xl bg-white p-4 ring-1 ring-slate-200 lg:grid-cols-[1fr_180px_180px_150px_150px_auto]"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input className="input pl-9" value={filters.q} onChange={(e) => setFilters({ ...filters, q: e.target.value })} placeholder="Cari aksi, data, pengguna..." /></div><select className="input" value={filters.module} onChange={(e) => setFilters({ ...filters, module: e.target.value })}><option value="">Semua modul</option>{modules.map((module) => <option key={module}>{module}</option>)}</select><input className="input" value={filters.action} onChange={(e) => setFilters({ ...filters, action: e.target.value })} placeholder="Aksi..." /><input type="date" className="input" value={filters.date_from} onChange={(e) => setFilters({ ...filters, date_from: e.target.value })} /><input type="date" className="input" value={filters.date_to} onChange={(e) => setFilters({ ...filters, date_to: e.target.value })} /><button className="rounded-xl bg-slate-950 px-5 text-xs font-semibold text-white">Terapkan</button></form>
    <section className="mt-5 overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200"><div className="divide-y divide-slate-100">{logs.data.map((log) => <button key={log.id} onClick={() => setSelected(log)} className="flex w-full flex-col justify-between gap-4 p-4 text-left hover:bg-slate-50 sm:flex-row sm:items-center"><div className="flex min-w-0 items-center gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-violet-50 text-violet-600"><FileClock size={18} /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-lg bg-slate-100 px-2 py-1 text-[9px] font-bold uppercase text-slate-600">{log.module}</span><p className="text-sm font-semibold text-slate-800">{humanize(log.action)}</p></div><p className="mt-1 truncate text-[10px] text-slate-400">{log.record_type ?? 'system'} #{log.record_id ?? '—'} · {log.ip_address ?? 'internal'}</p></div></div><div className="flex items-center justify-between gap-6 pl-13 sm:pl-0"><div className="sm:text-right"><p className="text-xs font-medium text-slate-600">{log.user?.name ?? 'System'}</p><p className="mt-1 text-[9px] text-slate-400">{formatDate(log.created_at)}</p></div><ChevronRight size={15} className="text-slate-300" /></div></button>)}{!logs.data.length && <div className="p-14 text-center"><Eye size={28} className="mx-auto text-slate-300" /><p className="mt-3 text-sm text-slate-400">Tidak ada aktivitas untuk filter ini.</p></div>}</div></section>
    <ModalForm open={Boolean(selected)} onClose={() => setSelected(null)} title="Detail aktivitas" description={selected ? `${selected.module} · ${humanize(selected.action)} · ${formatDate(selected.created_at)}` : ''} icon={<ShieldCheck size={20} />} size="xl"><div className="grid gap-4 sm:grid-cols-3"><Info label="Pelaku" value={selected?.user?.name ?? 'System'} /><Info label="Record" value={`${selected?.record_type ?? 'system'} #${selected?.record_id ?? '—'}`} /><Info label="IP address" value={selected?.ip_address ?? 'Internal'} /></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><JsonPanel title="Sebelum" data={selected?.old_data ?? null} /><JsonPanel title="Sesudah / payload" data={selected?.new_data ?? null} /></div><p className="mt-4 text-[10px] text-slate-400">Nilai rahasia seperti password, token, signature, dan API key otomatis disamarkan.</p></ModalForm>
  </DashboardLayout>;
}
function Metric({ icon, label, value, tone }: { icon: ReactNode; label: string; value: number; tone: 'violet' | 'blue' | 'green' | 'amber' }) { const colors = { violet: 'bg-violet-50 text-violet-600', blue: 'bg-sky-50 text-sky-600', green: 'bg-emerald-50 text-emerald-600', amber: 'bg-amber-50 text-amber-600' }; return <div className="flex items-center gap-4 rounded-2xl bg-white p-4 ring-1 ring-slate-200"><div className={`flex size-11 items-center justify-center rounded-xl ${colors[tone]}`}>{icon}</div><div><p className="text-xl font-bold text-slate-950">{value}</p><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p></div></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 break-all text-sm font-semibold text-slate-700">{value}</p></div>; }
function JsonPanel({ title, data }: { title: string; data: Record<string, unknown> | null }) { return <section><p className="mb-2 text-xs font-semibold text-slate-600">{title}</p><pre className="modal-scroll max-h-80 overflow-auto rounded-xl bg-slate-950 p-4 text-[11px] leading-5 text-cyan-100">{data ? JSON.stringify(data, null, 2) : 'Tidak ada data.'}</pre></section>; }
function humanize(value: string) { return value.replaceAll('_', ' ').replace(/\b\w/g, (char) => char.toUpperCase()); }
function formatDate(value: string) { return new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'medium' }).format(new Date(value)); }
