import { Head, router, useForm } from '@inertiajs/react';
import { Award, BadgeCheck, CalendarClock, CheckCircle2, ClipboardCheck, GraduationCap, Pencil, Plus, Search, Trash2, UserPlus, Users } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Term = { id: number; name: string; code: string; starts_on: string | null };
type Program = { id: number; name: string; code: string };
type Component = { id: number; name: string; weight: string; max_score: string; sort_order: number };
type Score = { id: number; pmb_selection_component_id: number; score: string };
type Student = { id: number; nim: string; status: string };
type Application = { id: number; registration_number: string; full_name: string; email: string; phone: string; status: string; program: Program | null; invoice: { invoice_number: string; amount: string; paid_amount: string; status: string } | null };
type Result = { id: number; final_score: string | null; decision: 'pending' | 'accepted' | 'rejected'; application: Application; scores: Score[]; student: Student | null };
type Selection = { id: number; academic_term_id: number; program_id: number | null; name: string; starts_at: string; ends_at: string; passing_grade: string; status: 'draft' | 'finalized'; finalized_at: string | null; results_count?: number; academic_term: Term; program: Program | null; components?: Component[]; results?: Result[]; finalized_by?: { name: string } | null };
type ApplicationOption = { id: number; registration_number: string; full_name: string; program: Program | null };
type Page<T> = { data: T[]; current_page: number; last_page: number; total: number };
type SelectionForm = { academic_term_id: string; program_id: string; name: string; starts_at: string; ends_at: string; passing_grade: string };
type Props = { filters: { q: string; status: string; selected: number | null }; selections: Page<Selection>; selectedSelection: Selection | null; termOptions: Term[]; programOptions: Program[]; applicationOptions: ApplicationOption[]; summary: { draft: number; finalized: number; candidates: number; accepted: number }; abilities: { create: boolean; update: boolean; delete: boolean; convert: boolean } };

const initialSelection: SelectionForm = { academic_term_id: '', program_id: '', name: '', starts_at: '', ends_at: '', passing_grade: '60' };

export default function PmbSelectionPage({ filters, selections, selectedSelection, termOptions, programOptions, applicationOptions, summary, abilities }: Props) {
  const [filterData, setFilterData] = useState({ q: filters.q, status: filters.status });
  const [editing, setEditing] = useState(false);
  const form = useForm<SelectionForm>(initialSelection);
  const componentForm = useForm({ name: '', weight: '', max_score: '100', sort_order: 0 });
  const candidateForm = useForm({ pmb_application_id: '' });
  const isDraft = selectedSelection?.status === 'draft';
  const totalWeight = selectedSelection?.components?.reduce((sum, item) => sum + Number(item.weight), 0) ?? 0;

  function submitSelection(event: FormEvent) {
    event.preventDefault();
    if (editing && selectedSelection) form.patch(`/admin/pmb/selection/${selectedSelection.id}`, { preserveScroll: true, onSuccess: resetSelection });
    else form.post('/admin/pmb/selection', { onSuccess: resetSelection });
  }
  function editSelection() {
    if (!selectedSelection) return;
    setEditing(true);
    form.setData({ academic_term_id: String(selectedSelection.academic_term_id), program_id: selectedSelection.program_id ? String(selectedSelection.program_id) : '', name: selectedSelection.name, starts_at: dateTimeLocal(selectedSelection.starts_at), ends_at: dateTimeLocal(selectedSelection.ends_at), passing_grade: selectedSelection.passing_grade });
    form.clearErrors();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
  function resetSelection() { setEditing(false); form.reset(); form.clearErrors(); }
  function applyFilters(event: FormEvent) { event.preventDefault(); router.get('/admin/pmb/selection', filterData, { preserveState: true, replace: true }); }
  function select(id: number) { router.get('/admin/pmb/selection', { ...filterData, selected: id }, { preserveState: true, replace: true }); }
  function addComponent(event: FormEvent) { event.preventDefault(); if (selectedSelection) componentForm.post(`/admin/pmb/selection/${selectedSelection.id}/components`, { preserveScroll: true, onSuccess: () => componentForm.reset() }); }
  function addCandidate(event: FormEvent) { event.preventDefault(); if (selectedSelection) candidateForm.post(`/admin/pmb/selection/${selectedSelection.id}/candidates`, { preserveScroll: true, onSuccess: () => candidateForm.reset() }); }
  function finalize() { if (selectedSelection && window.confirm('Finalisasi seleksi? Nilai dan keputusan seluruh peserta akan dikunci.')) router.post(`/admin/pmb/selection/${selectedSelection.id}/finalize`, {}, { preserveScroll: true }); }

  return <DashboardLayout>
    <Head title="Seleksi PMB" />
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-medium text-teal-600">Penerimaan mahasiswa baru</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">Seleksi dan kelulusan PMB.</h1><p className="mt-2 text-sm text-slate-500">Kelola jadwal, nilai berbobot, passing grade, finalisasi, dan konversi mahasiswa.</p></div><div className="rounded-xl bg-white px-4 py-3 text-sm font-semibold text-slate-600 ring-1 ring-slate-200">Finalisasi bersifat permanen</div></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={<CalendarClock size={18} />} label="Seleksi draft" value={summary.draft} /><Summary icon={<ClipboardCheck size={18} />} label="Difinalisasi" value={summary.finalized} /><Summary icon={<Users size={18} />} label="Total peserta" value={summary.candidates} /><Summary icon={<Award size={18} />} label="Dinyatakan lulus" value={summary.accepted} /></div>

    <div className="mt-6 grid gap-6 xl:grid-cols-[.75fr_1.25fr]">
      <div className="space-y-6">
        {(abilities.create || editing) && <section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><div className="flex items-center justify-between"><SectionTitle icon={editing ? <Pencil size={18} /> : <Plus size={18} />} title={editing ? 'Edit jadwal seleksi' : 'Jadwal seleksi baru'} description="Jadwal dapat mencakup satu prodi atau seluruh prodi." />{editing && <button type="button" onClick={resetSelection} className="text-xs font-semibold text-slate-500">Batal</button>}</div><form onSubmit={submitSelection} className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Periode akademik"><select required value={form.data.academic_term_id} onChange={(e) => form.setData('academic_term_id', e.target.value)} className="input"><option value="">Pilih periode</option>{termOptions.map((item) => <option key={item.id} value={item.id}>{item.code} - {item.name}</option>)}</select></Field><Field label="Program studi"><select value={form.data.program_id} onChange={(e) => form.setData('program_id', e.target.value)} className="input"><option value="">Semua program</option>{programOptions.map((item) => <option key={item.id} value={item.id}>{item.code} - {item.name}</option>)}</select></Field><label className="block sm:col-span-2"><span className="mb-2 block text-xs font-semibold text-slate-600">Nama seleksi</span><input required value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} className="input" placeholder="Tes masuk gelombang 1" /></label><Field label="Mulai"><input required type="datetime-local" value={form.data.starts_at} onChange={(e) => form.setData('starts_at', e.target.value)} className="input" /></Field><Field label="Selesai"><input required type="datetime-local" value={form.data.ends_at} onChange={(e) => form.setData('ends_at', e.target.value)} className="input" /></Field><Field label="Passing grade"><input required type="number" min="0" max="100" step="0.01" value={form.data.passing_grade} onChange={(e) => form.setData('passing_grade', e.target.value)} className="input" /></Field><div className="flex items-end"><button disabled={form.processing} className="w-full rounded-xl bg-teal-600 py-3 text-sm font-semibold text-white disabled:opacity-40">{form.processing ? 'Menyimpan...' : editing ? 'Simpan perubahan' : 'Buat seleksi'}</button></div><div className="sm:col-span-2"><Errors errors={form.errors} /></div></form></section>}

        <section className="rounded-2xl bg-white p-5 ring-1 ring-slate-200/80"><form onSubmit={applyFilters} className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={15} /><input value={filterData.q} onChange={(e) => setFilterData({ ...filterData, q: e.target.value })} className="input pl-9" placeholder="Cari seleksi atau prodi" /></div><select value={filterData.status} onChange={(e) => setFilterData({ ...filterData, status: e.target.value })} className="input w-32"><option value="">Semua</option><option value="draft">Draft</option><option value="finalized">Final</option></select><button className="rounded-xl bg-slate-900 px-4 text-xs font-semibold text-white">Cari</button></form><div className="mt-4 space-y-2">{selections.data.map((item) => <button key={item.id} type="button" onClick={() => select(item.id)} className={`w-full rounded-xl p-4 text-left ring-1 transition ${selectedSelection?.id === item.id ? 'bg-teal-50 ring-teal-200' : 'bg-slate-50 ring-slate-100 hover:ring-slate-300'}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-800">{item.name}</p><p className="mt-1 text-[11px] text-slate-500">{item.academic_term.code} - {item.program ? item.program.code : 'Semua prodi'}</p></div><Status value={item.status} /></div><p className="mt-3 text-[11px] text-slate-400">{formatDate(item.starts_at)} - {item.results_count ?? 0} peserta</p></button>)}{selections.data.length === 0 && <p className="py-8 text-center text-xs text-slate-400">Belum ada jadwal seleksi.</p>}</div>{selections.last_page > 1 && <div className="mt-4 flex justify-between"><button disabled={selections.current_page <= 1} onClick={() => router.get('/admin/pmb/selection', { ...filterData, page: selections.current_page - 1 }, { preserveState: true })} className="text-xs font-semibold text-teal-600 disabled:opacity-30">Sebelumnya</button><span className="text-xs text-slate-400">{selections.current_page}/{selections.last_page}</span><button disabled={selections.current_page >= selections.last_page} onClick={() => router.get('/admin/pmb/selection', { ...filterData, page: selections.current_page + 1 }, { preserveState: true })} className="text-xs font-semibold text-teal-600 disabled:opacity-30">Berikutnya</button></div>}</section>
      </div>

      {!selectedSelection ? <section className="flex min-h-80 items-center justify-center rounded-2xl bg-white p-8 text-center text-sm text-slate-400 ring-1 ring-slate-200/80">Pilih atau buat jadwal seleksi.</section> : <div className="space-y-6">
        <section className="rounded-2xl bg-[#071827] p-7 text-white"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><Status value={selectedSelection.status} dark /><span className="text-xs text-slate-400">{selectedSelection.academic_term.code}</span></div><h2 className="mt-4 text-2xl font-semibold">{selectedSelection.name}</h2><p className="mt-2 text-sm text-slate-300">{selectedSelection.program ? `${selectedSelection.program.code} - ${selectedSelection.program.name}` : 'Seluruh program studi'}</p></div><div className="rounded-2xl bg-white/10 px-5 py-4 text-right"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Passing grade</p><p className="mt-2 text-3xl font-semibold text-teal-200">{Number(selectedSelection.passing_grade).toFixed(2)}</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><DarkInfo label="Mulai" value={formatDateTime(selectedSelection.starts_at)} /><DarkInfo label="Selesai" value={formatDateTime(selectedSelection.ends_at)} /><DarkInfo label="Peserta" value={String(selectedSelection.results?.length ?? 0)} /></div>{isDraft && <div className="mt-5 flex flex-wrap gap-2">{abilities.update && <button onClick={editSelection} className="rounded-xl bg-white/10 px-4 py-2 text-xs font-semibold text-white"><Pencil className="mr-2 inline" size={13} />Edit</button>}{abilities.delete && <button onClick={() => window.confirm('Hapus jadwal dan seluruh data seleksi ini?') && router.delete(`/admin/pmb/selection/${selectedSelection.id}`)} className="rounded-xl bg-rose-500/20 px-4 py-2 text-xs font-semibold text-rose-200"><Trash2 className="mr-2 inline" size={13} />Hapus</button>}</div>}</section>

        <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><SectionTitle icon={<Award size={18} />} title="Komponen nilai" description={`Total bobot ${totalWeight.toFixed(2)}% dari 100%.`} /><div className="mt-5 space-y-2">{selectedSelection.components?.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><p className="text-xs font-semibold text-slate-700">{item.name}</p><p className="mt-1 text-[11px] text-slate-400">Maksimum {Number(item.max_score)} - bobot {Number(item.weight)}%</p></div>{isDraft && abilities.update && <button onClick={() => window.confirm(`Hapus komponen ${item.name}?`) && router.delete(`/admin/pmb/selection/${selectedSelection.id}/components/${item.id}`, { preserveScroll: true })} className="p-2 text-rose-500"><Trash2 size={14} /></button>}</div>)}{!selectedSelection.components?.length && <p className="py-4 text-center text-xs text-slate-400">Belum ada komponen.</p>}</div>{isDraft && abilities.update && <form onSubmit={addComponent} className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Nama"><input required value={componentForm.data.name} onChange={(e) => componentForm.setData('name', e.target.value)} className="input" /></Field><Field label="Bobot %"><input required type="number" min="0.01" max="100" step="0.01" value={componentForm.data.weight} onChange={(e) => componentForm.setData('weight', e.target.value)} className="input" /></Field><Field label="Nilai maksimum"><input required type="number" min="0.01" step="0.01" value={componentForm.data.max_score} onChange={(e) => componentForm.setData('max_score', e.target.value)} className="input" /></Field><div className="flex items-end"><button disabled={componentForm.processing} className="w-full rounded-xl bg-slate-900 py-3 text-xs font-semibold text-white">Tambah komponen</button></div><div className="sm:col-span-2"><Errors errors={componentForm.errors} /></div></form>}</section>

          <section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><SectionTitle icon={<UserPlus size={18} />} title="Peserta seleksi" description="Hanya aplikasi terverifikasi dengan invoice lunas." />{isDraft && abilities.update && <form onSubmit={addCandidate} className="mt-5 space-y-3"><select required value={candidateForm.data.pmb_application_id} onChange={(e) => candidateForm.setData('pmb_application_id', e.target.value)} className="input"><option value="">Pilih calon peserta</option>{applicationOptions.map((item) => <option key={item.id} value={item.id}>{item.registration_number} - {item.full_name} ({item.program?.code ?? '-'})</option>)}</select><Errors errors={candidateForm.errors} /><button disabled={candidateForm.processing || applicationOptions.length === 0} className="w-full rounded-xl bg-teal-600 py-3 text-xs font-semibold text-white disabled:opacity-40">Tambahkan peserta</button></form>}<div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-700">{selectedSelection.results?.length ?? 0} peserta terdaftar</p><p className="mt-1 text-[11px] text-slate-400">{applicationOptions.length} calon memenuhi syarat dan belum dijadwalkan.</p></div></section></div>

        <section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><SectionTitle icon={<BadgeCheck size={18} />} title="Nilai dan hasil peserta" description={isDraft ? 'Simpan seluruh nilai sebelum finalisasi.' : `Difinalisasi ${selectedSelection.finalized_at ? formatDateTime(selectedSelection.finalized_at) : ''}.`} />{isDraft && abilities.update && <button onClick={finalize} disabled={Math.abs(totalWeight - 100) > 0.001 || !selectedSelection.results?.length} className="rounded-xl bg-emerald-600 px-5 py-3 text-xs font-semibold text-white disabled:opacity-40"><CheckCircle2 className="mr-2 inline" size={14} />Finalisasi seleksi</button>}</div><div className="mt-6 space-y-4">{selectedSelection.results?.map((result) => <ResultCard key={result.id} selection={selectedSelection} result={result} components={selectedSelection.components ?? []} editable={Boolean(isDraft && abilities.update)} canConvert={abilities.convert} />)}{!selectedSelection.results?.length && <p className="py-10 text-center text-xs text-slate-400">Belum ada peserta seleksi.</p>}</div></section>
      </div>}
    </div>
  </DashboardLayout>;
}

function ResultCard({ selection, result, components, editable, canConvert }: { selection: Selection; result: Result; components: Component[]; editable: boolean; canConvert: boolean }) {
  const initialScores = Object.fromEntries(components.map((component) => [String(component.id), result.scores.find((score) => score.pmb_selection_component_id === component.id)?.score ?? '']));
  const form = useForm<{ scores: Record<string, string> }>({ scores: initialScores });
  function submit(event: FormEvent) { event.preventDefault(); form.put(`/admin/pmb/selection/${selection.id}/candidates/${result.id}/scores`, { preserveScroll: true }); }
  function setScore(componentId: number, value: string) { form.setData('scores', { ...form.data.scores, [String(componentId)]: value }); }
  return <div className="rounded-2xl bg-slate-50 p-5 ring-1 ring-slate-100"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-slate-800">{result.application.full_name}</p><Decision value={result.decision} /></div><p className="mt-1 font-mono text-[11px] text-teal-700">{result.application.registration_number}</p><p className="mt-1 text-[11px] text-slate-400">{result.application.program?.code ?? '-'} - {result.application.email}</p></div><div className="flex items-center gap-2">{result.final_score !== null && <div className="rounded-xl bg-white px-4 py-2 text-right ring-1 ring-slate-200"><p className="text-[9px] font-bold uppercase text-slate-400">Nilai akhir</p><p className="mt-1 text-lg font-semibold text-slate-800">{Number(result.final_score).toFixed(2)}</p></div>}{editable && <button onClick={() => window.confirm(`Keluarkan ${result.application.full_name}?`) && router.delete(`/admin/pmb/selection/${selection.id}/candidates/${result.id}`, { preserveScroll: true })} className="p-2 text-rose-500"><Trash2 size={15} /></button>}</div></div>{editable && <form onSubmit={submit} className="mt-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{components.map((component) => <Field key={component.id} label={`${component.name} / ${Number(component.max_score)}`}><input required type="number" min="0" max={component.max_score} step="0.01" value={form.data.scores[String(component.id)] ?? ''} onChange={(e) => setScore(component.id, e.target.value)} className="input" /></Field>)}</div><Errors errors={form.errors} />{components.length > 0 && <button disabled={form.processing} className="mt-4 rounded-xl bg-slate-900 px-5 py-2.5 text-xs font-semibold text-white">Simpan nilai</button>}</form>}{!editable && <div className="mt-4 flex flex-wrap gap-2">{components.map((component) => { const score = result.scores.find((item) => item.pmb_selection_component_id === component.id); return <span key={component.id} className="rounded-lg bg-white px-3 py-2 text-[11px] text-slate-600 ring-1 ring-slate-200">{component.name}: <strong>{score ? Number(score.score) : '-'}</strong></span>; })}</div>}{result.student ? <div className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-xs font-semibold text-emerald-700"><GraduationCap size={16} />Mahasiswa aktif - NIM {result.student.nim}</div> : result.decision === 'accepted' && canConvert ? <button onClick={() => window.confirm(`Konversi ${result.application.full_name} menjadi mahasiswa?`) && router.post(`/admin/pmb/selection/${selection.id}/candidates/${result.id}/convert`, {}, { preserveScroll: true })} className="mt-4 rounded-xl bg-teal-600 px-5 py-2.5 text-xs font-semibold text-white"><GraduationCap className="mr-2 inline" size={14} />Konversi menjadi mahasiswa</button> : null}</div>;
}

function Summary({ icon, label, value }: { icon: ReactNode; label: string; value: number }) { return <div className="rounded-2xl bg-white p-5 ring-1 ring-slate-200/80"><div className="flex size-9 items-center justify-center rounded-xl bg-teal-50 text-teal-600">{icon}</div><p className="mt-4 text-2xl font-semibold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-400">{label}</p></div>; }
function SectionTitle({ icon, title, description }: { icon: ReactNode; title: string; description: string }) { return <div className="flex items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-teal-50 text-teal-600">{icon}</div><div><h2 className="font-semibold text-slate-900">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-400">{description}</p></div></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
function Errors({ errors }: { errors: Partial<Record<string, string>> }) { return <div className="mt-2 space-y-1">{Object.values(errors).map((error, index) => <p key={`${error}-${index}`} className="text-xs text-rose-600">{error}</p>)}</div>; }
function Status({ value, dark = false }: { value: Selection['status']; dark?: boolean }) { return <span className={`rounded-full px-2.5 py-1 text-[9px] font-bold uppercase ${value === 'finalized' ? dark ? 'bg-emerald-400/20 text-emerald-200' : 'bg-emerald-50 text-emerald-700' : dark ? 'bg-amber-400/20 text-amber-200' : 'bg-amber-50 text-amber-700'}`}>{value === 'finalized' ? 'Final' : 'Draft'}</span>; }
function Decision({ value }: { value: Result['decision'] }) { const tone = value === 'accepted' ? 'bg-emerald-100 text-emerald-700' : value === 'rejected' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700'; const label = value === 'accepted' ? 'Lulus' : value === 'rejected' ? 'Tidak lulus' : 'Menunggu'; return <span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase ${tone}`}>{label}</span>; }
function DarkInfo({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-white/10 p-4"><p className="text-[9px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-xs font-semibold text-white">{value}</p></div>; }
function dateTimeLocal(value: string) { const date = new Date(value); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
function formatDate(value: string) { return new Date(value).toLocaleDateString('id-ID', { dateStyle: 'medium' }); }
function formatDateTime(value: string) { return new Date(value).toLocaleString('id-ID', { dateStyle: 'medium', timeStyle: 'short' }); }
