import { Head, router, useForm } from '@inertiajs/react';
import { AlertTriangle, ArrowLeft, BadgeCheck, CheckCircle2, Download, FileText, RotateCcw, ShieldCheck, UserRound, XCircle } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Program = { id: number; name: string; code: string; degree: string };
type Document = { id: number; type: string; original_name: string; mime_type: string; size: number; status: 'pending' | 'verified' | 'rejected'; notes: string | null; uploaded_at: string };
type Invoice = { invoice_number: string; amount: string; paid_amount: string; due_at: string | null; status: string; virtual_account: { provider: string; va_number: string; status: string; expires_at: string | null } | null };
type Application = { id: number; registration_number: string; full_name: string; email: string; phone: string; identity_number: string; birth_place: string; birth_date: string; gender: string; address: string; previous_school: string; graduation_year: number; guardian_name: string; guardian_phone: string; registration_path: string; registration_type: string; registration_wave: string | null; status: string; submitted_at: string | null; program: Program | null; documents: Document[]; invoice: Invoice | null };
type Props = { application: Application; documentRequirements: Record<string, string>; abilities: { review: boolean; download: boolean } };

export default function PmbVerification({ application, documentRequirements, abilities }: Props) {
  const [notes, setNotes] = useState<Record<number, string>>(Object.fromEntries(application.documents.map((item) => [item.id, item.notes ?? ''])));
  const actionForm = useForm({});
  const allVerified = Object.keys(documentRequirements).every((type) => application.documents.some((item) => item.type === type && item.status === 'verified'));
  const hasRejected = application.documents.some((item) => item.status === 'rejected');

  function decide(document: Document, status: 'verified' | 'rejected') {
    if (status === 'rejected' && !notes[document.id]?.trim()) { window.alert('Catatan penolakan wajib diisi.'); return; }
    router.patch(`/admin/pmb/applications/${application.id}/documents/${document.id}`, { status, notes: notes[document.id] ?? '' }, { preserveScroll: true });
  }
  function verify() { if (window.confirm('Verifikasi aplikasi dan seluruh dokumen?')) actionForm.post(`/admin/pmb/applications/${application.id}/verify`, { preserveScroll: true }); }
  function returnForCorrection() { if (window.confirm('Kembalikan aplikasi agar pemohon mengganti dokumen yang ditolak?')) actionForm.post(`/admin/pmb/applications/${application.id}/return`, { preserveScroll: true }); }

  return <DashboardLayout>
    <Head title={`Verifikasi ${application.registration_number}`} />
    <a href="/admin/pmb" className="inline-flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-teal-700"><ArrowLeft size={15} /> Kembali ke PMB</a>
    <div className="mt-5 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-medium text-teal-600">Verifikasi pendaftaran</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">{application.full_name}</h1><p className="mt-2 font-mono text-sm text-slate-500">{application.registration_number}</p></div><Status value={application.status} /></div>

    <div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]">
      <div className="space-y-6"><section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><Title icon={<UserRound size={18} />} text="Identitas pemohon" /><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info label="NIK" value={application.identity_number} /><Info label="Email" value={application.email} /><Info label="Telepon" value={application.phone} /><Info label="Lahir" value={`${application.birth_place}, ${formatDate(application.birth_date)}`} /><Info label="Jenis kelamin" value={application.gender === 'L' ? 'Laki-laki' : 'Perempuan'} /><Info label="Sekolah / lulus" value={`${application.previous_school} · ${application.graduation_year}`} /><Info label="Orang tua/wali" value={application.guardian_name} /><Info label="Telepon wali" value={application.guardian_phone} /></div><div className="mt-3 rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Alamat</p><p className="mt-2 text-sm leading-6 text-slate-700">{application.address}</p></div></section>
        <section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><Title icon={<ShieldCheck size={18} />} text="Pilihan dan invoice" /><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info label="Program" value={application.program ? `${application.program.code} · ${application.program.name}` : '—'} /><Info label="Jalur / jenis" value={`${application.registration_path} · ${application.registration_type}`} /><Info label="Gelombang" value={application.registration_wave || 'Umum'} /><Info label="Tanggal submit" value={application.submitted_at ? formatDate(application.submitted_at) : '—'} /></div>{application.invoice && <div className="mt-4 rounded-xl bg-[#071827] p-4 text-white"><p className="font-mono text-xs text-teal-200">{application.invoice.invoice_number}</p><p className="mt-2 text-xl font-semibold">{formatMoney(application.invoice.amount)}</p><p className="mt-1 text-[10px] uppercase text-slate-400">{application.invoice.status}</p>{application.invoice.virtual_account && <p className="mt-3 rounded-lg bg-white/10 px-3 py-2 font-mono text-xs text-teal-100">VA {application.invoice.virtual_account.va_number}</p>}</div>}</section></div>

      <div className="space-y-6"><section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><Title icon={<FileText size={18} />} text="Pemeriksaan dokumen" /><p className="mt-2 text-xs text-slate-400">Download melewati authorization dan file tetap berada pada storage privat.</p><div className="mt-5 space-y-4">{Object.entries(documentRequirements).map(([type, label]) => { const document = application.documents.find((item) => item.type === type); return <div key={type} className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-100">{document ? <><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><p className="text-sm font-semibold text-slate-800">{label}</p><DocumentStatus value={document.status} /></div><p className="mt-1 truncate text-xs text-slate-400">{document.original_name} · {formatBytes(document.size)}</p></div>{abilities.download && <a href={`/admin/pmb/applications/${application.id}/documents/${document.id}`} className="flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-[10px] font-semibold text-teal-700 ring-1 ring-slate-200"><Download size={13} /> Download</a>}</div>{abilities.review && application.status === 'submitted' && <div className="mt-4"><textarea value={notes[document.id] ?? ''} onChange={(e) => setNotes({ ...notes, [document.id]: e.target.value })} className="input min-h-16" placeholder="Catatan wajib jika dokumen ditolak" /><div className="mt-2 flex gap-2"><button onClick={() => decide(document, 'verified')} className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-emerald-50 py-2 text-[10px] font-semibold text-emerald-700"><CheckCircle2 size={13} /> Setujui</button><button onClick={() => decide(document, 'rejected')} className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-rose-50 py-2 text-[10px] font-semibold text-rose-700"><XCircle size={13} /> Tolak</button></div></div>}{document.notes && <p className="mt-3 rounded-lg bg-white p-3 text-xs text-slate-600">Catatan: {document.notes}</p>}</> : <div className="flex items-center gap-2 text-xs text-rose-600"><AlertTriangle size={15} /> {label} belum tersedia.</div>}</div>; })}</div></section>
        {abilities.review && application.status === 'submitted' && <section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><Title icon={<BadgeCheck size={18} />} text="Finalisasi verifikasi" />{(actionForm.errors as Record<string, string>).application && <p className="mt-4 text-xs text-rose-600">{(actionForm.errors as Record<string, string>).application}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={returnForCorrection} disabled={!hasRejected || actionForm.processing} className="flex items-center justify-center gap-2 rounded-xl bg-amber-50 py-3 text-xs font-semibold text-amber-700 disabled:opacity-40"><RotateCcw size={15} /> Kembalikan untuk koreksi</button><button onClick={verify} disabled={!allVerified || actionForm.processing} className="flex items-center justify-center gap-2 rounded-xl bg-teal-600 py-3 text-xs font-semibold text-white disabled:opacity-40"><BadgeCheck size={15} /> Verifikasi aplikasi</button></div></section>}
      </div>
    </div>
  </DashboardLayout>;
}

function Title({ icon, text }: { icon: ReactNode; text: string }) { return <div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-teal-50 text-teal-600">{icon}</span><h2 className="font-semibold text-slate-900">{text}</h2></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1.5 text-xs font-semibold text-slate-700">{value}</p></div>; }
function Status({ value }: { value: string }) { return <span className="self-start rounded-full bg-teal-50 px-3 py-1.5 text-xs font-bold uppercase text-teal-700">{value}</span>; }
function DocumentStatus({ value }: { value: Document['status'] }) { const tone = value === 'verified' ? 'bg-emerald-100 text-emerald-700' : value === 'rejected' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700'; return <span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase ${tone}`}>{value}</span>; }
function formatBytes(bytes: number) { return bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function formatDate(value: string) { return new Date(value).toLocaleDateString('id-ID', { dateStyle: 'long' }); }
function formatMoney(value: string) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value)); }
