import { Head, router, useForm } from '@inertiajs/react';
import { AlertTriangle, Archive, Check, CheckCircle2, ChevronLeft, ChevronRight, Download, FileSpreadsheet, GraduationCap, History, Pencil, Plus, RotateCcw, Search, Trash2, Upload, UserRoundCheck, UsersRound, X } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Page<T> = { data: T[]; current_page: number; last_page: number; total: number };
type Program = { id: number; name: string; code: string };
type Term = { id: number; name: string; code: string };
type User = { id: number; name: string; email: string };
type Advisor = { id: number; program_id: number; name: string; nidn: string };
type StatusHistory = { id: number; from_status: string | null; to_status: string; effective_on: string; reason: string; academic_term: Term | null; changed_by: Pick<User, 'id' | 'name'> | null };
type Student = { id: number; user_id: number; program_id: number; academic_advisor_id: number | null; admission_term_id: number | null; nim: string; cohort_year: number; registration_type: string; gender: string | null; birth_date: string | null; phone: string | null; address: string | null; status: string; current_semester: number; deleted_at: string | null; user: User; program: Program; academic_advisor: Advisor | null; admission_term?: Term | null; status_histories?: StatusHistory[] };
type Filters = { q: string; program_id: string; student_status: string; cohort_year: string; archive: 'available' | 'archived'; selected: number | null };
type ImportRow = { line: number; values: Record<string, string>; action: 'create' | 'update'; errors: Record<string, string[]> };
type ImportPreview = { token: string; file_name: string; total_rows: number; valid_rows: number; error_rows: number; rows: ImportRow[] };
type Props = { filters: Filters; students: Page<Student>; selectedStudent: Student | null; programOptions: Program[]; termOptions: Term[]; advisorOptions: Advisor[]; userOptions: User[]; summary: { total: number; active: number; leave: number; graduates: number; archived: number }; abilities: { create: boolean; update: boolean; delete: boolean }; transferAbility: { import: boolean; export: boolean }; importPreview: ImportPreview | null };
type StudentForm = { user_id: string; program_id: string; academic_advisor_id: string; admission_term_id: string; nim: string; cohort_year: number; registration_type: string; gender: string; birth_date: string; phone: string; address: string; current_semester: number };
type StatusForm = { status: string; academic_term_id: string; effective_on: string; reason: string };

const initialStudent: StudentForm = { user_id: '', program_id: '', academic_advisor_id: '', admission_term_id: '', nim: '', cohort_year: new Date().getFullYear(), registration_type: 'Reguler', gender: '', birth_date: '', phone: '', address: '', current_semester: 1 };
const initialStatus: StatusForm = { status: 'Cuti', academic_term_id: '', effective_on: new Date().toISOString().slice(0, 10), reason: '' };

export default function Students({ filters, students, selectedStudent, programOptions, termOptions, advisorOptions, userOptions, summary, abilities, transferAbility, importPreview }: Props) {
  const [filterData, setFilterData] = useState(filters);
  const [editing, setEditing] = useState<number | null>(null);
  const studentForm = useForm<StudentForm>(initialStudent);
  const statusForm = useForm<StatusForm>(initialStatus);
  const importForm = useForm<{ file: File | null }>({ file: null });
  const confirmForm = useForm({});
  const [selectedStudents, setSelectedStudents] = useState<number[]>([]);
  const archived = Boolean(selectedStudent?.deleted_at);

  function submitStudent(event: FormEvent) {
    event.preventDefault(); const options = { preserveScroll: true, onSuccess: resetStudent };
    if (editing) { studentForm.patch(`/admin/students/${editing}`, options); return; }
    studentForm.post('/admin/students', options);
  }
  function editStudent(item: Student) {
    setEditing(item.id); studentForm.setData({ user_id: String(item.user_id), program_id: String(item.program_id), academic_advisor_id: item.academic_advisor_id ? String(item.academic_advisor_id) : '', admission_term_id: item.admission_term_id ? String(item.admission_term_id) : '', nim: item.nim, cohort_year: item.cohort_year, registration_type: item.registration_type, gender: item.gender ?? '', birth_date: item.birth_date?.slice(0, 10) ?? '', phone: item.phone ?? '', address: item.address ?? '', current_semester: item.current_semester }); studentForm.clearErrors(); window.scrollTo({ top: 0, behavior: 'smooth' });
  }
  function resetStudent() { setEditing(null); studentForm.reset(); studentForm.clearErrors(); }
  function submitStatus(event: FormEvent) { event.preventDefault(); if (!selectedStudent) return; statusForm.post(`/admin/students/${selectedStudent.id}/status`, { preserveScroll: true, onSuccess: () => statusForm.reset() }); }
  function applyFilters(event: FormEvent) { event.preventDefault(); setSelectedStudents([]); router.get('/admin/students', { ...filterData, selected: undefined }, { preserveState: true, replace: true }); }
  function selectStudent(id: number) { router.get('/admin/students', { q: filterData.q, program_id: filterData.program_id, student_status: filterData.student_status, cohort_year: filterData.cohort_year, archive: filterData.archive, selected: id }, { preserveState: true, replace: true }); }
  function paginate(page: number) { setSelectedStudents([]); router.get('/admin/students', { ...filterData, page }, { preserveState: true, replace: true }); }
  function previewImport(event: FormEvent) { event.preventDefault(); importForm.post('/admin/students/import/preview', { forceFormData: true, preserveScroll: true }); }
  function confirmImport() { if (importPreview) confirmForm.post(`/admin/students/imports/${importPreview.token}/confirm`, { preserveScroll: true }); }
  function cancelImport() { if (importPreview) router.delete(`/admin/students/imports/${importPreview.token}`, { preserveScroll: true }); }
  function toggleStudent(id: number) { setSelectedStudents((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  function bulkStudents() { const action = filterData.archive === 'archived' ? 'restore' : 'archive'; if (!selectedStudents.length || !window.confirm(`${action === 'restore' ? 'Pulihkan' : 'Arsipkan'} ${selectedStudents.length} mahasiswa?`)) return; router.post('/admin/students/bulk', { action, ids: selectedStudents }, { preserveScroll: true, onSuccess: () => setSelectedStudents([]) }); }
  const advisors = advisorOptions.filter((item) => !studentForm.data.program_id || item.program_id === Number(studentForm.data.program_id));

  return <DashboardLayout>
    <Head title="Mahasiswa" />
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-medium text-teal-600">Master akademik</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">Mahasiswa.</h1><p className="mt-2 text-sm text-slate-500">Kelola identitas akademik, dosen wali, angkatan, dan riwayat status mahasiswa.</p></div><div className="flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-slate-600 ring-1 ring-slate-200"><Archive size={16} className="text-teal-600" /> {summary.archived} mahasiswa diarsipkan</div></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={<UsersRound size={18} />} label="Mahasiswa tersedia" value={summary.total} /><Summary icon={<UserRoundCheck size={18} />} label="Status aktif" value={summary.active} /><Summary icon={<History size={18} />} label="Sedang cuti" value={summary.leave} /><Summary icon={<GraduationCap size={18} />} label="Lulus" value={summary.graduates} /></div>

    <section className="mt-6 rounded-2xl bg-white p-5 ring-1 ring-slate-200/80"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-teal-50 text-teal-600"><FileSpreadsheet size={18} /></div><div><h2 className="text-sm font-semibold text-slate-900">Transfer CSV mahasiswa</h2><p className="mt-1 text-xs text-slate-400">Akun memakai email aktif; perubahan status tetap melalui workflow riwayat status.</p></div></div><div className="flex gap-2">{transferAbility.export && <a href="/admin/students/template" className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-semibold text-slate-600 ring-1 ring-slate-200"><FileSpreadsheet size={15} /> Template</a>}{transferAbility.export && <a href="/admin/students/export" className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-semibold text-slate-600 ring-1 ring-slate-200"><Download size={15} /> Export</a>}</div></div><form onSubmit={previewImport} className="mt-5 flex min-w-0 gap-2"><input required type="file" accept=".csv,text/csv" onChange={(event) => importForm.setData('file', event.target.files?.[0] ?? null)} className="min-w-0 flex-1 rounded-xl bg-slate-50 px-3 py-2 text-xs text-slate-500 ring-1 ring-slate-200 file:mr-3 file:rounded-lg file:border-0 file:bg-slate-900 file:px-3 file:py-1.5 file:text-xs file:font-semibold file:text-white" /><button disabled={!transferAbility.import || importForm.processing} className="flex items-center gap-2 rounded-xl bg-teal-600 px-4 text-xs font-semibold text-white disabled:opacity-40"><Upload size={15} /> Preview</button></form>{importForm.errors.file && <p className="mt-3 text-xs text-rose-600">{importForm.errors.file}</p>}</section>

    {importPreview && <section className="mt-6 overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200/80"><div className="flex flex-col gap-4 border-b border-slate-100 p-5 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2">{importPreview.error_rows ? <AlertTriangle size={18} className="text-amber-500" /> : <CheckCircle2 size={18} className="text-emerald-500" />}<h2 className="font-semibold text-slate-900">Preview mahasiswa</h2></div><p className="mt-1 text-xs text-slate-400">{importPreview.file_name} · {importPreview.valid_rows} valid · {importPreview.error_rows} bermasalah</p></div><div className="flex gap-2"><button onClick={cancelImport} className="rounded-xl px-4 py-2.5 text-xs font-semibold text-slate-500 ring-1 ring-slate-200">Batalkan</button><button onClick={confirmImport} disabled={importPreview.error_rows > 0 || confirmForm.processing} className="rounded-xl bg-[#071827] px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-40">Konfirmasi impor</button></div></div>{(confirmForm.errors as Record<string, string>).import && <p className="bg-rose-50 px-5 py-3 text-xs text-rose-600">{(confirmForm.errors as Record<string, string>).import}</p>}<div className="max-h-[380px] overflow-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">Baris</th><th className="px-4 py-3">NIM</th><th className="px-4 py-3">Email akun</th><th className="px-4 py-3">Aksi</th><th className="px-4 py-3">Validasi</th></tr></thead><tbody className="divide-y divide-slate-100">{importPreview.rows.map((row) => { const errors = Object.values(row.errors).flat(); return <tr key={row.line} className={errors.length ? 'bg-rose-50/40' : ''}><td className="px-4 py-3">{row.line}</td><td className="px-4 py-3 font-semibold text-teal-700">{row.values.nim || '—'}</td><td className="px-4 py-3">{row.values.user_email || '—'}</td><td className="px-4 py-3">{row.action === 'create' ? 'Buat' : 'Perbarui'}</td><td className="px-4 py-3">{errors.length ? <ul className="space-y-1 text-rose-600">{errors.map((error, index) => <li key={`${error}-${index}`}>{error}</li>)}</ul> : <span className="text-emerald-600">Siap diimpor</span>}</td></tr>; })}</tbody></table></div></section>}

    <div className="mt-6 grid gap-6 xl:grid-cols-[.72fr_1.28fr]">
      <div className="space-y-6">
        {(abilities.create || editing) && <section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-teal-50 text-teal-600">{editing ? <Pencil size={18} /> : <Plus size={18} />}</div><div className="min-w-0 flex-1"><h2 className="font-semibold text-slate-950">{editing ? 'Edit mahasiswa' : 'Mahasiswa baru'}</h2><p className="text-xs text-slate-400">Status awal otomatis Aktif.</p></div>{editing && <button onClick={resetStudent} className="rounded-lg p-2 text-slate-400"><X size={16} /></button>}</div>
          <form onSubmit={submitStudent} className="mt-6 space-y-4">
            <Field label="Akun pengguna"><select required value={studentForm.data.user_id} onChange={(e) => studentForm.setData('user_id', e.target.value)} className="input"><option value="">Pilih akun</option>{userOptions.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.email}</option>)}</select></Field>
            <Field label="Program studi"><select required value={studentForm.data.program_id} onChange={(e) => studentForm.setData((data) => ({ ...data, program_id: e.target.value, academic_advisor_id: '' }))} className="input"><option value="">Pilih prodi</option>{programOptions.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></Field>
            <div className="grid gap-4 sm:grid-cols-2"><Field label="NIM"><input required value={studentForm.data.nim} onChange={(e) => studentForm.setData('nim', e.target.value.toUpperCase())} className="input" /></Field><Field label="Angkatan"><input required type="number" min="2000" value={studentForm.data.cohort_year} onChange={(e) => studentForm.setData('cohort_year', Number(e.target.value))} className="input" /></Field></div>
            <div className="grid gap-4 sm:grid-cols-2"><Field label="Jenis pendaftaran"><select value={studentForm.data.registration_type} onChange={(e) => studentForm.setData('registration_type', e.target.value)} className="input"><option>Reguler</option><option>Transfer</option><option>Pindahan</option></select></Field><Field label="Semester berjalan"><input required type="number" min="1" max="20" value={studentForm.data.current_semester} onChange={(e) => studentForm.setData('current_semester', Number(e.target.value))} className="input" /></Field></div>
            <Field label="Periode masuk"><select value={studentForm.data.admission_term_id} onChange={(e) => studentForm.setData('admission_term_id', e.target.value)} className="input"><option value="">Belum ditentukan</option>{termOptions.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></Field>
            <Field label="Dosen wali"><select value={studentForm.data.academic_advisor_id} onChange={(e) => studentForm.setData('academic_advisor_id', e.target.value)} className="input"><option value="">Belum ditentukan</option>{advisors.map((item) => <option key={item.id} value={item.id}>{item.nidn} · {item.name}</option>)}</select></Field>
            <div className="grid gap-4 sm:grid-cols-2"><Field label="Jenis kelamin"><select value={studentForm.data.gender} onChange={(e) => studentForm.setData('gender', e.target.value)} className="input"><option value="">Tidak diisi</option><option value="L">Laki-laki</option><option value="P">Perempuan</option></select></Field><Field label="Tanggal lahir"><input type="date" value={studentForm.data.birth_date} onChange={(e) => studentForm.setData('birth_date', e.target.value)} className="input" /></Field></div>
            <Field label="Telepon"><input value={studentForm.data.phone} onChange={(e) => studentForm.setData('phone', e.target.value)} className="input" /></Field><Field label="Alamat"><textarea value={studentForm.data.address} onChange={(e) => studentForm.setData('address', e.target.value)} className="input min-h-20" /></Field>
            <Errors errors={studentForm.errors} /><button disabled={studentForm.processing} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#071827] py-3 font-semibold text-white disabled:opacity-60">{studentForm.processing ? 'Menyimpan...' : editing ? 'Perbarui mahasiswa' : 'Simpan mahasiswa'} <Check size={16} /></button>
          </form></section>}

        <BulkSelector items={students.data} selected={selectedStudents} archived={filterData.archive === 'archived'} enabled={filterData.archive === 'archived' ? abilities.update : abilities.delete} onToggle={toggleStudent} onSubmit={bulkStudents} />

        <section className="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200/80"><form onSubmit={applyFilters} className="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-2"><label className="relative sm:col-span-2"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={filterData.q} onChange={(e) => setFilterData({ ...filterData, q: e.target.value })} className="input pl-9" placeholder="Cari NIM, nama, email" /></label><select value={filterData.program_id} onChange={(e) => setFilterData({ ...filterData, program_id: e.target.value })} className="input"><option value="">Semua prodi</option>{programOptions.map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</select><select value={filterData.student_status} onChange={(e) => setFilterData({ ...filterData, student_status: e.target.value })} className="input"><option value="">Semua status</option>{['Aktif', 'Cuti', 'Lulus', 'Nonaktif'].map((item) => <option key={item}>{item}</option>)}</select><input type="number" value={filterData.cohort_year} onChange={(e) => setFilterData({ ...filterData, cohort_year: e.target.value })} className="input" placeholder="Angkatan" /><div className="flex gap-2"><select value={filterData.archive} onChange={(e) => setFilterData({ ...filterData, archive: e.target.value as Filters['archive'] })} className="input"><option value="available">Tersedia</option><option value="archived">Arsip</option></select><button className="rounded-xl bg-teal-600 px-4 text-white"><Search size={16} /></button></div></form>
          <div className="divide-y divide-slate-100">{students.data.map((item) => <button key={item.id} onClick={() => selectStudent(item.id)} className={`w-full p-4 text-left hover:bg-slate-50 ${selectedStudent?.id === item.id ? 'bg-teal-50/70' : ''}`}><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-800">{item.user.name}</p><p className="mt-1 text-[11px] font-semibold uppercase tracking-wide text-teal-600">{item.nim} · {item.program.code}</p></div><Status value={item.status} /></div><p className="mt-2 text-xs text-slate-400">Angkatan {item.cohort_year} · Semester {item.current_semester} · Wali: {item.academic_advisor?.name ?? '—'}</p></button>)}{students.data.length === 0 && <p className="p-8 text-center text-xs text-slate-400">Belum ada mahasiswa.</p>}</div><div className="flex items-center justify-between border-t border-slate-100 px-4 py-3 text-xs text-slate-400"><span>Halaman {students.current_page} / {students.last_page}</span><div className="flex gap-1"><button onClick={() => paginate(students.current_page - 1)} disabled={students.current_page <= 1} className="p-1.5 disabled:opacity-30"><ChevronLeft size={14} /></button><button onClick={() => paginate(students.current_page + 1)} disabled={students.current_page >= students.last_page} className="p-1.5 disabled:opacity-30"><ChevronRight size={14} /></button></div></div></section>
      </div>

      <div className="min-w-0 space-y-6">{!selectedStudent ? <section className="rounded-2xl bg-white p-12 text-center ring-1 ring-slate-200/80"><UsersRound className="mx-auto text-slate-300" /><p className="mt-4 text-sm text-slate-500">Pilih mahasiswa untuk melihat detail.</p></section> : <>
        <section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><div className="flex justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-xl font-semibold text-slate-950">{selectedStudent.user.name}</h2><Status value={selectedStudent.status} />{archived && <span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-semibold text-amber-700">Arsip</span>}</div><p className="mt-1 text-xs font-semibold text-teal-600">{selectedStudent.nim} · {selectedStudent.program.name}</p><p className="mt-3 text-sm text-slate-500">{selectedStudent.user.email}</p></div><div className="flex gap-2">{archived ? abilities.update && <button onClick={() => router.patch(`/admin/students/${selectedStudent.id}/restore`)} className="rounded-xl bg-teal-50 p-2.5 text-teal-700"><RotateCcw size={16} /></button> : <>{abilities.update && <button onClick={() => editStudent(selectedStudent)} className="rounded-xl bg-slate-100 p-2.5 text-slate-600"><Pencil size={16} /></button>}{abilities.delete && <button onClick={() => window.confirm('Arsipkan mahasiswa?') && router.delete(`/admin/students/${selectedStudent.id}`)} className="rounded-xl bg-rose-50 p-2.5 text-rose-600"><Trash2 size={16} /></button>}</>}</div></div><div className="mt-6 grid gap-3 text-xs sm:grid-cols-2"><Info label="Angkatan" value={String(selectedStudent.cohort_year)} /><Info label="Semester" value={String(selectedStudent.current_semester)} /><Info label="Jenis masuk" value={selectedStudent.registration_type} /><Info label="Periode masuk" value={selectedStudent.admission_term?.name ?? '—'} /><Info label="Dosen wali" value={selectedStudent.academic_advisor?.name ?? '—'} /><Info label="Telepon" value={selectedStudent.phone ?? '—'} /></div></section>
        {!archived && abilities.update && <section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><h3 className="font-semibold text-slate-900">Perubahan status</h3><p className="mt-1 text-xs text-slate-400">Status Lulus bersifat terminal dan riwayat tidak dapat dihapus.</p><form onSubmit={submitStatus} className="mt-4 grid gap-3 md:grid-cols-2"><select value={statusForm.data.status} onChange={(e) => statusForm.setData('status', e.target.value)} className="input">{['Aktif', 'Cuti', 'Lulus', 'Nonaktif'].map((item) => <option key={item}>{item}</option>)}</select><input required type="date" value={statusForm.data.effective_on} onChange={(e) => statusForm.setData('effective_on', e.target.value)} className="input" /><select value={statusForm.data.academic_term_id} onChange={(e) => statusForm.setData('academic_term_id', e.target.value)} className="input md:col-span-2"><option value="">Tanpa periode</option>{termOptions.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select><textarea required value={statusForm.data.reason} onChange={(e) => statusForm.setData('reason', e.target.value)} className="input min-h-20 md:col-span-2" placeholder="Alasan perubahan status" /><div className="md:col-span-2"><Errors errors={statusForm.errors} /></div><button disabled={statusForm.processing} className="rounded-xl bg-teal-600 py-2.5 text-sm font-semibold text-white md:col-span-2">Simpan perubahan status</button></form></section>}
        <section className="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200/80"><div className="border-b border-slate-100 px-5 py-4"><h3 className="font-semibold text-slate-900">Riwayat status</h3></div><div className="divide-y divide-slate-100">{selectedStudent.status_histories?.map((item) => <div key={item.id} className="px-5 py-4"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-700">{item.from_status ?? 'Awal'} → {item.to_status}</p><span className="text-xs text-slate-400">{new Date(item.effective_on).toLocaleDateString('id-ID')}</span></div><p className="mt-2 text-xs text-slate-500">{item.reason}</p><p className="mt-1 text-[11px] text-slate-400">{item.academic_term?.code ?? 'Tanpa periode'} · {item.changed_by?.name ?? 'Sistem'}</p></div>)}{!selectedStudent.status_histories?.length && <p className="p-8 text-center text-xs text-slate-400">Belum ada riwayat.</p>}</div></section>
      </>}</div>
    </div>
  </DashboardLayout>;
}

function BulkSelector({ items, selected, archived, enabled, onToggle, onSubmit }: { items: Student[]; selected: number[]; archived: boolean; enabled: boolean; onToggle: (id: number) => void; onSubmit: () => void }) { if (!enabled || items.length === 0) return null; return <div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200/80"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-slate-700">Bulk mahasiswa pada halaman ini</p><button disabled={selected.length === 0} onClick={onSubmit} className="rounded-lg bg-slate-900 px-3 py-1.5 text-[10px] font-semibold text-white disabled:opacity-30">{archived ? 'Pulihkan' : 'Arsipkan'} {selected.length || ''}</button></div><div className="mt-3 flex max-h-24 flex-wrap gap-2 overflow-auto">{items.map((item) => { const eligible = archived || ['Lulus', 'Nonaktif'].includes(item.status); return <label key={item.id} className={`flex items-center gap-2 rounded-lg px-2.5 py-1.5 text-[10px] ring-1 ${eligible ? 'cursor-pointer' : 'cursor-not-allowed opacity-40'} ${selected.includes(item.id) ? 'bg-teal-50 text-teal-700 ring-teal-200' : 'text-slate-500 ring-slate-200'}`}><input disabled={!eligible} type="checkbox" checked={selected.includes(item.id)} onChange={() => onToggle(item.id)} />{item.nim} · {item.user.name}</label>; })}</div></div>; }
function Summary({ icon, label, value }: { icon: ReactNode; label: string; value: number }) { return <div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200/80"><div className="flex items-center justify-between"><span className="text-teal-600">{icon}</span><span className="text-2xl font-semibold text-slate-950">{value.toLocaleString('id-ID')}</span></div><p className="mt-3 text-xs text-slate-500">{label}</p></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
function Errors({ errors }: { errors: Partial<Record<string, string>> }) { return <>{Object.values(errors).map((error, index) => <p key={`${error}-${index}`} className="text-xs text-rose-600">{error}</p>)}</>; }
function Status({ value }: { value: string }) { const tone = value === 'Aktif' ? 'bg-emerald-50 text-emerald-700' : value === 'Lulus' ? 'bg-blue-50 text-blue-700' : value === 'Cuti' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600'; return <span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${tone}`}>{value}</span>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-slate-400">{label}</p><p className="mt-1 font-semibold text-slate-700">{value}</p></div>; }
