import { Head, router, useForm } from '@inertiajs/react';
import { AlertTriangle, Archive, Check, CheckCircle2, ChevronLeft, ChevronRight, Download, FileSpreadsheet, KeyRound, Pencil, Plus, RotateCcw, Search, ShieldCheck, Trash2, Upload, UserCheck, UsersRound, X } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { DashboardLayout } from '@/layouts/DashboardLayout';

type Role = { id: number; name: string };
type User = { id: number; name: string; username: string | null; email: string; is_active: boolean; active_role: string; deleted_at: string | null; roles: Role[] };
type Page<T> = { data: T[]; current_page: number; last_page: number; total: number };
type Filters = { q: string; role: string; state: string; archive: 'available' | 'archived'; selected: number | null };
type ImportRow = { line: number; values: Record<string, string>; action: 'update'; errors: Record<string, string[]> };
type ImportPreview = { token: string; file_name: string; total_rows: number; valid_rows: number; error_rows: number; rows: ImportRow[] };
type Form = { name: string; username: string; email: string; password: string; password_confirmation: string; is_active: boolean; roles: string[]; active_role: string };
type Props = { filters: Filters; users: Page<User>; selectedUser: User | null; roleOptions: string[]; summary: { total: number; active: number; multiRole: number; archived: number }; abilities: { create: boolean; update: boolean; delete: boolean }; transferAbility: { import: boolean; export: boolean }; importPreview: ImportPreview | null; currentUserId: number };

const initialForm: Form = { name: '', username: '', email: '', password: '', password_confirmation: '', is_active: true, roles: [], active_role: '' };

export default function Users({ filters, users, selectedUser, roleOptions, summary, abilities, transferAbility, importPreview, currentUserId }: Props) {
  const [filterData, setFilterData] = useState(filters);
  const [editing, setEditing] = useState<number | null>(null);
  const form = useForm<Form>(initialForm);
  const importForm = useForm<{ file: File | null }>({ file: null });
  const confirmForm = useForm({});
  const [selectedUsers, setSelectedUsers] = useState<number[]>([]);
  const [bulkAction, setBulkAction] = useState<'activate' | 'deactivate' | 'archive' | 'restore'>(filters.archive === 'archived' ? 'restore' : abilities.update ? 'deactivate' : 'archive');
  const archived = Boolean(selectedUser?.deleted_at);

  function submit(event: FormEvent) {
    event.preventDefault();
    const options = { preserveScroll: true, onSuccess: resetForm };
    if (editing) { form.patch(`/admin/users/${editing}`, options); return; }
    form.post('/admin/users', options);
  }

  function edit(user: User) {
    const roles = user.roles.map((role) => role.name);
    setEditing(user.id);
    form.setData({ name: user.name, username: user.username ?? '', email: user.email, password: '', password_confirmation: '', is_active: user.is_active, roles, active_role: roles.includes(user.active_role) ? user.active_role : (roles[0] ?? '') });
    form.clearErrors();
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  function resetForm() { setEditing(null); form.reset(); form.clearErrors(); }
  function toggleRole(role: string) {
    const roles = form.data.roles.includes(role) ? form.data.roles.filter((item) => item !== role) : [...form.data.roles, role];
    form.setData((data) => ({ ...data, roles, active_role: roles.includes(data.active_role) ? data.active_role : (roles[0] ?? '') }));
  }
  function applyFilters(event: FormEvent) { event.preventDefault(); setSelectedUsers([]); router.get('/admin/users', { ...filterData, selected: undefined }, { preserveState: true, replace: true }); }
  function selectUser(id: number) { router.get('/admin/users', { ...filterData, selected: id }, { preserveState: true, replace: true }); }
  function paginate(page: number) { setSelectedUsers([]); router.get('/admin/users', { ...filterData, page }, { preserveState: true, replace: true }); }
  function previewImport(event: FormEvent) { event.preventDefault(); importForm.post('/admin/users/import/preview', { forceFormData: true, preserveScroll: true }); }
  function confirmImport() { if (importPreview) confirmForm.post(`/admin/users/imports/${importPreview.token}/confirm`, { preserveScroll: true }); }
  function cancelImport() { if (importPreview) router.delete(`/admin/users/imports/${importPreview.token}`, { preserveScroll: true }); }
  function toggleUser(id: number) { setSelectedUsers((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  function runBulk() { if (!selectedUsers.length || !window.confirm(`Jalankan aksi ${bulkAction} pada ${selectedUsers.length} akun?`)) return; router.post('/admin/users/bulk', { action: bulkAction, ids: selectedUsers }, { preserveScroll: true, onSuccess: () => setSelectedUsers([]) }); }

  return <DashboardLayout>
    <Head title="Manajemen Pengguna" />
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-medium text-teal-600">Pengaturan akses</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-slate-950">Manajemen pengguna.</h1><p className="mt-2 text-sm text-slate-500">Kelola akun, multi-role, role aktif, status akses, dan reset kata sandi.</p></div><div className="flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-slate-600 ring-1 ring-slate-200"><Archive size={16} className="text-teal-600" /> {summary.archived} akun diarsipkan</div></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={<UsersRound size={18} />} label="Akun tersedia" value={summary.total} /><Summary icon={<UserCheck size={18} />} label="Akun aktif" value={summary.active} /><Summary icon={<ShieldCheck size={18} />} label="Akun multi-role" value={summary.multiRole} /><Summary icon={<Archive size={18} />} label="Dalam arsip" value={summary.archived} /></div>

    <section className="mt-6 rounded-2xl bg-white p-5 ring-1 ring-slate-200/80"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-teal-50 text-teal-600"><FileSpreadsheet size={18} /></div><div><h2 className="text-sm font-semibold text-slate-900">Sinkronisasi CSV pengguna</h2><p className="mt-1 text-xs text-slate-400">Hanya memperbarui akun tersedia berdasarkan email. Kata sandi tidak pernah diekspor atau dibaca dari CSV.</p></div></div><div className="flex gap-2"><a href="/admin/users/template" className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-semibold text-slate-600 ring-1 ring-slate-200"><FileSpreadsheet size={15} /> Template</a>{transferAbility.export && <a href="/admin/users/export" className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-semibold text-slate-600 ring-1 ring-slate-200"><Download size={15} /> Export</a>}</div></div><form onSubmit={previewImport} className="mt-5 flex min-w-0 gap-2"><input required type="file" accept=".csv,text/csv" onChange={(event) => importForm.setData('file', event.target.files?.[0] ?? null)} className="min-w-0 flex-1 rounded-xl bg-slate-50 px-3 py-2 text-xs text-slate-500 ring-1 ring-slate-200 file:mr-3 file:rounded-lg file:border-0 file:bg-slate-900 file:px-3 file:py-1.5 file:text-xs file:font-semibold file:text-white" /><button disabled={!transferAbility.import || importForm.processing} className="flex items-center gap-2 rounded-xl bg-teal-600 px-4 text-xs font-semibold text-white disabled:opacity-40"><Upload size={15} /> Preview</button></form>{importForm.errors.file && <p className="mt-3 text-xs text-rose-600">{importForm.errors.file}</p>}</section>

    {importPreview && <section className="mt-6 overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200/80"><div className="flex flex-col gap-4 border-b border-slate-100 p-5 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2">{importPreview.error_rows ? <AlertTriangle size={18} className="text-amber-500" /> : <CheckCircle2 size={18} className="text-emerald-500" />}<h2 className="font-semibold text-slate-900">Preview sinkronisasi akun</h2></div><p className="mt-1 text-xs text-slate-400">{importPreview.file_name} · {importPreview.valid_rows} valid · {importPreview.error_rows} bermasalah</p></div><div className="flex gap-2"><button onClick={cancelImport} className="rounded-xl px-4 py-2.5 text-xs font-semibold text-slate-500 ring-1 ring-slate-200">Batalkan</button><button onClick={confirmImport} disabled={importPreview.error_rows > 0 || confirmForm.processing} className="rounded-xl bg-[#071827] px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-40">Konfirmasi sinkronisasi</button></div></div>{(confirmForm.errors as Record<string, string>).import && <p className="bg-rose-50 px-5 py-3 text-xs text-rose-600">{(confirmForm.errors as Record<string, string>).import}</p>}<div className="max-h-[380px] overflow-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">Baris</th><th className="px-4 py-3">Email</th><th className="px-4 py-3">Nama</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Validasi</th></tr></thead><tbody className="divide-y divide-slate-100">{importPreview.rows.map((row) => { const errors = Object.values(row.errors).flat(); return <tr key={row.line} className={errors.length ? 'bg-rose-50/40' : ''}><td className="px-4 py-3">{row.line}</td><td className="px-4 py-3 font-semibold text-teal-700">{row.values.email || '—'}</td><td className="px-4 py-3">{row.values.name || '—'}</td><td className="px-4 py-3">{row.values.roles || '—'}</td><td className="px-4 py-3">{errors.length ? <ul className="space-y-1 text-rose-600">{errors.map((error, index) => <li key={`${error}-${index}`}>{error}</li>)}</ul> : <span className="text-emerald-600">Siap disinkronkan</span>}</td></tr>; })}</tbody></table></div></section>}

    <div className="mt-6 grid gap-6 xl:grid-cols-[.72fr_1.28fr]">
      <div className="space-y-6">
        {(abilities.create || editing) && <section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-teal-50 text-teal-600">{editing ? <Pencil size={18} /> : <Plus size={18} />}</div><div className="min-w-0 flex-1"><h2 className="font-semibold text-slate-950">{editing ? 'Edit akun' : 'Akun baru'}</h2><p className="text-xs text-slate-400">Kata sandi minimal 12 karakter.</p></div>{editing && <button onClick={resetForm} className="rounded-lg p-2 text-slate-400"><X size={16} /></button>}</div>
          <form onSubmit={submit} className="mt-6 space-y-4">
            <Field label="Nama lengkap"><input required value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} className="input" /></Field>
            <div className="grid gap-4 sm:grid-cols-2"><Field label="Username"><input value={form.data.username} onChange={(event) => form.setData('username', event.target.value.toLowerCase())} className="input" placeholder="Opsional" /></Field><Field label="Email"><input required type="email" value={form.data.email} onChange={(event) => form.setData('email', event.target.value)} className="input" /></Field></div>
            <div className="grid gap-4 sm:grid-cols-2"><Field label={editing ? 'Kata sandi baru' : 'Kata sandi'}><input required={!editing} type="password" minLength={12} value={form.data.password} onChange={(event) => form.setData('password', event.target.value)} className="input" placeholder={editing ? 'Kosongkan jika tetap' : 'Minimal 12 karakter'} /></Field><Field label="Konfirmasi kata sandi"><input required={!editing || form.data.password.length > 0} type="password" value={form.data.password_confirmation} onChange={(event) => form.setData('password_confirmation', event.target.value)} className="input" /></Field></div>
            <Field label="Role"><div className="grid gap-2 sm:grid-cols-2">{roleOptions.map((role) => <label key={role} className={`flex cursor-pointer items-center gap-2 rounded-xl px-3 py-2.5 text-xs font-semibold ring-1 ${form.data.roles.includes(role) ? 'bg-teal-50 text-teal-700 ring-teal-200' : 'text-slate-500 ring-slate-200'}`}><input type="checkbox" checked={form.data.roles.includes(role)} onChange={() => toggleRole(role)} />{role}</label>)}</div></Field>
            <div className="grid gap-4 sm:grid-cols-2"><Field label="Role aktif"><select required value={form.data.active_role} onChange={(event) => form.setData('active_role', event.target.value)} className="input"><option value="">Pilih role</option>{form.data.roles.map((role) => <option key={role}>{role}</option>)}</select></Field><Field label="Status akun"><label className="flex h-[42px] items-center gap-3 rounded-xl bg-slate-50 px-3 text-sm text-slate-600 ring-1 ring-slate-200"><input type="checkbox" checked={form.data.is_active} onChange={(event) => form.setData('is_active', event.target.checked)} /> Aktif dan dapat masuk</label></Field></div>
            <Errors errors={form.errors} /><button disabled={form.processing} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#071827] py-3 font-semibold text-white disabled:opacity-60">{form.processing ? 'Menyimpan...' : editing ? 'Perbarui akun' : 'Simpan akun'} <Check size={16} /></button>
          </form></section>}

        <BulkSelector items={users.data} selected={selectedUsers} archived={filterData.archive === 'archived'} currentUserId={currentUserId} canUpdate={abilities.update} canDelete={abilities.delete} action={bulkAction} onAction={setBulkAction} onToggle={toggleUser} onSubmit={runBulk} />

        <section className="overflow-hidden rounded-2xl bg-white ring-1 ring-slate-200/80"><form onSubmit={applyFilters} className="grid gap-3 border-b border-slate-100 p-4 sm:grid-cols-2"><label className="relative sm:col-span-2"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={filterData.q} onChange={(event) => setFilterData({ ...filterData, q: event.target.value })} className="input pl-9" placeholder="Cari nama, username, atau email" /></label><select value={filterData.role} onChange={(event) => setFilterData({ ...filterData, role: event.target.value })} className="input"><option value="">Semua role</option>{roleOptions.map((role) => <option key={role}>{role}</option>)}</select><select value={filterData.state} onChange={(event) => setFilterData({ ...filterData, state: event.target.value })} className="input"><option value="">Semua status</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select><select value={filterData.archive} onChange={(event) => { const archive = event.target.value as Filters['archive']; setFilterData({ ...filterData, archive }); setBulkAction(archive === 'archived' ? 'restore' : abilities.update ? 'deactivate' : 'archive'); setSelectedUsers([]); }} className="input"><option value="available">Tersedia</option><option value="archived">Arsip</option></select><button className="flex items-center justify-center gap-2 rounded-xl bg-teal-600 px-4 text-sm font-semibold text-white"><Search size={16} /> Terapkan</button></form>
          <div className="divide-y divide-slate-100">{users.data.map((user) => <button key={user.id} onClick={() => selectUser(user.id)} className={`w-full p-4 text-left hover:bg-slate-50 ${selectedUser?.id === user.id ? 'bg-teal-50/70' : ''}`}><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-800">{user.name}{user.id === currentUserId && <span className="ml-2 text-[10px] text-teal-600">ANDA</span>}</p><p className="mt-1 truncate text-xs text-slate-400">{user.email}</p></div><Status active={user.is_active} /></div><div className="mt-2 flex flex-wrap gap-1">{user.roles.map((role) => <RoleBadge key={role.id} name={role.name} active={role.name === user.active_role} />)}</div></button>)}{users.data.length === 0 && <p className="p-8 text-center text-xs text-slate-400">Tidak ada akun yang sesuai.</p>}</div><div className="flex items-center justify-between border-t border-slate-100 px-4 py-3 text-xs text-slate-400"><span>Halaman {users.current_page} / {users.last_page}</span><div className="flex gap-1"><button onClick={() => paginate(users.current_page - 1)} disabled={users.current_page <= 1} className="p-1.5 disabled:opacity-30"><ChevronLeft size={14} /></button><button onClick={() => paginate(users.current_page + 1)} disabled={users.current_page >= users.last_page} className="p-1.5 disabled:opacity-30"><ChevronRight size={14} /></button></div></div></section>
      </div>

      <div className="min-w-0">{!selectedUser ? <section className="rounded-2xl bg-white p-12 text-center ring-1 ring-slate-200/80"><UsersRound className="mx-auto text-slate-300" /><p className="mt-4 text-sm text-slate-500">Pilih akun untuk melihat detail.</p></section> : <section className="rounded-2xl bg-white p-6 ring-1 ring-slate-200/80"><div className="flex justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold text-slate-950">{selectedUser.name}</h2><Status active={selectedUser.is_active} />{archived && <span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-semibold text-amber-700">Arsip</span>}</div><p className="mt-2 text-sm text-slate-500">{selectedUser.email}</p><p className="mt-1 text-xs text-slate-400">@{selectedUser.username ?? 'tanpa-username'}</p></div><div className="flex gap-2">{archived ? abilities.update && <button title="Pulihkan akun" onClick={() => router.patch(`/admin/users/${selectedUser.id}/restore`)} className="rounded-xl bg-teal-50 p-2.5 text-teal-700"><RotateCcw size={16} /></button> : <>{abilities.update && <button title="Edit atau reset kata sandi" onClick={() => edit(selectedUser)} className="rounded-xl bg-slate-100 p-2.5 text-slate-600"><Pencil size={16} /></button>}{abilities.delete && <button title="Arsipkan akun" onClick={() => window.confirm('Nonaktifkan dan arsipkan akun ini?') && router.delete(`/admin/users/${selectedUser.id}`)} className="rounded-xl bg-rose-50 p-2.5 text-rose-600"><Trash2 size={16} /></button>}</>}</div></div>
          <div className="mt-7 grid gap-3 sm:grid-cols-2"><Info label="Role aktif" value={selectedUser.active_role} icon={<ShieldCheck size={16} />} /><Info label="Akses masuk" value={selectedUser.is_active && !archived ? 'Diizinkan' : 'Diblokir'} icon={<KeyRound size={16} />} /></div>
          <div className="mt-6 border-t border-slate-100 pt-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Role yang dimiliki</p><div className="mt-3 flex flex-wrap gap-2">{selectedUser.roles.map((role) => <RoleBadge key={role.id} name={role.name} active={role.name === selectedUser.active_role} />)}</div><p className="mt-5 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">Role aktif menentukan konteks kerja saat ini. Akun dapat berpindah hanya ke role yang dimilikinya. Akun yang dipulihkan tetap nonaktif sampai administrator mengaktifkannya kembali.</p></div>
        </section>}</div>
    </div>
  </DashboardLayout>;
}

function Summary({ icon, label, value }: { icon: ReactNode; label: string; value: number }) { return <div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200/80"><div className="flex items-center justify-between"><span className="text-teal-600">{icon}</span><span className="text-2xl font-semibold text-slate-950">{value.toLocaleString('id-ID')}</span></div><p className="mt-3 text-xs text-slate-500">{label}</p></div>; }
function BulkSelector({ items, selected, archived, currentUserId, canUpdate, canDelete, action, onAction, onToggle, onSubmit }: { items: User[]; selected: number[]; archived: boolean; currentUserId: number; canUpdate: boolean; canDelete: boolean; action: 'activate' | 'deactivate' | 'archive' | 'restore'; onAction: (action: 'activate' | 'deactivate' | 'archive' | 'restore') => void; onToggle: (id: number) => void; onSubmit: () => void }) { const enabled = archived ? canUpdate : canUpdate || canDelete; if (!enabled || items.length === 0) return null; return <div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200/80"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-semibold text-slate-700">Bulk akun pada halaman ini</p><div className="flex gap-2">{!archived && <select value={action} onChange={(event) => onAction(event.target.value as 'activate' | 'deactivate' | 'archive')} className="rounded-lg px-2 py-1.5 text-[10px] ring-1 ring-slate-200">{canUpdate && <><option value="activate">Aktifkan</option><option value="deactivate">Nonaktifkan</option></>}{canDelete && <option value="archive">Arsipkan</option>}</select>}<button disabled={selected.length === 0} onClick={onSubmit} className="rounded-lg bg-slate-900 px-3 py-1.5 text-[10px] font-semibold text-white disabled:opacity-30">{archived ? 'Pulihkan' : 'Jalankan'} {selected.length || ''}</button></div></div><div className="mt-3 flex max-h-24 flex-wrap gap-2 overflow-auto">{items.map((item) => { const eligible = archived || item.id !== currentUserId; return <label key={item.id} className={`flex items-center gap-2 rounded-lg px-2.5 py-1.5 text-[10px] ring-1 ${eligible ? 'cursor-pointer' : 'cursor-not-allowed opacity-40'} ${selected.includes(item.id) ? 'bg-teal-50 text-teal-700 ring-teal-200' : 'text-slate-500 ring-slate-200'}`}><input disabled={!eligible} type="checkbox" checked={selected.includes(item.id)} onChange={() => onToggle(item.id)} />{item.name} · {item.email}</label>; })}</div></div>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="mb-2 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>; }
function Errors({ errors }: { errors: Partial<Record<string, string>> }) { return <>{Object.values(errors).map((error, index) => <p key={`${error}-${index}`} className="text-xs text-rose-600">{error}</p>)}</>; }
function Status({ active }: { active: boolean }) { return <span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{active ? 'Aktif' : 'Nonaktif'}</span>; }
function RoleBadge({ name, active }: { name: string; active: boolean }) { return <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${active ? 'bg-teal-600 text-white' : 'bg-slate-100 text-slate-600'}`}>{name}{active ? ' · aktif' : ''}</span>; }
function Info({ label, value, icon }: { label: string; value: string; icon: ReactNode }) { return <div className="rounded-xl bg-slate-50 p-4"><span className="text-teal-600">{icon}</span><p className="mt-3 text-xs text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-slate-700">{value}</p></div>; }
